### ISSUE TITLE
Fazer queries com o Eloquent do Laravel

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#10]
Bom dia, estou usando o Eloquent do Laravel para fazer as consultas no meu banco de dados e acabo ficando muito limitado  funções padrões dele. É possível montar queries com o eloquent?
Por exemplo, estou fazendo a seguinte consulta:

`<p>$itens = Iten::with('categorias')</p>`

eu quero limitar a consulta em apenas 10 elementos e ordenar por id decrescente, mas não sei commo fazer isso a partir de uma querie(e nem de outr aforma..) Como devo prosseguir?

**Comment by andreportaro** [comment]
Gabriel, primeiramente o ideal é pesquisar na documentação do eloquent:

https://laravel.com/docs/5.4/eloquent

Existe um método "limit" cujo parâmetro é um int.

Basta concatenar nos métodos:

Iten::with('categorias')->limit(10)->get();

PS: item em Inglês é item mesmo, com "m"




Em 9 de fev de 2017 18:58, "Gabriel Henrique" <notifications@github.com>
escreveu:

Bom dia, estou usando o Eloquent do Laravel para fazer as consaultas no meu
banco de dados e acabo ficando muito limitado funções paddrões dele. É
possível montar queries com o eloquent?
Por exemplo, estou fazendo a seguinte consulta:

<p>$itens = Iten::with('categorias')</p>

eu quero limitar a consulta em apenas 10 elementos e ordenar por id
decrescente, mas não sei commo fazer isso a partir de uma querie(e nem de
outr aforma..) Como devo prosseguir?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravelbrasil/forum/issues/10>, or mute the thread

**Comment by omarkdev** [comment]
```php
$items = Item::take(10)
       ->orderBy('id', 'DESC')
       ->with('categorias')
       ->get()
```

Acredito que seja isso.

**Comment by giordanolima** [comment]
@Gabrieldesousah 
Conseguiu resolver?

**Comment by gabrieldesousah** [comment]
Obrigado galera, eu fiquei confuso com o funcionamento mas deu certo! 
O que eu não entendi foi o seguinte: Por quê precisa usar o get() quando se utiliza do método limit()? Uma vez que não precisa do get() se não usar o limit?

**Comment by cagartner** [comment]
O `->get()` funciona para dizer que você terminou de construir sua query e quer "pegar"/executar para buscar os resultados.

Serve para fazer validações diferentes em alguns casos, ex:

```php
$query = $items = Item::take(10)
       ->orderBy('id', 'DESC')
       ->limit(10)
       ->with('categorias');

if ($user->isAdmin) {
    $query->where('type', '=', 'admin')
}

return $query->get();
```

No exemplo não importa a ordem que você define a query, a montagem dela só se dara quando o método `get()` é executado.

Espero que tenha ajudado.

**Comment by paulofreitas** [comment]
Complementando a resposta do @cagartner:

Quando você usa métodos como o `Model::take()`, `Model::orderBy()` e o `Model::limit()`, você está na verdade chamando métodos fluentes do Query Builder &ndash; seja numa chamada estática ou não.

Internamente, a classe `Model` do Eloquent implementa um método `newQuery()` e outro método estático `query()` que te permite acessar o Query Builder para pesquisar na tabela do model. Para não se ter que chamar estes métodos explicitamente em todas as *queries*, a classe `Model` também implementa os métodos mágicos `__call()` e `__callStatic()` que encaminham ao Query Builder as chamadas de métodos inexistentes (através do método `newQuery()`) de modo que você possa usar o model como se tivesse chamando o Query Builder diretamente.

O Query Builder por sua vez é um construtor de *queries* fluente que te oferece diferentes métodos para filtrar e retornar os resultados. Métodos fluentes como o `take()`, `orderBy()` e `limit()` são métodos de filtragem que apenas modificam as condições das *queries* retornando a própria instância do Query Builder. Para efetivamente retornar os resultados, você precisa chamar os métodos de retorno como o `get()`, o `paginate()`, o `pluck()`, entre vários outros.

Por outro lado, quando você chama um método como o `Model::all()`, você está acessando um método implementado na própria classe `Model` que internamente faz uso do Query Builder para simplificar um caso de uso comum para se obter toda a coleção de registros daquele model &ndash; curiosamente, usar o `Model::all()` corresponde a usar `Model::get()`.

Espero ter lhe ajudado a compreender ainda mais a mágica por trás dos métodos e o que eles efetivamente fazem internamente. 👍

**Comment by cagartner** [comment]
Acredito que esteja já bem claro a explicação, portanto  estou fechando esse issue.

**Comment by browndemon** [comment]
Estou mais ou menos com a mesma coisa só que preciso puxa modelo dos carros pela marca, como ficaria esse elouquent? Já tenho um get por id e quero fazer outro do mesmo jeito só que pela marca.

**Comment by browndemon** [comment]
`public function make($make){
        $carm = Car::where('make', $make);
        return responde()->json($carm);
    }`

**Comment by juniorb2ss** [comment]
@lukinhaloc 

Para passar uma condição para o *query builder* utiliza-se métodos de condição, ou seja `where`, `orWhere`, `whereIn` e etc.

No seu caso, basta filtrar e invocar o método que faz a chama, que no código postado só faltou este, que é método `get`, ficando:

```php
<?php
$cars = Car::where('make', $make)
                     ->get();

return response()->json($cars);
```

Algumas coisas legais.

Graças aos métodos mágicos do PHP, você pode condicionar com métodos, por exemplo:

```php
<?php
$cars = Car::whereMake( $make)
                     ->get();

return response()->json($cars);
```
Que faz a mesma coisa que o código anterior, porém, utilizando método mágico.

Scopes https://laravel.com/docs/5.6/eloquent#query-scopes

É possível também criar escopos pré-definidos e deixar sua syntax mais clara e concisa:

Em teu model, crie uma função que será utilizado como local scope:

```php
   /**
     * Scope a query to get only cars with determined brand.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeBrand($query, string $brand)
    {
        return $query->whereBrand($brand);
    }
```

Para utilizar, basta:

```php
$cars = Cars::brand($brand)->get();
```

:+1:
