### ISSUE TITLE
[Resolvido] Produtos com colunas diferentes

### ISSUE THREAD

**Issue by flipmorsch** [laravelbrasil/forum#105]
Bom dia, pessoal.

Estou trabalhando em um sistema que irá listar diferentes produtos, mas estes produtos possuem dados diferentes. Por exemplo: CPU (socket, clock, consumo, l2, l3), Memória RAM (clock, tamanho, etc). Qual é a melhor forma de fazer isso no Eloquent?

**Comment by petrenkorf** [comment]
Uma das opções é trabalhar utilizando o modelo EAV (Entity - Attribute - Value), mas como toda solução existem prós e contras: Se por um lado você ganha flexibilidade nos dados, você perde no aumento de complexidade e desempenho da aplicação.

**Comment by aviniciustech** [comment]
Não sei se vai te ajudar mas só para te passar o que usei em um projeto que trabalho com esse mesmo caso de cadastro variado.

Tenho um e-commerce com cadastro de produtos bem variado pois se trata de um E-commerce + EAD, ou seja, tenho cursos online, pdf, fisico, ao vivo e mais, primeira versão estava em um banco relacional assim, gerando várias estruturas EAV deixando as consultas bem complexas.

Acabei optando por utilizar o mongodb para essa parte de produtos e não perdi o eloquent pois existe um [projeto](https://github.com/jenssegers/laravel-mongodb) para utiliza o mongodb com ele.

**Comment by fininhors** [comment]
Olá, tem outra possibilidade também. Atualmente os bancos (que eu conheço e uso): MySQL e PostgreSQL tem o tipo de dados JSON. Ou seja, você pode criar o campo características na tabela produtos e salvar em formato json. Dessa forma, cada produto salva apenas as informações que precisa.
Espero ter ajudado.

**Comment by paulofreitas** [comment]
Eu tinha visto essa pergunta mais cedo e só acabei tendo tempo para responder agora que todas as respostas possíveis foram dadas. 😛 

À primeira vista o EAV pode ser tentador pela facilidade de armazenar os dados, mas além de [ser um anti-pattern](https://pragprog.com/book/bksqla/sql-antipatterns) ele vai comprometer bastante a complexidade e desempenho quando você precisar pesquisar essas informações. Fuja dele. 🙁 

Havendo conhecimento em alguma solução de banco de dados orientados a documentos (NoSQL) como o [MongoDB](https://www.mongodb.com/) ou [Apache Cassandra](https://cassandra.apache.org/) você estará bem servido em separar essa parte de produtos neles. Inclusive o [Laravel MongoDB](https://github.com/jenssegers/laravel-mongodb) do Jens Segers é um excelente adendo para trabalhar com o MongoDB no Laravel. 👍 

Uma alternativa a um banco de dados NoSQL é usar as novas colunas JSON do MySQL/MariaDB/PostgreSQL. Pode não parecer em princípio, mas isso torna estes bancos em bancos de dados híbridos (SQL/NoSQL).
Como se pode ver [aqui](https://scotch.io/tutorials/working-with-json-in-mysql) e [aqui](https://www.sitepoint.com/use-json-data-fields-mysql-databases/), o uso das colunas JSON se sobressai ao uso do EAV já que existe facilidade tanto no armazenamento como na consulta das informações. E, como se sabe, [o Laravel torna tudo isso ainda mais fácil](https://mattstauffer.co/blog/new-json-column-where-and-update-syntax-in-laravel-5-3).

Em princípio essa alternativa pode parecer loucura já que no caso do MySQL/MariaDB (não conheço muito do PostgreSQL portanto vou focar no MySQL/MariaDB) não há um suporte direto ao uso de índices nestas colunas, o que pode impactar no desempenho da aplicação à medida que ela for crescendo. Felizmente, isso pode ser contornado de forma brilhante seja com [*flexviews*](https://www.percona.com/blog/2015/02/17/indexing-json-documents-for-efficient-mysql-queries-over-json-data/) ou com [*indexed virtual columns*](https://www.percona.com/blog/2016/03/07/json-document-fast-lookup-with-mysql-5-7/). Essa última é mais simples e [pode produzir resultados incríveis](http://blog.ulf-wendel.de/2016/use-index-json-aggregation-performance-elastic-mysql-mongodb/). E se isso já não fosse o bastante, ainda existe a possibilidade de usar o [ElasticSearch](https://www.elastic.co/products/elasticsearch) através do [Laravel Scout](https://laravel.com/docs/5.4/scout) em cima dessas soluções. O resultado é que você terá facilidade + desempenho excelente sem sair do Eloquent e MySQL/MariaDB - não conheço o PostgreSQL mas é provável que existam soluções parecidas para otimizar o desempenho. 😄

**Comment by flipmorsch** [comment]
Obrigado a todos pela ajuda! 

**Paulo Freitas**, optei pela sua solução, achei que é a mais viável para o meu projeto atualmente.
