### ISSUE TITLE
Seed de Estados, Cidades, Bairros e Logradouros

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#106]
Boa tarde pessoal!

Alguém possui seed de Estados, Cidades, Bairros e Logradouros prontos para Laravel? São muitos registros e digitar um por um demandaria muito tempo.

Se alguém puder colaborar, ficarei grato.

**Comment by paulofreitas** [comment]
Estados e cidades em formato de *seeders* você irá encontrar aqui: [magnobiet/laravel-states-cities-brazil](https://github.com/magnobiet/laravel-states-cities-brazil/)

Quanto a bairros e logradouros, além de serem mais difíceis de serem obtidos, você não irá encontrar nada muito atualizado e tampouco prontos para serem usados como *seeders* no Laravel. Esse tipo de informação é de propriedade dos Correios e está em constante atualização, só tendo a [base de dados do próprio Correios](https://www.correios.com.br/para-voce/correios-de-a-a-z/dne) ou [bases paralelas como a do CEP Aberto](http://cepaberto.com/) para ter algo mínimamente confiável. 👍 

Eu tenho um projeto de dados abertos aqui no GitHub que oferece as base de dados do IBGE com estados, mesorregiões, microrregiões, municípios, distritos e subdistritos em vários formatos incluindo o SQL: [paulofreitas/places.br](https://github.com/paulofreitas/places.br)
No caso creio que não vai ajudar muito mas os dados são curados e fidedignos aos que o IBGE disponibiliza. Ao menos no que se propõe a oferecer, o projeto está sempre disponibilizando as bases mais recentes. 😀 

Uma alternativa que pode ser empregada em alguns tipos de projetos (e talvez o seu) é não ter base alguma e usar um serviço externo para fazer *lookup* de endereços tal como alguns sites de e-commerce já fazem através do campo CEP. O usuário digita o CEP e automaticamente todo o resto é preenchido, algo que pode ser feito até mesmo [através de uma simples requisição ao site dos Correios](https://pt.stackoverflow.com/questions/400/como-buscar-um-endereço-por-cep-nos-correios/838#838). Se preferir, existem inúmeras [APIs alternativas como a do próprio CEP Aberto](http://cepaberto.com/api_key). Há, ainda, projetos baseados na [base de dados do OpenStreetMap](http://wiki.openstreetmap.org/wiki/Planet.osm) como o [Algolia Places](https://community.algolia.com/places) que oferecem um serviço de *lookup* de endereços que independe do CEP. As opções são diversas. 😁

**Comment by maykonmendel** [comment]
@paulofreitas 

Sua resposta foi a mais completa que encontrei até hoje. Agradeço pela contribuição, porque não vai me ajudar somente no Laravel, mas em outras linguagens que eu utilizar.

**Comment by joaosalless** [comment]
Complementando, também tenho um pequeno projeto contendo os estados e municípios brasileiros em formato de seeders. Embora seja algo muito simples levando em conta as soluções já apresentadas aqui, utilizo-o há 2 anos em alguns projetos Laravel.

https://github.com/joaosalless/ibge_municipios

**Comment by Marasca** [comment]
Eu tenho usado esse aqui (api de consulta de cep/endereço): https://viacep.com.br/ e o pacote para o laravel: https://github.com/netdragoon/zipcode

**Comment by mahenrique94** [comment]
Fala ai @maykonmendel, tenho um web service para [consultas de cep](http://mhcws.matheuscastiglioni.com.br/), além disso se quiser tenho também um script para rodar no banco de dados com todas as cidades: [gist](https://gist.github.com/mahenrique94/7fb7bc3f89b306d7f3a7f359e99f4946#file-pais_estado_cidade-sql)

Abraçooos

**Comment by diegocedrim** [comment]
@mahenrique94 você tem uma base com todos os logradouros do brasil? Se sim, pode me passar?
