### ISSUE TITLE
Erro em produção "Whoops, looks like..."

### ISSUE THREAD

**Issue by victorhugorch** [laravelbrasil/forum#108]
## Problema Encontrado

Boa noite, pessoal. Peguei um projeto legado feito utilizando Laravel 5.1 para resolver, o projeto está um bagunça inexplicável. Um erro está ocorrendo ao acessar a área administrativa do site e outros diversos lugares.

`Whoops, looks like something went wrong.`

Nos logs eu encontro o erro.

```[2016-01-28 19:19:20] local.ERROR: exception 'ErrorException' with message 'Und$
Stack trace:
#0 C:\www\repository\softbrazil\passarinhomecontou\app\Http\Controllers\UserCon$
#1 [internal function]: App\Http\Controllers\UserController->index()
...
[2016-01-28 19:25:08] local.ERROR: exception 'Symfony\Component\Debug\Exception$
Stack trace:
#0 {main}
[2016-01-28 19:25:19] local.ERROR: exception 'BadMethodCallException' with mess$
```

Mas o que isso significa? Alguém já teve o erro?  
O erro não acontece localmente então minha suspeita é que seja no servidor.

---

## Abordagem
Alterar a Key de 256 para 128. Não funcionou.

---

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by mateusjatenee** [comment]
Vc nao tem mais do log? pela exception `BadMethodCallException` parece que vc está chamando um método que não existe (numa classe com `__call()`)

**Comment by victorhugorch** [comment]
Pessoal, acabei descobrindo o que causava o problema. Como é um projeto legado, haviam muitas má práticas aplicadas nele. Um delas é deixar uma pasta `old` dentro do projeto com um outro projeto laravel dentro.

O que acontecia provavelmente é que ao buscar o `index.pho` o Laravel encontrava mais de um arquivo dentro do projeto e se perdia ou bugava. Após eu remover isso e alguns controllers duplicados o problema se resolveu.
