### ISSUE TITLE
Tratamente de erro local caindo em Exceptions/Handler.php

### ISSUE THREAD

**Issue by maikealame** [laravelbrasil/forum#109]
## Problema
Boa noite. Não consigo tratar erros localmente em um Event sem cair no Handler da pasta Exceptions. Considerando que tudo funciona até esse ponto, Controller->Event->Listener, o código seria assim:
```
[Controller]
event(new UpdatedEvent($layer));

[Listener]
public function subscribe($events)
{
        $events->listen(
            'App\Events\UpdatedEvent',
            'App\Listeners\CalculateMetadataListener@updated'
        );
}
public function updated($event) {
    $this->calculate();
}
private function calculate(){
    $calc = [ 
        "(5 + 4) / 2" , 
        "( + ) / 2" 
    ];

    foreach($calc as $c){

    try{
        $res = eval("return ".$c.";");
        if($res  === false) {
            Throw new \Exception();
        }
    }catch(FatalThrowableError $e){
        echo $c;
        dd("error");
    }catch(\Exception $e){
        echo $c;
        dd("error");
    }

    }
}
```

No primeiro caso de $calc eu consigo o resultado com sucesso pois não há erro de síntaxe, retornando 4.5. Porém, no segundo caso há erro, caindo no arquivo Exceptions/Handler.php, porém gostaria de tratar localmente sem chegar lá, pois não quero retornar response nenhum apenas setar null case haja erro. Como sei que vai pro arquivo handler? apenas fazendo isso:

```
public function render($request, Exception $e)
    {
        dd($e);
        ...
```

O erro que gera na tela é o seguinte:
![image](https://user-images.githubusercontent.com/15782847/27561945-a05a8a5a-5aa0-11e7-91ad-56e5a740846f.png)

---

## Abordagem
Usei ob_start(); entre outras tentativas e nada.

---

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by aviniciustech** [comment]
[Essa exceção que você esta recebendo](http://php.net/manual/pt_BR/class.parseerror.php) não esta na 'família' de \Exception, por isso não consegue capturar. Ela é um erro interno do PHP. 

Para você capturar teria que fazer isso:

```
 try {
    throw new \ParseError("Nunca vi isso em nenhuma aplicação");
 } catch (\Exception $exception) {
    dd(" Aqui não cai por que não estende de exception: ",$exception->getMessage());
 } catch (\Error $exception) {
    dd("Cai aqui por que é um error: ",$exception->getMessage());
 }
```

**Comment by maikealame** [comment]
Resolvido com ajuda do @avinisilva 
```
    try{
        $res = eval("return ".$c.";");
    }catch(\Error $e)
        dd($e);
    }catch(\Exception $e){
        dd($e);
    }
```
