### ISSUE TITLE
PagSeguro

### ISSUE THREAD

**Issue by dieggop** [laravelbrasil/forum#11]
Pessoal, venho testando alguns pacotes de Pagseguro, porém não tive êxito, não precisaria de muita coisa, nem carrinho de compras. Apenas desejo fazer com que o usuário consiga fazer uma compra de um "curso". Apenas!

Teriam algum vídeo mostrando a implementação? 

## Abordagem
Tentei já trabalhar com o pacote do wesley e o do artistas...

**Comment by andreportaro** [comment]
Diego, por favor poste qual a sua abordagem.

Conseguiu baixar os pacotes pelo composer?
Instalou corretamente o service provider?

Por favor poste mostras do código, ou seja, como você tentou implementar.



Em 9 de fev de 2017 19:22, "Dieggo Carrilho" <notifications@github.com>
escreveu:

**Comment by dieggop** [comment]
## ABORDAGEM 

Peço desculpas, porém eu exclui os códigos. Mas sim, consegui instalar todos eles pelo composer. 
os que fiz a instalação foram estes dois:
https://github.com/wesleywillians/laravel-pagseguro

https://packagist.org/packages/artistas/laravel-pagseguro

O do wesley, fiz similarmente ao código exemplo. Mas o retorno ficava uma página em branco!

 O do artistas/pagseguro também segui o tutorial que ele dispõe. Porém este dava um erro como se fosse sem permissão!!!

**Comment by andreportaro** [comment]
Então vamos lá Diego, baixa ambos de novo e implementa pra gente poder te
auxiliar :)

Em 9 de fev de 2017 19:27, "Dieggo Carrilho" <notifications@github.com>
escreveu:

**Comment by dieggop** [comment]
Ta certo, estou testando um 3º agora, michaeldouglas/laravel-pagseguro, se houver sucesso postarei aqui como fiz e se der errado, posto também hehehe! 

Obrigado a atenção!

**Comment by fabiosperotto** [comment]
Oi gente,

Vou repassar minha breve experiência do que eu consegui e não consegui utilizar. Não utilizei todos os pacotes descritos acima. Num dos projetos usei o referido por último pelo @dieggop o michaeldouglas/laravel-pagseguro [1]

Usei Laravel 5.2 em 2 projetos distintos (um com carrinho de compras efetivo, outro sem). Um deles com PagSeguro lightbox, outro sem:

**PagSeguro sem lightbox**: neste aqui usei o michaeldouglas/laravel-pagseguro, entretanto somente pela metade, simplesmente o retorno das notificações não foi possível utilizar. Toda a parte de compra é realizada com sucesso. As notificações pego manualmente com Guzzle [2]

**PagSeguro com lightbox**: com lightbox não utilizo pacotes, fora implementado diretamente conforme consta na documentação [3]. As requisições/retornos necessários também foram realizados com Guzzle [2]. Este projeto está em testes ainda mas por enquanto achei tranquilo desta forma.

Isso tudo devido a prazos, mas confesso que não explorei outros pacotes. No meu primeiro caso não foi a abordagem correta, recomendam algo?


Refs:
[1] https://github.com/michaeldouglas/laravel-pagseguro
[2] http://docs.guzzlephp.org
[3] https://dev.pagseguro.uol.com.br/documentacao/pagamentos/pagamento-lightbox/api-de-pagamentos-lightbox

**Comment by ravanscafi** [comment]
cc @marabesi

**Comment by hernandev** [comment]
@dieggop alguma novidade desde que reabriu o tópico, por favor compartilhe suas conclusões para que possamos encerrar a discussão ou retomá-la
