### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by r4free** [laravelbrasil/forum#111]
Alguem poderia me ajudar, **estou tentando enviar email pelo mailgun estou obtendo esse erro, estou usando o wamp**
ja setei o tudo como manda a documentaçao, o arquivo config/service.php & o config/mail.php
obs. pelo smtp usando gmail funciona normal
![capturar](https://user-images.githubusercontent.com/3081322/27608231-04788f34-5b5d-11e7-96a6-b5ef9cf0d0cd.PNG)

**Comment by cagartner** [comment]
Aparentemente é um erro com o Windows, tenta fazer esses passos: https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017

**Comment by paulofreitas** [comment]
Na verdade o problema ocorre em outras plataformas também e se dá por conta da falta do arquivo de autoridades certificadoras de certificados SSL. Para resolver basta salvar o arquivo http://curl.haxx.se/ca/cacert.pem em algum lugar e referenciar ele no `curl.cainfo` e `openssl.cafile` do *php.ini* em uso.

No Windows, se você salvar esse arquivo em `%WINDIR%\curl-ca-bundle.crt` você não precisa estar alterando o *php.ini*. Para tanto, basta rodar isso aqui no terminal:

    php -r "copy('http://curl.haxx.se/ca/cacert.pem', '%WINDIR%\curl-ca-bundle.crt');"

No Ubuntu/Debian/Red Hat/CentOS/Fedora você pode estar instalando o pacote `ca-certificates` através do gerenciador de pacotes do sistema: `sudo apt-get install ca-certificates` para o Ubuntu/Debian e `sudo yum install ca-certificates` para os demais.

No macOS, se o PHP foi instalado através do Homebrew (`brew install php71`) você não irá ter esse problema, caso contrário basta baixar o arquivo em `/usr/local/etc/openssl/cert.pem`:

    php -r "copy('http://curl.haxx.se/ca/cacert.pem', '/usr/local/etc/openssl/cert.pem');"

**Comment by elvispdosreis** [comment]
eu tenho esse problema no cpanel ele nao funcionaja fiz isso procedimento mais nao funcionou

**Comment by webesistemas** [comment]
> Na verdade o problema ocorre em outras plataformas também e se dá por conta da falta do arquivo de autoridades certificadoras de certificados SSL. Para resolver basta salvar o arquivo http://curl.haxx.se/ca/cacert.pem em algum lugar e referenciar ele no `curl.cainfo` e `openssl.cafile` do _php.ini_ em uso.
> 
> No Windows, se você salvar esse arquivo em `%WINDIR%\curl-ca-bundle.crt` você não precisa estar alterando o _php.ini_. Para tanto, basta rodar isso aqui no terminal:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '%WINDIR%\curl-ca-bundle.crt');"
> ```
> 
> No Ubuntu/Debian/Red Hat/CentOS/Fedora você pode estar instalando o pacote `ca-certificates` através do gerenciador de pacotes do sistema: `sudo apt-get install ca-certificates` para o Ubuntu/Debian e `sudo yum install ca-certificates` para os demais.
> 
> No macOS, se o PHP foi instalado através do Homebrew (`brew install php71`) você não irá ter esse problema, caso contrário basta baixar o arquivo em `/usr/local/etc/openssl/cert.pem`:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '/usr/local/etc/openssl/cert.pem');"
> ```

precisei disso hoje e funcionou, obrigado

**Comment by josemoraes** [comment]
> Na verdade o problema ocorre em outras plataformas também e se dá por conta da falta do arquivo de autoridades certificadoras de certificados SSL. Para resolver basta salvar o arquivo http://curl.haxx.se/ca/cacert.pem em algum lugar e referenciar ele no `curl.cainfo` e `openssl.cafile` do _php.ini_ em uso.
> 
> No Windows, se você salvar esse arquivo em `%WINDIR%\curl-ca-bundle.crt` você não precisa estar alterando o _php.ini_. Para tanto, basta rodar isso aqui no terminal:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '%WINDIR%\curl-ca-bundle.crt');"
> ```
> 
> No Ubuntu/Debian/Red Hat/CentOS/Fedora você pode estar instalando o pacote `ca-certificates` através do gerenciador de pacotes do sistema: `sudo apt-get install ca-certificates` para o Ubuntu/Debian e `sudo yum install ca-certificates` para os demais.
> 
> No macOS, se o PHP foi instalado através do Homebrew (`brew install php71`) você não irá ter esse problema, caso contrário basta baixar o arquivo em `/usr/local/etc/openssl/cert.pem`:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '/usr/local/etc/openssl/cert.pem');"
> ```

Thanks, @paulofreitas . Your guidance really helped me ;)

**Comment by gbarcella** [comment]
> Na verdade o problema ocorre em outras plataformas também e se dá por conta da falta do arquivo de autoridades certificadoras de certificados SSL. Para resolver basta salvar o arquivo http://curl.haxx.se/ca/cacert.pem em algum lugar e referenciar ele no `curl.cainfo` e `openssl.cafile` do _php.ini_ em uso.
> 
> No Windows, se você salvar esse arquivo em `%WINDIR%\curl-ca-bundle.crt` você não precisa estar alterando o _php.ini_. Para tanto, basta rodar isso aqui no terminal:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '%WINDIR%\curl-ca-bundle.crt');"
> ```
> 
> No Ubuntu/Debian/Red Hat/CentOS/Fedora você pode estar instalando o pacote `ca-certificates` através do gerenciador de pacotes do sistema: `sudo apt-get install ca-certificates` para o Ubuntu/Debian e `sudo yum install ca-certificates` para os demais.
> 
> No macOS, se o PHP foi instalado através do Homebrew (`brew install php71`) você não irá ter esse problema, caso contrário basta baixar o arquivo em `/usr/local/etc/openssl/cert.pem`:
> 
> ```
> php -r "copy('http://curl.haxx.se/ca/cacert.pem', '/usr/local/etc/openssl/cert.pem');"
> ```

Muito obrigado, me salvou!

**Comment by Werverton** [comment]
NO meu o problema era a linha 
SSLCACertificateFile /path/to/dominio-ca.bundle
que estava faltando, quando coloquei resolveu.
No arquivo do host virtual.

**Comment by gilmarodp** [comment]
Cara, tive dor de cabeça com exatamente esse problema que você está passando, resolvi o problema com ajuda de um amigo com algo muito simples, basta você desativar a verificação de SSL da sua requisição. Se isso é seguro ou não, já é outra discussão, mas acho válido para testar e não ficar preso a esse erro.

Se você estiver utilizando a classe Http do laravel você pode fazer a requisição e chamar o seguinte método:
`Http::withoutVerifying()->get('https://google.com')`
