### ISSUE TITLE
Sistema de login

### ISSUE THREAD

**Issue by RafaelGSS** [laravelbrasil/forum#112]
Sei que o Laravel nos permite um sistema completo de Login, Register e cia. Porém como ando estudando a pouco tempo Laravel, e preciso fazer um painel simples de login (Apenas para login, sem register, remember, ou algo do genero) Eu gostaria de fazer o meu. 
Andei pesquisando, e vi que qualquer model que _extends_ de "Illuminate\Foundation\Auth\User" Já provém de diversos métodos para que possa efetuar a autenticação, correto ?! 
Para que eu entenda isso mais afundo, como fazer a autenticação com o banco de dados, é totalmente inviavel ? gostaria de fazer algo assim, mas vendo como é feito o sistema de autenticação do Laravel, me perco por inteiro, já pesquisei bastante, e só vejo por pessoas que usam o recurso do próprio Laravel(Não que nao seja bom, meu intuito é apenas entender e aprender) e pessoas que vão direto para o ACL.

**Comment by mahenrique94** [comment]
@RafaelGSS recentemente tive a mesma necessidade, tive que fazer um sistema de login mas não queria usar o do Laravel e sim ter o meu próprio.

Basicamente o que você vai precisar fazer, é pegar o usuário e senha digitados no login, validar a entrada dos dados, consultar no banco de dados por esse usuário, caso o mesmo seja encontrado terá que setar o usuário na sessão e redirecionar para um dashboard.

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Request;
use App\AdmUsuario;

class LoginController extends Controller {

    public function formulario() {
        return view("auth.formulario");
    }

    public function login() {
        $credenciais = Request::only("usuario", "senha");
        $usuario = AdmUsuario::where("usuario", "=", $credenciais["usuario"])
                                ->where("senha", "=", $credenciais["senha"])
                                ->where("inativo", "=", false)->take(1)->first();
        if ($usuario != null) {
            Auth::login($usuario);
            return redirect()->action("DashboardController@dashboard");
        } else {
            return redirect()->action("Auth\LoginController@formulario");
        }
    }

}
```

Abraçooos

**Comment by RafaelGSS** [comment]
Ótimo mahenrique94! Isso é relativamente seguro ? você usou algum middleware ? ou criou o seu também ?

**Comment by mahenrique94** [comment]
ainda não terminei @RafaelGSS mas vou criar o meu próprio, em questão de segurança, basta apenas validar o que foi digitado nos inputs, no código acima ainda não criei a validação também, talvez um:

```
mysqli_real_escape_string($credenciais["usuario"], $credenciais["senha"])
```

Resolveria a questão de SQL Injection.
