### ISSUE TITLE
Autenticacao sem Model User

### ISSUE THREAD

**Issue by RafaelGSS** [laravelbrasil/forum#113]
Olá, estou fazendo um sisteminha de login básico
Sei que o laravel já disponibiliza 
Porém gostaria de fazer o meu, 
Quando faço o login para me autenticar com o `Auth::login($user);` recebo um erro _Type error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\Usuario given_ 
Andei pesquisando e vi que precisaria implementar a classe _Illuminate\Foundation\Auth\User_
Porém quando eu implemento, ele busca no banco de dados "users" e minha model é "Usuario" , deveria por buscar por "usuarios", aonde eu edito isso, já criei uma pasta no Illuminate\Foundation\Auth\Usuarios.php, e nada dá certo!

**Comment by cagartner** [comment]
Bom dia @RafaelGSS 

Basta informar no model o nome correto do banco, por padrão o Laravel "entende" um model User se refere a uma tabela "users" ou seja sempre o model será singular e a tabela será no plural, no seu caso você precisa sobrescrever isso seguindo essa forma:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'Usuario'; // Define o nome da tabela
}
```

Abraços!

**Comment by RafaelGSS** [comment]
Mas se no caso eu quisesse criar minha própria model ?

**Comment by cagartner** [comment]
Nesse caso você deve criar um custom guard: https://laravel.com/docs/5.4/authentication#adding-custom-guards conforme a documentação desse link.

Tem outro tutorial de como deve ser feito aqui: https://laracasts.com/discuss/channels/laravel/replacing-the-laravel-authentication-with-a-custom-authentication

**Comment by RafaelGSS** [comment]
Obrigado!
