### ISSUE TITLE
Breakpoints Bootstrap

### ISSUE THREAD

**Issue by rogerio-pereira** [laravelbrasil/forum#118]
olá pessoal, boa noite. estou com um problema não necessariamente de laravel, não tenho conhecimento em sass ou less, conheco css... meu problema é o seguinte, meu site está usando o bootstrap padrão, preciso alternar o tamanho dos breakpoints do boostrap usando essas configurações

```
$grid-breakpoints: (
  xs: 0,
  sm: 568px,
  md: 736px,
  lg: 960px,
  xl: 1200px
) !default;

```
onde eu devo colocar isso para que meus breakpoints funcionem corretamente

**Comment by marabesi** [comment]
Como essa dúvida não é relacionada com o Laravel irei fechar a issue, tudo bem?
