### ISSUE TITLE
Como enviar dados de uma tabela na view para uma controller?

### ISSUE THREAD

**Issue by jackrsantana** [laravelbrasil/forum#119]
Como devo proceder quando tenho um CRUD com relacionamento muitos para um, ou seja, onde é possível incluir vários registros para o registro principal conforme a imagem abaixo (muitos contatos para uma pessoa):

![duvida](https://user-images.githubusercontent.com/16987558/28384878-93408fbe-6c9c-11e7-8f7e-1070ddc0fcb1.png)

Fique na dúvida se o mais correto seria tentar utilizar ajax de alguma forma, mas isso iria me complicar nas inclusões, onde meu registro principal (pessoa) ainda não foi incluído e consequentemente, eu não conseguiria fazer a ligação das chaves nos outros registros (contatos). Será que seria uma boa tentar utilizar o DataTable nessa situação?

Desde já, muito obrigado!

**Comment by meirinaldojunior** [comment]
Brother, não sei se entendi bem tua pergunta, mas, minha sugestão é fazer um append dos dados na table, e depois só salvar o form preenchido, isso é puro front-end.

**Comment by jackrsantana** [comment]
@meirinaldojunior, a parte do append na table eu tô fazendo, minha dúvida é como enviar os dados adicionados na tabela para controller.

**Comment by meirinaldojunior** [comment]
@jackrsantana  Cria um array no name de cada item (telefone[], contato[], observacao[]), depois pega os dados por foreach lá no controller.

**Comment by jackrsantana** [comment]
😱😱😱😱
Não sabia que dava pra criar array de input. Só isso e eu já vou conseguir acessar na controller todos os dados adicionados?
Vou tentar aqui, muuuuuuuuito obrigado!

**Comment by meirinaldojunior** [comment]
Consegue sim...
@jackrsantana Que bom ter te ajudado brother! 
Abraço!
