### ISSUE TITLE
Alteração automática de dados no DB

### ISSUE THREAD

**Issue by guaracyalima** [laravelbrasil/forum#12]
Pessoal, estou em duvida(?) de como fazer:
Tenho um cadastro de "carnês" de pagamento com suas parcelas(com vencimentos mensais, as quais possuem dentre outros dados o valor, a data de vencimento e o status do pagamento -aguardando, pago, protestado e cancelado) e preciso que elas mostrem (na view - ou no banco?) se a parcela esta atrasada ou não (baseando-se na data de hoje (now)).

---

## Abordagem
Pensei em duas soluções (bem verbosas):
Fazer um if (na view mesmo) e fazer a comparação, mas esse código teria que ser repetidos em todos os lugares em que eu precisasse fazer essa verificação;

A segunda forma que pensei foi fazer essa mesma verificação só que no controller, onde ele alteraria diretamente no db o status de pagamento. 

---

## Help
Se alguém puder me indicar qual das duas ou uma forma melhorada de como fazer esse processo, ficarei muito grato.

**Comment by lucasdealmeida** [comment]
Isso vai depender muito do objetivo, você pode tratar isso apenas na visualização como você mesmo citou, mas só cuide para centralizar essa regra, com Presenter acredito que ficaria legal, ou você pode fazer essa verificação em background, uma vez ao dia, todos os dias, e caso esteja atrasado você altera o status para atrasado, assim você não teria nenhuma regra na view, apenas exibição do status, eu acredito que com a rotina fique melhor, porém dependeria de você ter uma coluna na tabela para determinar isso, pode usar o status (eu acho melhor) ou uma segunda coluna só para isso. Como eu disse, vai depender do seu objetivo.

**Comment by marabesi** [comment]
O que você pode fazer nessa situação é utilizar um helper na view e deixar a regra em uma classe para ser testada.

Eu adotaria a seguinte solução:

1) criar um helper pagamento que tenha a lógica necessária, seja ela exibir um texto se for vencido ou calcular alguma taxa de juros.
2) Adicionaria os casos de testes necessários

**Comment by guaracyalima** [comment]
Obrigado a todos pela ajuda.
Como ainda não dominei a criação de helpers, adotei mesmo a primeira abordagem, que embora tenha ficado bastante verboso funcionou corretamente.
