### ISSUE TITLE
Formatar resposta JSON

### ISSUE THREAD

**Issue by KleversonNascimento** [laravelbrasil/forum#124]
Tenho uma busca que retorna um JSON de usuários, que é feita desta forma:

` $usuarios=$this->usuario->all();
return  response()->json(['usuarios'=>$usuarios]);`

Sendo que a model de usuário que utilizo contém apenas isso:
`protected $fillable=['nome','email','celular','cpf'];`

## Problema Encontrado
Porém gostaria de formatar essa resposta para que ao invés do nome João ele mostrasse J**o por exemplo, como posso formatar esses dados antes de exibi-los?

## Solução
Conforme indicado pelo davidrtpereira bastou inserir a função getNameAttribute na model, formatar como eu queria e retornar o valor.

**Comment by davidrtpereira** [comment]
@KleversonNascimento 

Você pode criar um Mutator no model destes dados.
https://laravel.com/docs/5.4/eloquent-mutators

Quando quiser buscar o dado sem alteração, utilize o método $model->getOriginal('attribute');

**Comment by KleversonNascimento** [comment]
Muito obrigado, consegui fazer a alteração.
