### ISSUE TITLE
vagrant com Laravel

### ISSUE THREAD

**Issue by mauroslucios** [laravelbrasil/forum#125]
Máquina virtual vagrant não passa do default:SSH username:private key

## Problema Encontrado
Boa tarde a todos!
Gostaria de ajuda para resolver o seguinte problema:
Quando dou o comando vagrant up no terminal chegando na linha:
default:SSH username:private key começa com uma mensagem:
default: warning: Connection reset. Retying até chegar a mensagem:
default: warning: Authentication Failure. Retying e por fim reporta a mensagem:
Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with guest machine wthin the configures("config.vm.boot_timeout" value)time period...
E aborta o processo
---

## Abordagem
Já configurei o vagrntfile com config.vm.boot_timeout = 300, já atualizei  vrtualbox, atualizei vagrant, usei os comandos:
vagrant destroy e reiniciei tudo de novo e outros meios, mas até agora nada de solução!

Alguém pode me ajudar?

**Comment by marabesi** [comment]
Algumas coisas que você pode tentar:

1) remover tudo o que vc tem do vagrant (inclusive a imagem)
2) gerar novamente a key do ssh via ssh-keygen

**Comment by mauroslucios** [comment]
Obrigado marabesi, mas já consegui resolver!
Comecei com Laravel e Vagrant agora e estou estudando a fundo.
Abçs e mais uma vez obrigado!
