### ISSUE TITLE
Usando Condições em Consultas

### ISSUE THREAD

**Issue by crazyshock** [laravelbrasil/forum#128]
E ai galera!

Surgiu uma dúvida aqui na seguinte situação... Antes de usar o Laravel eu realizava um Select no banco e colocava as condições deste SQL da seguinte maneira:

```
$query = "select * from produtos where 1=1 ";
$query .= !empty($cod_produto) ? " and cod_produto = ".$cod_produto : "";
//execute query;
```
Agora usando o Laravel fica da seguinte maneira:
```
Produtos::where('cod_produto', = , $cod_produto)->get();
```
O meu problema é, a condição Where() só deverá ser chamada caso a variável $cod_produto for diferente de vazia. 

Como que posso fazer isso? Qual o melhor caminho a seguir?

Obrigado!!!!

**Comment by cagartner** [comment]
Bom dia.

Se não tiver $cod_produto a consulta vai retornar todos os produtos? Ou não vai retornar nada?

É que tem várias formas de fazer o que você quer fazer...

A forma "Eloquentzada" de fazer sua query é: 

```php
$query = Produtos::where(1, '=', 1);
if (!empty($cod_produto)) {
    $query->where('cod_produto', '=', $cod_produto);
}
$produtos = $query->get();
```
Essa consulta de cima não aconselho porque se o banco tiver milhares de registro e não for passado o $cod_produto vai retornar todos os produtos e vai deixar sua aplicaçaõ muito lenta.

Mas tem outras formas melhores que posso mostrar dependendo do que vai acontecer se tiver ou não o código.

**Comment by davidrtpereira** [comment]
@crazyshock 
Eu tenho uma sugestão, que deixaria o teu código mais limpo, que seria a utilização de scopes.

https://laravel.com/docs/5.4/eloquent#local-scopes

Eu sugiro que tu faça da seguinte maneira.

No model Produtos, crie uma função publica, com um nome sugestivo para esta situação

`class Produtos extends Model {
     // Seu codigo existente

    public function scopeCodProduto($query, $codProduto){
        if(!empty($codeProduto)){
            $query->where('cod_produto', $codProduto);
        }
    }
}`

No local onde você está fazendo está consulta, chame-a desta maneira:
`Produtos::codProduto($codProduto)->get();`

**Comment by crazyshock** [comment]
@cagartner Isso mesmo, se o parametro não existir ele retorna tudo, porém o código de produto foi apenas um exemplo, na minha situação ele tem várias "parametros" que vai filtrando.
Vou testar o que você me falou, acredito que isso já resolve meu problema.

Porém fiquei com uma pequena dúvida quando você falou "Mas tem outras formas melhores que posso mostrar dependendo do que vai acontecer se tiver ou não o código.", além desse exemplo e o do exemplo que o @davidrtpereira mostrou, existe ainda o melhor caminho para tornar mais rápido?

Mas de ante-mão já agradeço a ajuda de vocês!!!!

**Comment by keldnner** [comment]
@crazyshock eu gosto da abordagem feita pelo colega @vinicius73.
Segue link para um exemplo completo https://gist.github.com/vinicius73/175b0099ee1169876cfd.

**Comment by crazyshock** [comment]
@keldnner não estou conseguindo abrir o link... está correto mesmo?
Obrigado!

**Comment by paulofreitas** [comment]
O Query Builder oferece o método `when()` para lidar com essas situações:

```php
$produtos = Produtos::when($request->cod_produto, function ($query) use ($request) {
    $query->where('cod_produto', $request->cod_produto);
})
    ->get();
```
Porém se você planeja usar isso mais de uma vez seu código irá ficar um monstrinho difícil de dar manutenção. Você irá querer desacoplar isso. Um modo interessante de se fazer isso é usar uma combinação dos *patterns* *criteria* e *specification*.

Tem um excelente tutorial do Amo Chohan sobre como desacoplar filtros em consultas complexas com o Eloquent que aborda isso na prática: https://m.dotdev.co/writing-advanced-eloquent-search-query-filters-de8b6c2598db

Esse conceito de desacoplar os filtros em classes é o *criteria pattern* em si: https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/#Creating_A_New_Criteria
Já o conceito de aplicar um filtro se uma determinada condição for atendida é um conceito do *specification pattern*: http://marcaube.ca/2015/05/specifications

O código final do artigo do Amo Chocan não ficou muito intuitivo nisso (digamos que ficou mágico demais) mas você pode refatorá-lo facilmente para algo mais literal. As idéias de simplificação e reúso de código na conclusão do artigo é um primeiro passo para melhorar isso. :smiley:

Abraços! o/

**Comment by crazyshock** [comment]
Sensacional!! 
Agradeço todas as dicas!!!!

**Comment by omarkdev** [comment]
Acredito que a dúvida já foi resolvida, por enquanto estou fechando essa issue.
