### ISSUE TITLE
Laravel 5.4 Observers - Merge values into request

### ISSUE THREAD

**Issue by pxpm** [laravelbrasil/forum#13]
Descrição Geral do Problema

Ora bem, boas a todos novamente.
Estou com o seguinte problema que passo a descrever:

Tenho o `RegisterController.php`
```php
    protected function create(array $data)
    {
        $user_model_fqn = config('backpack.base.user_model_fqn');
        $user = new $user_model_fqn();
        $data['company_id'] = '';
        if (!isset($data['default_lang'])) {
            $data['default_lang'] = '';
        }
        if (!isset($data['company_id'])) {
            $data['company_id'] = '';
        }
        return $user->create([
            'name'     => $data['name'],
            'email'    => $data['email'],
            'password' => bcrypt($data['password']),
            'default_lang' => $data['default_lang'],
            'company_id' => $data['company_id'],
        ]);
    }
```

Os `isset`s eu utilizo, porque não passo os valores `company_id` e `default_lang` pelo form. Eles são carregados correctamente noutra parte da minha aplicação e o objectivo é inserir esses valores "on-the-fly".

A seguir tenho um `UserObserver`, está registado no service provider e os eventos disparam.

Qual é a minha dúvida e o meu problema?

No observer eu tenho o seguinte código:

```php
    public function creating(Eloquent $model)
    {

        if (\Request::get('default_lang') == '') {
            //dd($this->request->get('DomainDefaultLang'));
            //dd(\Request::all());
            \Request::merge(['default_lang' => \Request::get('DomainDefaultLang')]);
        }
        if (\Request::get('company_id') == '') {
            \Request::merge(['company_id' => \Request::get('CompanyId')]);
        }
        dd(\Request::all());
    }
```

O dd() funciona e o meu request retorna o seguinte:

```
array:7 [▼
  "_token" => "aklsdjfdaSDFae234rqwEFDasdfasdfq34faeFA"
  "name" => "Maria Manuel Sim Martins"
  "email" => "xxxxx@gmail.com"
  "password" => "123456"
  "password_confirmation" => "123456"
  "default_lang" => "ss"
  "company_id" => 1
]
```

O problema reside, que se eu remover o dd (uma vez que já vi que os parâmetros estão no request) ele continua pela app fora, mas os valores do `company_id` e do `default_lang` estão vazios, e não com os que eu meti no request.

Não é o observer o sitio correcto para este tipo de manipulação ?

Agradecido desde já,

pxpm

**Comment by pxpm** [comment]
@rscafi 5* pelo trabalho. E desculpas da minha parte por não o ter tido. Vou ter mais atenção numa próxima vez.
Muito obrigado.

**Comment by ravanscafi** [comment]
fica tranquilo @pxpm, estamos aí pra isso 😉

**Comment by cagartner** [comment]
@pxpm Nesse caso você quer adicionar no Request os valores `default_lang` e `company_id` certo?

Isso será salvo no model que você está criando certo?

Nesse caso no observer se você dar um dd() no parâmetro `$model` verá que é o model já com os dados, ai nesse caso você adiciona diretamente no model que ele irá criar com os dados ex:

```php
    public function creating(Eloquent $model)
    {

        if (\Request::get('default_lang') == '') {
            //dd($this->request->get('DomainDefaultLang'));
            //dd(\Request::all());
            // \Request::merge(['default_lang' => \Request::get('DomainDefaultLang')]);
            $model->default_lang = \Request::get('DomainDefaultLang');
        }
        if (\Request::get('company_id') == '') {
            // \Request::merge(['company_id' => \Request::get('CompanyId')]);
            $model->company_id = \Request::get('CompanyId');
        }
        dd($model);
    }
```

**Comment by pxpm** [comment]
@cagartner Em cheio \o/

Mais uma vez obrigado, era isso mesmo.
Ao fazer as alterações que disseste funcionou logo. 
Então uso o Request merge ou add apenas quando quero adicionar parâmetros antes de o model bootar, se for depois devo fazer sempre como fiz aqui, apanhar uma instância e modificar directamente na instância do model, é isso ou estou a fazer alguma confusão?

Melhores cumprimentos

**Comment by cagartner** [comment]
Isso mesmo.

Irei finalizar esse issue. Abraços!
