### ISSUE TITLE
Erro ao instalar laravel homestead v3.0.0 (OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104)

### ISSUE THREAD

**Issue by ghost** [laravelbrasil/forum#130]
Boa noite!
Alguém já teve o problema abaixo quando tentava instalar **laravel homestead v3.0.0**, e conseguiu solucionar?

## Ambiente:
Ubuntu 16.04.3 LTS
Vagrant 1.9.8
VirtualBox 5.1.26 r117224 (Qt5.5.1)

## Problema Encontrado
```
$ vagrant box add laravel/homestead
==> box: Loading metadata for box 'laravel/homestead'
    box: URL: https://vagrantcloud.com/laravel/homestead
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) parallels
2) virtualbox
3) vmware_desktop

Enter your choice: 2
==> box: Adding box 'laravel/homestead' (v3.0.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/3.0.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```
---

## Abordagem
Já tentei uma série de soluções googlando na web:
[Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/401)
[Homestead won’t update – Vagrant: An error occurred while downloading the remote file](http://danielkoop.me/2016/02/17/homestead-wont-update-vagrant-an-error-occurred-while-downloading-the-remote-file/)

---

**Comment by marabesi** [comment]
Você está fazendo uma instalação do zero? Tive esse problema e resolvi removendo todos os arquivos inclusive e box e instalando tudo de novo.

**Comment by ghost** [comment]
@marabesi estou fazendo tudo do zero, inclusive já segui sua orientação. Mas ainda não obtive êxito.

**Comment by dinnouti** [comment]
Voce esta tentando instalar localmente em sua maquina? Enquanto isso experimenta

`vagrant box add laravel/homestead -c`
ou
`vagrant box add --insecure -c laravel/homestead`

**Comment by ghost** [comment]
@dinnouti Já havia tentado essa solução conforme abordado abaixo.
[Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/401)

**Comment by hirenkeraliya** [comment]
@aljesti  Yes, I have the Same problem with install laravel homestead I have to make many different ways but still see this error. and try to make it to other computer but not Installed.

**Comment by ghost** [comment]
Olá! 
Demorei porque estava trabalhando com o XAMPP. 
Voltando ao problema. Fiz um upgrade no vagrant da versão 1.9.8 para **2.0.0.0**, e virtualbox da versão 5.1.26 r117224 (Qt5.5.1) para **5.1.30** r118389 (Qt5.5.1). 
Em seguida instalei o Homestead:
```
cd ~
git clone https://github.com/laravel/homestead.git Homestead
cd Homestead
git checkout v6.5.0
bash init.sh
vagrant up
```
E pronto! Problema resolvido.
...
**==> homestead-7: Successfully added box 'laravel/homestead' (v4.0.0) for 'virtualbox'!**
