### ISSUE TITLE
Autenticação básica não funcional em produção.

### ISSUE THREAD

**Issue by deciocrf** [laravelbrasil/forum#131]
Descrição Geral do Problema

## Problema Encontrado
Bom dia, sou iniciante no Laravel, e desenvolvi uma aplicação utilizando ambiente homestead e tudo ok até ai, o problema veio agora que subi para um servidor Ubuntu 16.04 , onde após realizar as configurações no apache2, /var/www, migrations e seeds, o mesmo código não realiza login, fica num loop de redirecionamento para /login ( estou usando autenticação basica do laravel ).
OBS: Existe uma parte que não exige autenticação, e o form envia os dados e grava no banco como deveria, no arquivo de rotas /client/create.

**Meu arquivo de rotas** :

````php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth'],], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/cabin/show/{id}', 'CabinController@show');

    Route::get('/cabin/attach/', 'CabinController@attachClient');

    Route::get('/cabin/detach/{id}', 'CabinController@detachClient');

    Route::get('/cabin', 'CabinController@index')->name('web.cabins.index');

    Route::get('/cabin/sale', 'CabinController@sale')->name('web.cabins.sale');

    Route::get('/client', 'ClientController@index')->name('web.clients.index');    

    Route::get('/client/edit/{id}', 'ClientController@edit')->name('web.clients.edit');

    Route::post('/client/{id}', 'ClientController@update')->name('web.clients.update');

    Route::get('/client/delete/{id}', 'ClientController@destroy')->name('web.clients.destroy');

});

// Route::post('/client/createLP', 'ClientController@storeFromLP')->name('web.clients.storeFromLP');

Route::get('/client/create', 'ClientController@create')->name('web.clients.create');

Route::post('/client', 'ClientController@store')->name('web.clients.store');`
````

**Auth/LoginController.php** :

````php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
}
````
---

## Abordagem
**Permissãode diretorios** : 

> find {laravel-folder}/ -type d -exec chmod 755 {} ;
>find {laravel-folder}/ -type d -exec chmod ug+s {} ;
>find {laravel-folder}/ -type f -exec chmod 644 {} ;
>chown -R {username}:www-data {laravel-folder}
>chmod -R 777 {laravel-folder}/storage
>chmod -R 777 {laravel-folder}/bootstrap/cache/

**permissões do apache www-data**: 
![image](https://user-images.githubusercontent.com/5418863/29750257-ba966a2c-8b12-11e7-8050-9ecb0bfc07b6.png)

**Tentei Retirar as rotas de dentro do grupo auth**.
**Tentei achar erros no /storage/logs/laravel.log -> mas não parece nada de erro, cria sessão, escreve, e salva**
**No navegador verifiquei que esta sendo criada o arquivo de sessão e se removido ocorre erro de TokenMismatch**
**Adicionar `protected $redirectPath = '/home';` no LoginController.php**

---

## Atualização 1

---

**Comment by ravanscafi** [comment]
Provavelmente o seu Apache tá removendo o header de `Authorization` do request.
Talvez colocando isso no seu `public/.htaccess` resolva.

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
```

**Comment by deciocrf** [comment]
Bom acabou que foi uma falha de iniciante minha , porque estava utilizando o login ao invés de email, tinha utilizado, a função errada no LoginController , pois estava tentando utilizar a função utilizando o nome de retorno e nao username, então ao corrigir para: 

````php
public function username()
{
  return "login";
}
````

resolveu o problema, obrigado a todos que ajudaram.
