### ISSUE TITLE
Erro laravel

### ISSUE THREAD

**Issue by adailsonm** [laravelbrasil/forum#133]
Descrição Geral do Problema

## Problema Encontrado
Detalhar problema - Utilize Markdown ou Gist para códigos
Não consigo subir meu formulario tento alterar um dado na tabela ta tudo certinho, é ele não envia. nenhum dos campos 
`DB::table('usuarios')->update(array('nickname' => $request->Nickname)) ele num vai acho que tem algo relacionado com token.
---

## Abordagem
Você já tentou alguma solução, descreva aqui.
Ja to usando o {{ csrf_field }} e também o input type hidden name _token value {{ csrf_token() }}
---

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by cagartner** [comment]
O input name está como `Nickname` em maiúsculo mesmo?

Se possível postar gist com a view do form, rota, controller e etc, fica mais fácil te ajudar.

Abraços!

**Comment by adailsonm** [comment]
https://gist.github.com/adailsonm/63510c6043b0d354853323a3ee7dc029 - Controller
https://gist.github.com/adailsonm/138fdcd0db96970b9d52da6b8eb8993e - View
https://gist.github.com/adailsonm/8e0162cff6a5e82b6c6bdf9d32e13fbe - Rota

**Comment by cagartner** [comment]
Reparei em algumas coisas.

-  Remova o input hidden _token
-  Você está enviando a imagem quando atualiza No seu controller ele só vai efetuar o update se for enviado uma imagem.
- O nome da sua action esta minuscula no controller mais maiuscula na rota (Não tenho certeza se é um problema isso, só é estranho para mim rsrsrs)

Abraços!

**Comment by adailsonm** [comment]
Era isso mesmo, obrigado pela ajuda! \o;
