### ISSUE TITLE
Itens ativos e inativos

### ISSUE THREAD

**Issue by rogerio-pereira** [laravelbrasil/forum#139]
Olá pessoal bom dia, atualmente estou desenvolvendo um CMS para um cliente, nesse cms todas as tabelas, inclusive a de usuários tem uma coluna booleana de ativo/inativo. 

No CMS deve listar todos os itens ativos e inativos, já estou fazendo isso. mas o meu problema é no site só deve mostrar os itens ativos, e no cms só pode fazer login com um usuário ativo (preciso deixar os usuários ativos e inativos porque algumas coisas dependem do usuário, por exemplo o autor de cada matéria...

Estou usando repository (https://github.com/andersao/l5-repository), pensei em duas alternativas, um middleware que rode apenas nas áreas que nao são o painel administrativo, ou usar criteria do próprio repository, mas queria que eu fizesse uma vez e aplicasse em todos os models, para evitar de ficar reescrevendo cada código para cada model novo.

O que vocês sugerem

**Comment by flavianohonorato** [comment]
E porque não Middleware?

**Comment by rogerio-pereira** [comment]
como eu faria esse middleware
Não consegui entender como fazer os middlewares lendo a documentação

**Comment by rogerio-pereira** [comment]
Foi respondido no facebook, usar QueryScopes
https://laravel.com/docs/5.5/eloquent#query-scopes
Aparentemente resolve o meu problema, li por cima, mais tarde eu leio com calma
