### ISSUE TITLE
Login não aconteceu [Wrong Credentials]

### ISSUE THREAD

**Issue by igorkarolesky** [laravelbrasil/forum#144]
Utilizei o php artisan make:auth.
Quando eu me registro e o sistema automaticamente me loga fica tudo OK!
Porém quando eu dou logout e tento fazer o login recebo erro de credenciais invalidas.

**Comment by igorkarolesky** [comment]
Consegui resolver.
Aparentemente o registro encryptava mas a senha que era enviada para o banco de dados não.
Logo as senhas não batiam e o sistema não logava.
Corrigido inserindo corretamente a encryptação enviada para o banco de dados.

**Comment by omarkdev** [comment]
Estou fechando esta issue, pois aparentemente o problema foi resolvido.
