### ISSUE TITLE
VueJs - reload

### ISSUE THREAD

**Issue by danteldev** [laravelbrasil/forum#15]
## Descrição Geral do Problema
Não consigo fazer o reload da pagina usando o vue init webpack meu-projeto
## Problema Encontrado
A pagina não recarrega

## Abordagem
Já instalei o vue-clie e também o yeoman e nada
Instalei o npm install webpack-dev-server --save-dev:/

**Comment by vinicius73** [comment]
A dúvida é sobre vue? @danteldev 
https://forum.codecasts.com.br é o locar mais recomendado

**Comment by danteldev** [comment]
Obrigado @vinicius73 :/
