### ISSUE TITLE
Packages para PDF

### ISSUE THREAD

**Issue by cagartner** [laravelbrasil/forum#16]
## Problema Encontrado
Como no caso de Package para pagamento do pagseguro, gostaria de sugestões e indicações ou até casos de uso de packages para geração de PDF.

Gostaria de conhecer alguns que possuem bom desempenho para geração em massa ou como vocês contornaram esse problema para não estuprar a máquina de produção.

---

## Abordagens

- [barryvdh/laravel-dompdf](https://github.com/barryvdh/laravel-dompdf)
    - Prós:
        - Fácil instalação
    - Contra:
        - Demorado para gerar
- [barryvdh/laravel-snappy](https://github.com/barryvdh/laravel-snappy)
    - Prós:
        - Fácil instalação
        - Gera a partir do HTML
    - Contra:
        - CSS Inline

**Comment by marlon-david** [comment]
Usando Laravel, só uma vez instalei um package para PDF, que foi esse: barryvdh/laravel-dompdf

Mas como no servidor de produção levou quase um minuto pra gerar uma página simples, então troquei para um plugin que gerasse via front-end (do jQuery DataTables)

Se aparecer por aqui algum em PHP que tenha um desempenho melhor, também me interesso

**Comment by fabiosperotto** [comment]
Usando o mesmo pacote que o @marlon-david obtive a mesma experiência em PDFs com layouts gerados pelo frontend. Também fora deixado pra gerar via front. 

Em outro projeto, consigo usar somente numa geração de conferência de pedido, por exemplo, onde é bem simples o PDF (sem estilização).

Preciso também de uma indicação x)

**Comment by hernandev** [comment]
Eu uso o https://github.com/barryvdh/laravel-snappy que é um wrapper do `snappy` e usa o `wkhtmltopdf` pra gerar os arquivos, me atende bem, um dos problemas é sempre gerar views que sejam corretamente compativeis, os CSS preferencialmente devem estar `inline`.

Cada pacote tem sua propria limitação pra gerar PDF a partir de HTML, é entender o caso e testar a solução que melhor lhe atende.

**Comment by cagartner** [comment]
@hernandev A intenção é essa mesma, centralizar várias opções para poder testar a melhor solução já com alguns feedbacks e experiências

**Comment by joaosalless** [comment]
Já tentei utilizar os pacotes `barryvdh/laravel-dompdf` e `barryvdh/laravel-snappy`. Em ambos os casos, o resultado não foi satisfatório.

Li relatos de pessoas que estão usando Phantomjs para gerar PDF e estão felizes com o resultado.
http://jonnnnyw.github.io/php-phantomjs

Estes dois pacotes utilizam Phantomjs e parecem interessantes mas ainda não tive tempo para testar:

https://github.com/danielboendergaard/phantom-pdf

https://github.com/fireguard/report

**Comment by cagartner** [comment]
@joaosalless Muito interessante, quero ver se logo faço uns testes nesses packages.

**Comment by hernandev** [comment]
@cagartner como essa pergunta depende de gostos pessoais, irei fechá-la para limpar a lista de dúvidas pententes.

A issue pode continuar sendo usada para futuras discussões, somente não deixaremos o status de aberto pois varias pessoas já deram opinião e sugestões, o que preenche o objetivo da issue.

**Comment by mclgms** [comment]
Tentei usar o phantom, mas sem sucesso!

**Comment by elton182** [comment]
Uma solução bacana é o jasper para geração de PDF...

**Comment by erickosma** [comment]
Concordo com o @elton182 . Se estiver procurando performance o  JasperReports é boa opção.
