### ISSUE TITLE
Utilizar vue em conjunto com o blade

### ISSUE THREAD

**Issue by tiagopaes** [laravelbrasil/forum#164]
Estou com uma dúvida a respeito de qual a melhor maneira de usar o vue.js e blade juntos em uma aplicação Laravel (Monolito).

## Problema Encontrado

O ideal seria utilizar apenas uma view do blade para carregar e inicializar o view component para criar uma SPA a partir desse ponto e fazer o back-end como uma api, ou seria melhor usar as views do blade normalemente e em alguns pontos usar vue components, ou o ideal é mesmo usar ou um ou outro?

**Comment by vinicius73** [comment]
O _"ideal"_ é manter tudo o mais separado possível, criando seu projeto com o vue-cli e seguindo com o desenvolvimento em um repositório git separado.

https://blog.codecasts.com.br/laravel-vue-js-whatever-1f3d0d688d06
Este link pode ajudar.
