### ISSUE TITLE
Rotas no banco de dados

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#17]
Bom dia, gostaria de saber se é possível fazer as rotas do Laravel no banco de dados. Pensei em fazer um modelo para isso e depois chamar o que está salvo no BD, creio q isso funciona mas não sei se é a melhor das soluções

**Comment by ravanscafi** [comment]
Possível é... recomendado, nem tanto. Qual problema você gostaria de resolver?

**Comment by m4rcosazevedo** [comment]
Existe casos e casos...

Eu tenho uma aplicação, que vou fazer isso, pois, vou querer deixar que o administrador altere algumas coisas das rotas, mas, ele não poderá alterar tudo.
Só poderá alterar o nome que irá para a url.. os names ele não poderá alterar, por exemplo:
Vou criar por padrão...
/catalogo/{category}/{slug}

ai ele pode alterar para:
/produtos/{category}/{slug}
ou o nome que desejar..

Mas só vai poder alterar o nome, não vai poder alterar os parametros...
assim, quando for alterar, só a opção "catalogo", poderá ser alterada.. e vou impedir, o uso de caracteres especiais, etc...

Outra observação é que para cadastrar uma rota, vou criar um arquivo Yaml e nele vou colocar todas as rotas default, e depois recuperar essas informações e salvar no db.. esse arquivo yaml só será lido, quando eu der um php artisan por exemplo.. ainda estou definido como será esse escopo...

**Comment by wilcorrea** [comment]
Todo o sistema de rotas no banco não me parece uma boa ideia. 

O apontamento para menus ou alguns recursos pode ser compreensível, mas ainda assim recomendaria um json com os dados a fazer uma consulta para cada request.

**Comment by omarkdev** [comment]
Porque você não cria uma página "edit" e nessa pagina você mostra apenas o que o administrador está apto a editar?

**Comment by pxpm** [comment]
Essa implementação não vai trazer alguns problemas como _Route Caching_?

**Comment by paulofreitas** [comment]
Depende muito do propósito... Na maioria dos casos, essa não é uma boa idéia.

Lógico que existem exceções, como nos casos onde você [precise criar páginas dinâmicas](http://stackoverflow.com/a/23145539), por exemplo.

O problema de armazenar **tudo** no banco é que isso irá, entre outras coisas:

- introduzir complexidade desnecessária para carregar as rotas;
- introduzir *overhead* no carregamento das rotas;
- inviabilizar o *caching* das rotas;
- dificultar o versionamento das rotas.

Note que você mais perde do que ganha. A menos que sua situação se encaixe ou seja similar ao exemplo citado, aí você poderia estar armazenando algumas rotas no banco. Do contrário, eu não te recomendaria fazer isso. :+1:

**Comment by rafaelpazio** [comment]
Uma solução que eu usaria, seria criar um arquivo modelo de rotas, e quando o usuário alterar as rotas, você iria ler esse modelo, e recriar o arquivo original. Acho que isso resolveria os problemas citados pelo @paulofreitas, pois depois de gerar o arquivo novamente, você poderia chamar os comandos do artisan para limpar e cachear novamente.

```php
// Recria o arquivo de rotas...
Artisan::call('route:clear');
Artisan::call('route:cache');
```
Sem complexidade e overhead, tem cache e versionamento!

**Comment by hernandev** [comment]
o autor da pergunta @Gabrieldesousah não se pronunciou mais sobre o tema, então estou fechando essa pergunta por inatividade, caso sinta necessidade de prolongar a discussão, favor solicitar a reabertura do mesmo.
