### ISSUE TITLE
Erro composer - /autoload_real.php on line 66?

### ISSUE THREAD

**Issue by lucenarenato** [laravelbrasil/forum#172]
Descrição Geral do Problema
Projeto Laravel
Ubuntu 16.04
## Problema Encontrado
Fatal error: composerRequirece031de5a6af1ce876fbf28732e52773(): Failed opening required '/var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/../../App/helpers.php' (include_path='.:/usr/share/php') in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php on line 66

---

## Abordagem
Tentei varias soluçoes no google

prime-automoveis/vendor/autoload.php(7): ComposerAutoloaderInitce031de5a6af1ce876fbf28732e52773::getLoader()
#4 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/laravel/framework/src/Illuminat in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequirece031de5a6af1ce876fbf28732e52773(): Failed opening required '/var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/../../App/helpers.php' (include_path='.:/usr/share/php') in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/../../App/helpers.php): failed to open stream: No such file or directory in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php:66
Stack trace:
#0 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/cursos...', 66, Array)
#1 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php(66): require()
#2 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php(56): composerRequirece031de5a6af1ce876fbf28732e52773('08841bc5a44e560...', '/var/www/cursos...')
#3 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/autoload.php(7): ComposerAutoloaderInitce031de5a6af1ce876fbf28732e52773::getLoader()
#4 /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/laravel/framework/src/Illuminat in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequirece031de5a6af1ce876fbf28732e52773(): Failed opening required '/var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/../../App/helpers.php' (include_path='.:/usr/share/php') in /var/www/cursos/meu/Arquivo Comprimido/prime-automoveis/vendor/composer/autoload_real.php on line 66

**Comment by lucenarenato** [comment]
Resolvido:
Alterei composer.json
"autoload": {
        "files": [
            "app/helpers.php"
e depois rodei 
 composer dumpautoload
e finalmente
php artisan serve.

**Comment by danielson150** [comment]
Como você resolveu este problema? Poderia explicar mais detalhadamente? Estou com este mesmo problema só que é no Symfony.

**Comment by cawecoy** [comment]
@danielson150 pra mim funcionou simplesmente executando `composer dumpautoload`

**Comment by eliacer-droid** [comment]
If none of the above solutions work for you!

1. Delete folder composer. (vendor/composer).
2. Delete autoload.php (vendor/autoload.php).
3. Composer Install.
4. Composer Update.
5. Run services.

I hope it helps.

PD: I do not know much english.

Greetings

**Comment by LeandroSD** [comment]
> If none of the above solutions work for you!
> 
> 1. Delete folder composer. (vendor/composer).
> 2. Delete autoload.php (vendor/autoload.php).
> 3. Composer Install.
> 4. Composer Update.
> 5. Run services.
> 
> I hope it helps.
> 
> PD: I do not know much english.
> 
> Greetings

it worked for me, thanks!

**Comment by mvascs** [comment]
Only delete vendor folder and composer install.

**Comment by moisesdreckmann** [comment]
the composer was not accepting the name 'src', only the one described in psr-4. For me, the solution is to change the namespaces and uses.
