### ISSUE TITLE
Mensagem "Sua conexão não é segura" na hora de testar um projeto Laravel

### ISSUE THREAD

**Issue by denilsonlr** [laravelbrasil/forum#173]
Boa pessoal.
Iniciei os estudos de Laravel ontem e comecei fazendo a instalação do Laravel com Homestead. Tudo ocorreu bem até o teste final quando criei um projeto laravel pra testar no navegador e recebi esse erro:

_"Sua conexão não é segura

O proprietário do meuteste.dev configurou este site incorretamente. Para proteger suas informações de serem roubadas, o Firefox não se conectou a ele.

Este site usa HTTP Strict Transport Security (HSTS) para especificar que o Firefox só pode se conectar a ele com segurança. Como resultado, não é possível adicionar uma exceção para este certificado."_

Acredito que seja configuração errada no servidor relacionado ao protocolo de segurança mas não faço a menor ideia de onde acertar essa configuração.
Grato se alguém puder me ajudar a resolver.

**Comment by jedsonmelo** [comment]
Tenta trocar meuteste.dev para meuteste.local

**Comment by denilsonlr** [comment]
jedsonmelo Vou tentar. Depois posto o resultado aqui. Obrigado

**Comment by lucenarenato** [comment]
Se voce tiver iniciando, tente criar projetos sem homested
<https://about.me/renatolucena?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Renato De Oliveira Lucena
about.me/renatolucena
<https://about.me/renatolucena?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>


Em dom, 22 de jul de 2018 às 16:50, denilsonlr <notifications@github.com>
escreveu:

**Comment by denilsonlr** [comment]
lucenarenato. Eu já tinha instalado o Laravel com o Xampp e estava funcionando bem, mas seguindo orientação de um livro que comprei resolvi instalar pelo homestead. Segundo o livro o homestead evita muitos problemas (incompatibilidades) na hora de publicar o projeto no servidor remoto e te dá muito mais controle de configurações. Por isso optei pelo homestead.

**Comment by denilsonlr** [comment]
Consegui resolver reinstalando o homestead. Não sei ao certo onde havia errado na primeira instalação que ocasionou o erro. Mas agora está tudo ok.
Agradeço a ajuda.
