### ISSUE TITLE
Erro de Acesso

### ISSUE THREAD

**Issue by eas3011** [laravelbrasil/forum#177]
Olá, sou novo ainda no Laravel, estou usando o framework para auxilar algumas tarefas numa empresa que trabalho.

Desenvolvi uma pequena aplicação que vem funcionando perfeitamente há meses, no entanto de dois dias pra cá, sem qualquer alteração no Banco de Dados ou no Código, aparece o erro:

QueryException
SQLSTATE[HY000] [2003] Can't connect to MySQL server on [nome do banco]

Acesso o banco de dados MySQL através de outros aplicativos normalmente, somente através desta aplicação que desenvolvi consta este erro. Já revisei todo o código, senhas e etc. E ainda persiste.

Se puderem me ajudar, ficarei grato.

**Comment by viniciusmelocodes** [comment]
Onde sua aplicação está rodando?

**Comment by eas3011** [comment]
> Onde sua aplicação está rodando?
Roda localmente, porém acessa um Banco de Dados remoto hospedado num servidor on-line.

**Comment by eas3011** [comment]
Resolvido. 
Apenas atualizei o arquivo .env e o sistema voltou ao normal.

**Comment by viniciusmelocodes** [comment]
Show de bola. Agora só precisa fechar a issue.

**Comment by eas3011** [comment]
Grato pela atenção!!! Eu tenho um sistema de controle que usamos internamente, mas tenho vontade de expandir e torná-lo comercial. Quem sabe num futuro precise de parcerias, já sei que posso buscar aqui. Valew!!!
