### ISSUE TITLE
Laravel 5.4 - Removido App:share - Dúvida

### ISSUE THREAD

**Issue by pxpm** [laravelbrasil/forum#18]
Descrição Geral do Problema
Boa tarde novamente a todos.

Estou a utilizar uma package que já é um bocado antiga portanto preciso de refactorar o código para ele correr na versão 5.4

## Problema Encontrado

Tenho o seguinte register no service provider:

```php
public function register()
{
    // Bind it only once so we can reuse in IoC
    $this->app->singleton('App\ConfigWritter\Repository', function($app, $items)
    {
        $writer = new FileWriter($app['files'], $app['path.config']);
        return new Repository($items, $writer);
    });
    // Capture the loaded configuration items
    $config_items = app('config')->all();
    $this->app['config'] = $this->app->share(function($app) use ($config_items)
    {
        return $app->make('App\ConfigWritter\Repository', $config_items);
    });
}
```

O problema está no `$this-app->share `

Alguém me pode ajudar, em como deve ficar a implementação para L5.4 ?

---
## O que eu já tentei.

@paulofreitas 
``` 
Substitua o $this->app->share() por $this->app->singleton():

    $this->app['config'] = $this->app->singleton(function($app) use ($config_items)
    {
        return $app->make('App\ConfigWritter\Repository', $config_items);
    });
```

Retorna o seguinte erro:

```
[2017-02-17 10:29:30] local.ERROR: ErrorException: Illegal offset type in unset in C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Container\Container.php:988
Stack trace:
#0 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Container\Container.php(988): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', 'C:\\xampp\\htdocs...', 988, Array)
#1 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Container\Container.php(204): Illuminate\Container\Container->dropStaleInstances(Object(Closure))
#2 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Container\Container.php(315): Illuminate\Container\Container->bind(Object(Closure), NULL, true)
#3 C:\xampp\htdocs\megaboff\app\ConfigWritter\ConfigServiceProvider.php(29): Illuminate\Container\Container->singleton(Object(Closure))
#4 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(568): App\ConfigWritter\ConfigServiceProvider->register()
#5 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(App\ConfigWritter\ConfigServiceProvider))
#6 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(543): Illuminate\Foundation\ProviderRepository->load(Array)
#7 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#8 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#9 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(270): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 C:\xampp\htdocs\megaboff\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 C:\xampp\htdocs\megaboff\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}  

```

**Comment by paulofreitas** [comment]
Substitua o `$this->app->share()` por `$this->app->singleton()`:
```php
    $this->app['config'] = $this->app->singleton(function($app) use ($config_items)
    {
        return $app->make('App\ConfigWritter\Repository', $config_items);
    });
```

O método `share()` do IoC era pra ter sido descontinuado (*deprecated*) junto com o `bindShared()` no Laravel 5.1 e removido com ele no Laravel 5.2. Por alguma razão desconhecida ele acabou ficando perdido ali por mais tempo, tendo sido removido pelo Taylor no [commit 1a1969b](https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736) no Laravel 5.4.

Hoje em dia o método `singleton()` substitui os métodos `share()` e `bindShared()` de modo similar à maneira como eram usados. ;-)

**Comment by pxpm** [comment]
Boas @paulofreitas obrigado pela resposta. Embora não tenha resolvido, já fiz o que disseste e não funcionou. Eu já tinha lido que a função share estava descontinuada, mas trocando share por singleton simplesmente não resolve. Vou actualizar a pergunta para não alargar mais nos comentários

**Comment by andreportaro** [comment]
Uma dúvida, já tentou substituir o $this->app['config'] =
this->app->singleton por somente uma chamada de Singleton?

$this->app->singleton('config', function() use ($config_items)

{ return $app->make('App\ConfigWritter\Repository', $config_items); });



Em 17 de fev de 2017 08:34, "pxpm" <notifications@github.com> escreveu:

Boas @paulofreitas <https://github.com/paulofreitas> obrigado pela
resposta. Embora não tenha resolvido, já fiz o que disseste e não
funcionou. Eu já tinha lido que a função share estava descontinuada, mas
trocando share por singleton simplesmente não resolve. Vou actualizar a
pergunta para não alargar mais nos comentários

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravelbrasil/forum/issues/18#issuecomment-280615156>,
or mute the thread

**Comment by paulofreitas** [comment]
Oops, perdão pelo erro, cometi um engano... 😳

Você precisa fazer exatamente como demonstrado pelo @andreportaro, o primeiro argumento do método `singleton()` será o apelido (ou *alias*) no IoC para a *closure* que está sendo passada no segundo parâmetro: 

```php
$this->app->singleton('config', function($app) use ($config_items) {
    return $app->make('App\ConfigWritter\Repository', $config_items);
});
```

Essa linha deve ficar assim mesmo, removendo a atribuição feita no trecho `$this->app['config'] =`.

Isso por si só já deve fazer funcionar. :+1:

Não tenho certeza se o `app('config')->all()` continua funcionando como o esperado, mas de qualquer forma, se der erro nesse trecho tu pode alterar isso por `$this->app->make('config')->all()` ou ainda por `resolve('config')->all()`. 😉

**Comment by pxpm** [comment]
Obrigado @paulofreitas pelo esforço e pelas dicas.
Está resolvido, podem fechar :+1:
