### ISSUE TITLE
Bower - Estrutura de arquivos

### ISSUE THREAD

**Issue by jeanmalves** [laravelbrasil/forum#19]
Descrição Geral do Problema

## Problema Encontrado
Olá pessoal, estou importando o dashboard AdminLTE 2 utilizando o bower no laravel 5.3. Ao instalar o tema vi que foi criado o diretorio bower_components em public, mas me gerou uma dúvida porque vu ter que versionar o dashboard todo e não sei se isso é legal.
Gostaria de saber como vocês estruturam o front-end. Eu vi alguns colocarem na pasta vendor.

## Abordagem

Removi o diretório bower_components e instalei via npm conforme sugestão do @joaosalless, o dashboard foi para o diretório node_modules, agora preciso compilar, vou ver como faz.

## Solução

Utilzando o mix.copy() consegui copiar os scripts necessários. Como eu não customizar o tema, não precisei compiar o .less do tema, segue abaixo meu gulpfile:

<pre>elixir(mix => {
    mix.sass('app.scss')
         .webpack('app.js');

    mix.copy('node_modules/admin-lte/bootstrap/js/bootstrap.min.js', 'resources/assets/js/vendor')
       .copy('node_modules/admin-lte/plugins/jQuery/**', 'resources/assets/js/vendor')
       .copy('node_modules/admin-lte/dist/js/app.min.js', 'resources/assets/js/vendor/admin-lte.min.js');

    mix.copy('node_modules/admin-lte/bootstrap/css/bootstrap.min.css', 'resources/assets/css/vendor')
       .copy('node_modules/admin-lte/dist/css/AdminLTE.min.css', 'resources/assets/css/vendor')
       .copy('node_modules/admin-lte/dist/css/skins/_all-skins.min.css', 'resources/assets/css/vendor');

    mix.copy('node_modules/admin-lte/dist/img/**', 'public/img');

    mix.styles([
        'vendor/bootstrap.min.css'
    ]);

   mix.styles([
        'vendor/AdminLTE.min.css',
        'vendor/_all-skins.min.css'
        ], 'public/css/AdminLTE.min.css');

    mix.scripts([
        'vendor/jquery-2.2.3.min.js',
        'vendor/bootstrap.min.js'
    ]);

    mix.scripts([
        'vendor/admin-lte.min.js',
        ], 'public/js/admin-lte.min.js');

});
</pre>

**Comment by joaosalless** [comment]
Você pode instalar o admin-lte via npm e compilar o arquivo .less através do Laravel Mix ou Gulp.

**Comment by jeanmalves** [comment]
@joaosalless fazendo uma correção, eu instalei o AdminLTE 2 desse link aqui: https://almsaeedstudio.com/themes/AdminLTE/index2.html 
Ele usa o bower para baixar na aplicação, esse que vc citou acima instalando via npm ele vai pra onde?

**Comment by joaosalless** [comment]
@jeanmalves, instalando via npm ele vai para a pasta `node_modules/admin-lte`

**Comment by jeanmalves** [comment]
Essa eu descobri @joaosalless o que eu não estou conseguindo agora é compilar o .less pelo laravel  usando o mix. Fiz assim:

`mix.less('node_modules/admin-lte/build/less/AdminLTE.less', 'public/css');`

Eu estu com uma outra duvída, as imagens do tema e os js entre outros como vai ficar?

**Comment by paulofreitas** [comment]
@jeanmalves Tu só vai compilar o LESS se de fato você for alterá-lo. Do contrário basta copiar o CSS compilado já oferecido pelo AdminLTE em `{bower_components|node_modules}/admin-lte/dist/css`.

A idéia da personalização de templates é a seguinte: você copia tudo o que for compilável/otimizável para o diretório `resources`, e lá você faz as alterações que quiser (esteja você copiando do `bower_components`, `node_modules`, etc., não importa o package manager, o procedimento é o mesmo). Seja estendendo eles através de outros arquivos, que é o ideal, seja modificando os arquivos originais que foram copiados (o que não é recomendável, pois você perderá as modificações quando eles forem copiados novamente). Depois disso é que tu vai compilar/otimizar eles para o diretório `public`.

Quanto ao diretório `vendor`, essa é uma boa prática para organização, para separar o que é código de terceiro do que é código da sua aplicação. Tu vai encontrar inúmeras variações disso, eu particularmente separo os arquivos de terceiros em `resources/assets/*/vendor`, seja CSS, JS, LESS, SASS, imagens, etc.

Sobre os demais assets do tema, o que você pode fazer é copiá-los do diretório `node_modules` para o diretório `public` através do `mix.copy()`, como demonstrado em [*Copying files and directories*](https://laravel.com/docs/5.4/mix#copying-files-and-directories) na documentação do Mix. Usei o termo *pode* e não *deve* porque tudo depende da sua necessidade. Se tu não for alterar o JS do AdminLTE, por exemplo, tu pode copiar o arquivo minificado oferecido por ele diretamente para o `public`. Caso você for alterar, você copia para `resources/assets/js` e depois tu minifica eles em `public/js`. E por aí vai. :+1:

**Comment by jeanmalves** [comment]
@paulofreitas esclareceu algumas dúvidas, realmente eu não quero alterar o tema, então acho que vou seguir suas recomendações.
Obrigado por enquanto, vou fazer as modificações e depois eu posto os resultados, valew!

**Comment by jeanmalves** [comment]
Ola pessoal, consegui integrar o template! :+1: 

Segue os resultados na descrição geral.

Obrigado a todos pelas dicas!!
