### ISSUE TITLE
Aplicação Laravel em rota usando cpanel

### ISSUE THREAD

**Issue by marcelcunha** [laravelbrasil/forum#196]
Olá pessoal, fui encarregado de desenvolver uma aplicação Laravel para funcionar como serviço de um determinado site. A aplicação está pronta há algum tempo e me foi dada a tarefa de subi-la para o servidor onde o site está hospedado (gerenciado por cPanel).

Esse app deverá funcionar na rota serviços, ex: ```www.meusite.com.br/servicos``` . Então, subi os arquivos para a pasta servicos do servidor e como imaginei funcionou normalmente, porém, para acessar preciso adicionar ```/public``` no fim da rota: ```www.meusite.com.br/servicos/public```.   

Gostaria de conseguir acessá-lo diretamente na rota /servicos mas nenhumas das abordagens que tentei com .htacess foi satisfatória. Fiz várias pesquisas no google e testei os resultados que achei, mas não tenho conhecimento de .htacces então não tinha muita ideia do que estava fazendo e não cheguei perto de conseguir o que preciso (ou cheguei e não sei). 

Estou em casa e daqui não tenho acesso ao servidor para copiar as regras do .htacess e postá-las aqui. Caso alguém tenha ideia do que fazer e possa me ajudar, agradeço bastante.

**Comment by jedsonmelo** [comment]
vc pode botar `/servicos` com o link simbolico com a public da sua aplicação.

**Comment by marcelcunha** [comment]
@jedsonmelo Se não me engano, já testei isso e continuou não funcionando. Vou pedir acesso mais tarde e testar, respondo se deu certo ou não. Muito obrigado

**Comment by rmsaitam** [comment]
@jedsonmelo como se trata de um servidor em hospedagem compartilhada com cPanel, deve ter o diretório public_html, então precisa criar o link simbólico public_html para public da aplicação.

Se fosse VPS a forma seria configurar o Vhost para o projeto, onde o DocumentRoot seria o diretório da aplicação seguido do /public.

**Comment by jedsonmelo** [comment]
@marcelcunha Na public_html vai ta seu projeto princial (o site) e onde você botou o projeto laravel, que pelo que vc falou é a pasta `serviços`, voce pode move o projeto laravel pra fora da public_html e a pasta serviços vai ser um link simbolico para a pasta public do seu projeto laravel.

Eu tenho uma aplicação laravel em um servidor compartilhado que funciona assim.

**Comment by marcelcunha** [comment]
@jedsonmelo Não havia entendido sua primeira explicação, confesso que não era o que pretendia fazer porém, testei sua dica e funcionou. Muito obrigado.
