### ISSUE TITLE
CRUD-API

### ISSUE THREAD

**Issue by bruno-holanda15** [laravelbrasil/forum#197]
## Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'nome' cannot be null
Detalhar problema - Utilize Markdown ou Gist para códigos

---
## Abordagem
Já tentei criar um cadastro usando o comando new Classe , e o comando create, mas mesmo assim não funcionou.
Coloquei um if para ver se estava retornando alguma coisa no request, e ele está null.

---

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by esron** [comment]
Coloca um trecho do teu código, mas acredito que esse erro seja da modelagem do banco de dados.

**Comment by joaorobertopb** [comment]
A coluna `nome` da sua tabela foi criada como `NOT NULL`. Ao tentar cadastrar os dados, você esta passando o campo "nome" como NULL...


1. Verifique se voce realmente esta buscando a informação corretamente da requisição ( veja se não tem nenhum erro com os nomes das variáveis ou algo do tipo... )

2. Verifique se esse campo "nome" está definido na propriedade **$fillable** do seu model Eloquent ( Mais detalhes aqui: [Mass Assignment ](https://laravel.com/docs/6.x/eloquent#mass-assignment))

> Ao usar o método _**create()**_ do eloquent você esta fazendo uma atribuição em massa, se o campo **nome** não estiver na propriedade **$fillable** do model Eloquent, esse valor será descartado pelo método _**create()**_ e consequentemente você enviara um valor **NULL** para o banco de dados.

Espero ter ajudado!

**Comment by bruno-holanda15** [comment]
Bom dia pessoal,

Consegui achar o erro, estava no envio de informações via teste, devia mandar as informações via json.
Mas obrigado pelo ajuda de todos.

**Comment by geovane95** [comment]
> Bom dia pessoal,
> 
> Consegui achar o erro, estava no envio de informações via teste, devia mandar as informações via json.
> Mas obrigado pelo ajuda de todos.

Pô man ficamos felizes que tenha conseguido resolver. Se puder compartilhar com a comunidade seria bem legal pois outros podem ter essa duvida também.

E se possível feche a issue por gentileza.
