### ISSUE TITLE
Request vazia ao ser submetida via fetch (ajax)

### ISSUE THREAD

**Issue by marcelcunha** [laravelbrasil/forum#199]
Olá, na minha aplicação tenho uma página com alguns checkboxes. Ao clicar, disparo um evento que submete uma requisição a uma rota que atualiza a informação no banco. Adotei uma prática onde evito usar jQuery, por isso estou usando ```fetch API``` do javascript. 
Abaixo o código js que uso:

```javascript
fetch(`/adm/role/${id}`, {
    method: 'PUT',
    headers: {'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content},
    body: formData
})
.then((response) => {console.log(response.json)})
```
A requisição é feita, retorna status 200 no front, consigo ver os parâmetros no console de rede do navegador. Ao analizar os parâmetros no backend descobri que o array estava vazio. Pesquisei, testei algumas sugestões e nada. Alguém tem alguma sugestão de como isso possa funcionar? Obrigado.

**Comment by jedsonmelo** [comment]
Se esse formData for realmente um objeto FormData do Js então esse pode ser o problema, aparentemente é um problema do PHP... Mais informações: https://stackoverflow.com/questions/50691938/patch-and-put-request-does-not-working-with-form-data/50691997

**Comment by marcelcunha** [comment]
@jedsonmelo Dei uma boa pesquisada, achei coisas falando sobre o cabeçalho (fiz alguns testes) mas nem passei perto de achar esse tópico no StackOverflow. Com a resposta resolvi meu problema. Muito obrigado mesmo.
