### ISSUE TITLE
Moderadores

### ISSUE THREAD

**Issue by hernandev** [laravelbrasil/forum#2]
Para que o forum funcione bem, vamos precisar de uma turma pra moderar isso aqui.

Irei coordenar até que tudo possa caminhar sozinho.

Quem tiver interesse em moderar, deixe o username abaixo.

Caso tenhamos 10 ou menos interessados em moderar, incluiremos todos.

Case tenhamos mais de 10 interessados, fazemos votação publica, pra escolher os primeiros 10 que irão ser moderadores.

Até

**Comment by zabaala** [comment]
@zabaala - Contem comigo 👍

**Comment by giordanolima** [comment]
@giordanolima Tamo aí

**Comment by cagartner** [comment]
@cagartner o/

**Comment by andreportaro** [comment]
Tenho interesse.

**Comment by omarkdev** [comment]
@omarkdev Tenho interesse.

**Comment by paulofreitas** [comment]
@paulofreitas 👍

**Comment by williamduarteoficial** [comment]
o/

**Comment by GuilhermeDevSanttos** [comment]
Tenho interesse \o/

**Comment by renanoliveira0** [comment]
@hernandev , tenho interesse

**Comment by wilcorrea** [comment]
@wilcorrea -> fico na espera de boa ; )

**Comment by hernandev** [comment]
Todos aqui, foram adicionados, quem tiver interesse, fazemos novamente no mes que vem.

como colaboradores, comecem a incentivar o uso do mesmo, e zelem pela boa ordem.

**Comment by GabrielApG** [comment]
Blz, interessado. ;)

**Comment by renanoliveira0** [comment]
Como vamos tratar as perguntas lá na comunidade do facebook? Vamos ter uma mensagem padrão solicitando ao usuário que transfira a pergunta para aqui? Os moderadores aqui seriam de lá também?

**Comment by fabiosperotto** [comment]
Tenho interesse em ajudar em qualquer coisa também, quando for possível
Tenho a mesma dúvida do @renanoliveira0 também deixo sugerido aos moderadores (se forem os mesmos de lá) informar uma mensagem padrão com um link pra cá e bloquear os comentários subsequentes. Só tem que ver como será a ação no caso de comentários com dúvidas dentro de postagens sobre pacotes.

ps: parabéns pela ideia de trazer pra fora do facebook o compartilhamento de conhecimento o/

**Comment by renanoliveira0** [comment]
Acho que se continuar liberado lá praticamente vai continuar a mesma coisa, a grande maioria vai continuar fazendo perguntas e esse repo aqui vai ficar vazio...

**Comment by paulofreitas** [comment]
As perguntas continuam sendo feitas também no Slack, no Telegram, no Google+... Creio que não dá para coibir isso. São +6800 membros no Facebook, +2600 membros no Slack, +1700 membros no Google+ e +900 membros no Telegram &ndash; e os números crescem a cada hora. Se for forçado penso eu que as pessoas vão acabar abandonando a comunidade e ir para outros lugares tirarem suas dúvidas...

No [Frontend Brasil](https://github.com/frontendbr/forum/issues) acontece a mesma coisa: nem todo mundo usa o fórum. É um desafio a ser trabalhado. Se por um lado a iniciativa tem por objetivo centralizar conteúdo e agregar valor à comunidade, por outro ela não deve dividir a comunidade. Vai ter quem não tenha nem queira ter conta no GitHub, vai ter quem não queira se expor no GitHub (no próprio grupo do Facebook tem gente que ainda apaga dúvidas para não parecer que não nasceu sabendo), enfim, não é algo que dá para impor já que as consequências disso não são benéficas para a comunidade. 😐 

O que ainda não foi discutido e que talvez possa ser tão útil quanto ter o fórum como ponto inicial para as dúvidas/discussões é usar o fórum para arquivar conteúdo relevante dos outros canais para indexá-los, sejam perguntas repetitivas, tópicos que geraram boas respostas, discussões memoráveis sobre algo, etc. Ainda não sei bem como isso poderia ser feito, mas talvez a equipe de moderação pudesse ir fazendo essa garimpagem e criando issues fechadas (mas não bloqueadas) copiando perguntas/respostas destes outros canais, mantendo a atribuição dos autores e tal e categorizando adequadamente aqui no fórum... É uma idéia e ela pode vir a agregar, penso eu.
O lado bom disso é que todos ganham independente de não usar o fórum para criar a dúvida/discussão, o lado ruim é que irá dar mais trabalho para quem mantém o fórum. 😄 🤣

**Comment by hernandev** [comment]
@renanoliveira0 e @paulofreitas Por mim, podem continuar perguntando lá e outros locais, eu só vou responder e ajudar o que vier por aqui.

Até por que supõe-se um pouco mais de elaboração nas perguntas daqui. o que fica mais fácil de ajudar.
Então, o caminho é sugerir, menos que fiquem menos perguntas rolando por aqui, as que chegarem serão bem vindas.

**Comment by zabaala** [comment]
Falando um pouco dos dois lados, eu vejo da seguinte forma:
Acho indiscutivelmente o Git importante. Não preciso citar todos os benefícios, mas, em síntese, aqui tenderemos a ter mais qualidade nas perguntas e respostas, mas o Facebook é bem mais dinâmico e instantâneo. O grupo lá tem muitas perguntas simples que lá mesmo serão respondidas. Aqui precisarão formalizar a dúvida. Soa mais burocrático. 

Então como tinha dito lá ao Renan, o grande desafio vai ser equilibrar essa balança, pq cada canal tem sua importância. Acho que agora é mais importante compreender e respeitar essas diferenças, antes de acionar algo, que simplesmente segregar.

**Comment by zabaala** [comment]
@paulofreitas acho que esse é o caminho mesmo, mas não vejo necessidade garimpar nada. Como as questões se repetem bastante por lá, bastaria trazer as "novas" pra cá.

Sinto que dessa forma a transição seja de pequeno impacto e grande valor agregado, já que estaríamos trabalhando em cima do objetivo que é criar aqui uma base de informações de alta qualidade.

@renanoliveira0 Vai dar certo, cara. Acredite! Mas, na minha opinião, devemos ir com calma. A gente não pode desconsiderar o fato de que o facebook funciona! Não é o ideal, mas ele funciona, sim. Por esse motivo precisamos de cautela, como o Paulo falou, pra que o público não se disperse.

**Comment by giordanolima** [comment]
O que fazemos com perguntas resolvidas?
Só colocamos a tag ou movemos para as issues fechadas?
Minha opinão é mover para as fechadas... O que vocês acham?

**Comment by zabaala** [comment]
@giordanolima acho que movemos pra fechada mesmo. Fica melhor pra responder o que precisa de atenção, não?

Até fechei a última sem perguntar. Sorry! =D

**Comment by gabrieldesousah** [comment]
@renanoliveira0 e @paulofreitas minha sugestão é mover a resposta para o fórum. 
Por exemplo: alguém faz uma pergunta em alguma das redes sociais, como a seguinte: "Como configuro o banco de dados no Laravel"
ae terão as respostas abaixo e pode haver novas dúvidas a respeito até que o problema seja solucionado. A partir disso os moderadores terão que fazer a seguinte montagem:

**Como configurar o banco de dados no Laravel** (isso ficaria na aba de tutoriais, por exemplo
primiero abra o arquivo... depois faça...

caso apareça o erro X(esse erro vem de uma pergunta no facebook)
faça o seguinte: ....

-------------
Após isso, esse post ficaria salvo para ser utilizado em outras perguntas repetidas.

**Comment by hernandev** [comment]
Fechando o tópico, em breve faremos uma análise e inclusão de novos moderadores.

Discussões de como proceder em caso de perguntas em outras redes e relacionados, vamos fazer em tópicos a parte
