### ISSUE TITLE
Problema PHPUnit

### ISSUE THREAD

**Issue by omarkdev** [laravelbrasil/forum#20]
Estou rodando este teste:

```php
$speaker = factory(Speaker::class)->
$this->assertDatabaseHas('speakers', [
    'email' => $speaker->email
]);
```

## Problema Encontrado
Ao rodar `phpunit` no terminal, ele me retorna este erro: 
```
TypeError: Argument 2 passed to PHPUnit\Framework\Assert::assertThat() must be an instance of PHPUnit\Framework\Constraint\Constraint, instance of Illuminate\Foundation\Testing\Constraints\HasInDatabase given, called in /var/www/projects/hacker-space/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithDatabase.php on line 21
```

Alguem tem alguma solução e/ou já passou por isso?

## Solução

Mudei meu mindset graças ao @andreportaro

**Comment by paulofreitas** [comment]
Tá faltando código, não? 🤔

Afora isso, o testcase está estendendo a classe abstrata `Tests\TestCase`?

**Comment by andreportaro** [comment]
Marcos, olhando o código, tem algo estranho aí.

Vc não pode concatenar um factory com um método de teste.. (vc poderia
chamar uma função anônima depois de criar os speakers, mas não vejo o
porquê)

$speaker = factory(Speaker::class, 1)->create(); // cria um speaker


Depois você chama o método para testar se criou ou não o speaker:

$this->assertDatabaseHas('speakers', [
    'email' => $speaker->email
]);


PS:

Esse teste é melhor que nenhum teste? Sim. Esse teste é um teste que
adiciona valor ou segurança projeto produto? Não tenho tanta certeza..
quer dizer, vc está testando se consegue criar um objeto no db. Sugiro
a leitura deste livro que mostra onde, como e porque o tdd é
necessário:

https://www.amazon.com.br/Engineering-Software-Service-Approach-Computing-ebook/dp/B00CCEHNUM




Em 17 de fev de 2017 04:49, "Paulo Freitas" <notifications@github.com>
escreveu:
