### ISSUE TITLE
Chamar uma método de controller em outra controller

### ISSUE THREAD

**Issue by geovane95** [laravelbrasil/forum#201]
Olá pessoal, estou engatinhando ainda em laravel e isso é algo que me intriga bastante, tenho o costume de colocar uma flag status em minhas tabelas no banco, dessa forma sempre crio o método destroy apenas flegando o status para 0.

Mas em determinados casos, quando tenho alguma entidade com cardinalidade 1-1 tenho que realizar a ativação de outras entidades. 

Por exemplo, tenho um endereço, esse endereço possui o numero da residencia, tipo de residencia, e um objeto de localização que neste temos os dados de logradouro, bairro, cep e cidade.

## Problema Encontrado
Essa cardinalidade é 1-1, portanto ao flegar status de endereço para 0 tenho que fazer o mesmo para localização.

Hoje utilizo este código:

```
public function destroy($id)
    {
        $address = $this->address->find($id);

        if (isset($address)) {
            $idLocation = $address->location->id;

            $location = Location::find($idLocation);

            $location->status = 0;

            $location->save();

            $address->status = 0;

            $address->save();
            return response()->json(["success" => "Endereço inativado com sucesso"], 201);
        }else{
            return response()->json(["error" => "Falha na alteração do endereço!"], 500);
        }
    }


```
Gostaria de saber se a forma como estou fazendo isso está correta?

Pois na minha lógica, eu deveria apenas ter o metódo destroy do endereço na controller do endereço e o método destroy da localização ma controller de localização, sendo este último sem redirect.

**Comment by fabiosperotto** [comment]
Discussão similar aqui: https://laracasts.com/discuss/channels/laravel/call-controller-function-from-another-controller?page=1

É possível chamar um método de um controller em outro controller, porém acredito fortemente que isto seja mau design de código. Neste seu caso eu recomendaria alguma lógica com as Models ou com Traits (veja a resposta do usuário Cronix no link acima que usa um método comum em 2 controllers diferentes, com traits). 

Sugestão de mais leitura a respeito em português com exemplos de código: https://medium.com/sysvale/php-traits-laravel-beyond-d01f27141185

**Comment by TiagoSilvaPereira** [comment]
Olá @geovane95 tudo joia?

O ideal nesse caso é você separar a lógica em um método no seu model (como você está começando, acredito que é a alternativa mais simples. Futuramente talvez você queira separar a lógica em outras camadas como Services, Repositories, etc, mas eu não me preocuparia com isso agora, só marcaria para estudar posteriormente. Separar lógica no Model também é correto e eficiente, e você vai acabar sentindo a necessidade de services e outras camadas se o model ficar muito "cheio").

Essa técnica que você está usando, de marcar status = 0 para deletar algo, é chamada de SoftDelete e já tem pronta no Laravel. Sugiro que dê uma olhada pois vai te ajudar muito e você não precisará ficar controlando a maioria das queries manualmente, checando se status é diferente de 0, etc. A diferença é que o Laravel usa um campo chamado deleted_at e marca a data do "delete". Mas o funcionamento é basicamente o mesmo que você está tentando fazer.

Sucesso amigo!

**Comment by geovane95** [comment]
Legal pessoal!

Muito obrigado pelas dicas.
