### ISSUE TITLE
problema em Envio em massa de post async

### ISSUE THREAD

**Issue by DiegoFSFlor** [laravelbrasil/forum#203]
Eu montei um código que ele irá fazer em massa (mais que um) o envio de post para uma api e a cada solicitação muda o valor no link da api e um valor no body, envio normal eu consigo por Cliente GuzzleHttp, mais estou tentando formatar em concurrency com EachPromise e não esta dando certo, ele da erro Fail que entra no rejected.

código:

```
$client = new Client();
                
                $promises = (function() use ($client, $pessoa_mk, $id, $uuid, $request, $upsertUri, $endpoint) {
                    
                    foreach ($pessoa as $p) {

                        $request['body'] = json_encode(['uuid' => $uuid, 'whenInAuto' => true, 'whenInChat' => true, 'variables' => $p[0]]);
                        $request['headers'] = ['Authorization' => 'Bearer .....', 'Content-Type'  => 'application/json'];
                        $upsertUri = 'https://api...../' . $endpoint . '/' . $id . '/contact/' . $p[1] . '/exec';

                        yield $client->postAsync($upsertUri, ['body' => $request['body'], 'headers' => $request['headers']]);

                    }
                    
                })();
                
                $eachPromise = new EachPromise($promises, [
                    // how many concurrency we are use
                    'concurrency' => 10,
                    'fulfilled' => function (Response $response) {
                        if ($response->getStatusCode() == 200) {
                            $data = json_decode($response->getBody(), true);
                            // processing response of user here
                            echo "successes";
                            Log::info('success::'.$data);
                        }
                    },
                    'rejected' => function ($reason) {
                    // handle promise rejected here
                        echo "fail";
                        Log::info('fail::'.$reason);
                    }
                ]);
                
                $eachPromise->promise()->wait();
```

## Problema Encontrado
Esta retornando Fail e na laravel.log da o erro: **resulted in a `400 Bad Request` response**

**Comment by DiegoFSFlor** [comment]
encontrei o erro, era falta de um parâmetro correto no envio.

**Comment by fabiosperotto** [comment]
> encontrei o erro, era falta de um parâmetro correto no envio.

Olá. Deixe a resolução de qual parâmetro aqui para que outros possam também saber como resolver caso tenham o mesmo problema.

**Comment by DiegoFSFlor** [comment]
Umas das alterações minhas para a solução foi ter o foreach puro, antes eu montei uma array de outro foreach, e desta vez peguei os dados limpos do sql e joguei no foreach. No meu caso a variável vai dentro do body, então o yield adiciona os posts e logo abaixo o Each Promise recebe as informações e faz as chamadas.

O motivo deu fazer isto, é que o retorno de cada chamada demorava em torno 6 segundos, então eu faço 10 chamadas nos mesmo 10 segundos caindo para em média 2 segundos cada post
