### ISSUE TITLE
Blade - active menu

### ISSUE THREAD

**Issue by jhonattasantos** [laravelbrasil/forum#21]
Quero ativar o menu da pagina correspondente usando o blade: 

`<li class="{{ Route::currentRouteName() =='project.index' ? 'active' : '' }}">`

Só que eu quero ativar em toda rota de project: 

`<li class="{{ Route::currentRouteName() =='project.*' ? 'active' : '' }}">`

E o que eu fiz:

`<li class="{{ explode('.', Route::currentRouteName())[0] =='project' ? 'active' : '' }}">`

Minha Duvida é... É assim que vocês estão fazendo? Tem uma forma melhor de fazer? Como?

**Comment by cagartner** [comment]
Olá @JhonattaSantos.

Eu utilizava o `\Request::is('project/*')`.

Doc: https://laravel.com/docs/5.4/requests#request-path-and-method

Abraços!

**Comment by jhonattasantos** [comment]
Show @cagartner ! passei despercebido por essa parte do documento!

**Comment by joaosalless** [comment]
Eu costumo fazer da seguinte forma:

Crio uma macro no Request que retornará a string 'active' caso o nome da rota atual possua a string passada para a macro. Acho mais interessante usar sempre o nome da rota ao invés da url, pois se você precisar mudar algum prefixo ou url nas rotas as views não serão comprometidas.

Para isso é necessário adicionar a macro no método register da classe  `App\Providers\AppServiceProvider`


```php
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        ...

        \Request::macro('activeMenu', function ($routeName) {
            return str_contains(request()->route()->getName(), $routeName) ? 'active' : '';
        });
    }
```

Nas views você chama a macro da seguinte forma

```blade
<li class="{{ request()->activeMenu('project.index') }}">
```

Ou

```blade
<li class="{{ request()->activeMenu('project') }}">
```

**Comment by paulofreitas** [comment]
Uso helpers para isso. :+1:

No caso não uso o `request()->is()` porque uso *named routes* e costumo localizar elas. Com a ajuda do helper [`str_is()`](https://laravel.com/docs/5.4/helpers#method-str-is) as coisas ficam bem simples:

```php
function route_is($routes = [])
{
    return collect((array) $routes)->search(function ($route) {
        return str_is($route, Route::currentRouteName());
    }) !== false;
}

function route_state($routes = [], $active_state = 'active', $inactive_state = '')
{
    return route_is($routes) ? $active_state : $inactive_state;
}
```

O primeiro helper pode ser usado em qualquer lugar, o segundo é para ser usado no frontend. :+1:

A parte boa é que se pode passar mais de uma *named route* neles, usem elas *wildcard* ou não. E ainda pode alterar as classes de estados das rotas. 😃 

Exemplos:

```php
<li class="{{ route_state('project.*') }}">

<li class="{{ route_state(['project.*', 'home']) }}">

<li class="{{ route_state('project.*', 'active', 'inactive') }}">
```

**Comment by omarkdev** [comment]
Eu criei uma view composer e coloquei na view aonde está meu menu. Assim posso verificar a rota com `<li class=" {{ ($menu['main'] == 'welcome') ? 'active' : null }}">Inicio</li>`

Você pode conferir o MenuComposer aqui: https://gist.github.com/omarkdev/56184f02067f2a2d476b3316f1db724c

**Comment by jhonattasantos** [comment]
As soluções do @cagartner  e @paulofreitas ficaram boas para resolução do problema.(Obirgado)
Agora estou usando a solução do paulo!
@omarkdev e @joaosalless muito obrigado também pelas contribuições!
