### ISSUE TITLE
o problema do jedi e os outros padawans

### ISSUE THREAD

**Issue by ghost** [laravelbrasil/forum#219]

**Comment by wilcorrea** [comment]
O que você está procurando exatamente Lucas?

**Comment by wilcorrea** [comment]
O que você chama de evoluir seus conhecimentos?

**Comment by wilcorrea** [comment]
Vou esperar você terminar de editar para responder 😄

**Comment by wilcorrea** [comment]
> um lugar onde posso encontrar pessoas para falar sobre laravel e suas atualizações. e encontrei o grupo, mas como não tinham me respondido, achei que estava desativado ou parado.

Eu acho que a galera que puxava esse fórum deu uma esfriada. Eu mesmo tenho andado meio afastado. Tenho a sensação de que a maioria das pessoas tem ficado pelo Telegram:

- https://t.me/laravelbr
- https://t.me/phpbrasil

**Comment by wilcorrea** [comment]
Vou responder a parte final porque é mais simples

> estou procurando insights de como contribuir com esse grupo sobre laravel. e como posso ajudar quem não sabe nada de laravel, mas quer ajuda.

Tente ingressar pelo telegram que vai ter bastante espaço para trocas de ideias com outras pessoas. No twitter também pode achar boas pessoas para te ajudar a não ficar tão solitário.

Meu twitter é o https://twitter.com/wilcorrea

**Comment by wilcorrea** [comment]
> vou dividir essa resposta em três partes

Bora lá

> sabe quando você entende algo, mas é difícil ensinar para outra pessoa aquilo que você aprendeu ou a forma como tem aprendido? passou por algo parecido, onde você sabe algo, mas não sabe ensinar esse algo?

Legal você ter tido esse insight. Eu acho que parte da jornada de ensinar a aprender é aprender de fato. Articular seu pensamento e conseguir fragmentar seu conhecimento em etapas é vital para os próximos passos, como você diz, se tornar um Jedi, de fato.
Você vai precisar praticar ensinando pra sim mesmo, revisar cada etapa do que você acha que sabe. A cada visita vai descobrir que você não sabia tanto quanto parecia no início (o efeito Dunning-Kruger é sobre isso). Será que você sabe mesmo? Tente destrinchar seu pensamento em notações como diagramas, tente mostrar passo-a-passo como checar no resultado final

> evoluir no sentido de carreira profissional, acadêmica. digo orientação, mentoria nesse sentido. já sentiu-se perdido por não ter um bom material disponível ou aprender a estudar um assunto em questão? como posso orientar as pessoas a utilizarem o laravel da melhor forma possível? ou como posso aprender com outras pessoas mais sobre o laravel?

Sim, passei por isso tem uns 10 anos e eu fui atrás da comunidade e aprendi e evolui demais com isso. Minha dica maior vai ser entender como funciona este universo, conhecer as pessoas e estabelecer sua posição. Sobre mentoria eu devo começar a abrir vagas em breve. Imagino que outras pessoas da comunidade estejam puxando frentes assim também.

> ou por outra evoluir no sentido de aprender mais sobre tecnologia e principalmente sobre laravel. como posso contribuir nessa comunidade?

Acredito que seja um trabalho de formiguinha, sem pressa. Você provavelmente vai aprender mais do que ensinar. Aqui é meio parado mesmo. Roda mais por ai, procura no Youtube, Telegram, Slack, Discord, uma hora você acha sua turma.

Eu tenho interagido mais no https://t.me/phpcomrapadura ou interagido diretamente no meu https://t.me/wilcorrea

**Comment by wilcorrea** [comment]
Desiste não @lucasnuic e me chama nesses canais de comunicação que te passei caso ache interessante pra ti
