### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by guaracyalima** [laravelbrasil/forum#23]
## RESOLVIDO

Eu usava o prettus l5-repository com o laravel 5.1 e 5.3. Qual "gerenciador" de repositorys devo usar no laravel 5.4?

## Problema Encontrado
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

---

## "Solução"

Troquei a chamada ao AppNamespaceDetectorTrait por DetectsApplicationNamespace

---

**Comment by zabaala** [comment]
Não sei se já foi mencionado aqui, mas se você estiver vindo do grupo do Facebook, você já deve ter visto falar por lá que repository é um pattern e não um pacote, e que é altamente recomendado entender para que servem os repositories, para decidir quando e como usá-lo. Portanto, recomendo fortemente que você crie o seu próprio repositório. Repositório de terceiros um dia lhe colocará em uma situação semelhante a que você se encontra agora.

Para o seu caso, recomendo acompanhar esta issue: https://github.com/andersao/l5-repository/issues/332

**Comment by zabaala** [comment]
Seguindo os comentários em andersao/l5-repository/issue/332, esse pull request https://github.com/andersao/l5-repository/pull/331 resolveu o problema.

**Comment by guaracyalima** [comment]
Pois é brother, ainda estou meio que por fora dos pattern.
Seguindo a sua dica consegui "resolver" essa questão

**Comment by paulofreitas** [comment]
Vou complementar o que o @zabaala disse mais acima sobre pacotes de repositórios porque também concordo fortemente que você deva criar sua própria implementação de repositórios... :+1:

Antes disso, aliás, no grupo do Facebook tem várias reclamações sobre este pacote, [parece que ele foi abandonado](https://www.facebook.com/groups/laravelbrasil/permalink/1345767408778644/?match=cmVwb3NpdG9yaWVzLHJlcG9zaXRvcnk%3D). Isso por si só já é um bom motivo para deixar de usá-lo, pois inevitavelmente em algum momento ele irá deixar de funcionar no futuro.

O problema de alguns pacotes de repositórios, principalmente este que foi mencionado, é que eles violam completamente o *repository pattern*. E se eles violam o *pattern* quando o propósito de usá-los seria justamente implementar o *pattern*, deixa de fazer sentido usá-los para esta finalidade.

[Foi perguntado recentemente no grupo do Facebook](https://www.facebook.com/groups/laravelbrasil/permalink/1316962174992501/?comment_id=1317033808318671&comment_tracking=%7B%22tn%22%3A%22R6%22%7D) qual o ganho que se tem com esse pacote sendo que ele parece deixar as coisas mais complexas e só parece repetir o que o Eloquent já faz.

Sem querer, o autor do tópico acabou expondo exatamente o porque o pacote viola o *repository pattern*: ele faz mais coisas do que um repositório deveria fazer, além de ter alto acoplamento com detalhes específicos da camada de acesso aos dados, quando deveria ser exatamente o contrário.

Vou trazer minha resposta do grupo aqui para que fique registrado para consultas futuras os problemas que este pacote pode introduzir em projetos.

Quando o autor do tópico perguntou *O que ganho com esse pacote se ele parece deixar as coisas mais complexas*, minha resposta foi direta:

> Respondendo especificamente sobre este pacote: NADA
>
> Primeiro porque ele viola completamente o *Repository Pattern* e você acaba implementando uma nova camada na aplicação que não tem razão nenhuma de existir. 
>
> Eu sempre costumo lembrar desta resposta no Reddit a respeito de um desses pacotes mágicos de repositórios, a resposta que foi dada à ele serve de modo geral a qualquer pacote de repositório que faça mais do que deveria fazer: https://www.reddit.com/r/PHP/comments/4pnaag/rinvex_repository_is_a_simple_intuitive_and_smart/d4ni0et 😉 
>
> Vou copiar aqui os argumentos principais:
>
> >  *[...] there's precisely ZERO benefit to this repository implementation, because it's an unnecessary abstraction around Eloquent and the Query Builder. You might as well just use straight Eloquent queries, since this implementation is leaking Eloquent implementation details all over the place.*
> > *[...]*
> > *The entire purpose of a repository is abstract away the storage mechanism [...]*
> > *[...]*
> > But when you have things like: $repository->with(['relationship']); and $repository->addGlobalScope()...
> > *Those are Eloquent-specific implementation details that are being leaked into the domain, thereby directly coupling your application to Eloquent despite your attempts to abstract it away.*
>
> Ler com o CAPS LOCK ligado:
> > *If you're tightly coupling to Eloquent & Query Builder, why are you even bothering with another abstraction layer*
>
> Importante compreender:
> > *Methods like these also defeat the purpose of repositories:
$repository->findWhere([['id', '=', 1], ['slug', '!=', 'example']]);*
> > *Repositories are NOT (I repeat NOT) supposed to be generic query interfaces. They are supposed to be SPECIFIC query interfaces:
$userRepository->findActiveUsers();
$userRepository->findBannedUsers();
$orderRepository->findCompletedOrders();*
>
> O ponto mais importante:
> > *The API a repository is supposed to expose to you should explicitly reflect very specific business rules in your application. Why? Because that's the other point of repositories - to act as a domain-facing storage access system, rather than an infrastructure-facing storage access system. It allows queries to be a single source of truth that expresses the needs of your business.*
>
> Este último argumento demonstra bem a utilidade dos repositórios muito além da possibilidade de troca de acesso aos dados que muitas vezes nunca ocorre e, quando ocorre, é muito mais complexa do que isso.
>
> Já surgiu discussões bem interessantes no Laracasts sobre o assunto: https://laracasts.com/discuss/channels/laravel/are-repositories-really-the-way
>
> Inclusive este artigo do Shawn McCool sobre eles é muito pertinente: http://shawnmc.cool/the-repository-pattern
> Deve um repositório criar instâncias do model que ele responde? Para muitos da comunidade, incluindo o Shawn, não. E ele fundamenta muito bem a posição dele, a qual eu passei a concordar.
>
> É válido lembrar ainda que, em muitos casos, quem usa o repository pattern não precisava dele. Para muitos, o conceito de Query Objects já seria o bastante. O Jeffrey ensina este conceito no Laracasts:
https://laracasts.com/lessons/scopes-repositories-and-query-objects
https://laracasts.com/series/whip-monstrous-code-into-shape/episodes/17
>
> Aliás, vou fazer um adendo, tem um artigo do Amo Chohan no DotDev que também dá uma outra ótima perspectiva sobre queries complexas com o Eloquent: https://dotdev.co/writing-advanced-eloquent-search-query-filters-de8b6c2598db
>
> (Um outro adendo: esta série https://laracasts.com/series/whip-monstrous-code-into-shape/ é literalmente FODÁSTICA! Recomendo assinar o Laracasts só para assistir ela! :P)
>
> __Eu uso, acho importante e inclusive recomendo a camada de repositório justamente pelo último ponto citado na resposta do Reddit.__ Desde que, claro, ela seja implementada como deve.
>
> E minha recomendação é sempre criar o seu próprio repositório abstrato da maneira mais enxuta possível. Aí tu vai criando as interfaces e repositórios concretos conforme a necessidade.
>
> No caso de usar pacotes, se isso for realmente necessário, sugiro no máximo a usar implementações enxutas como este aqui da comunidade: https://github.com/artesaos/warehouse
>
> E o conceito de criterias para filtragens complexas? Também é muito interessante. Se implementado de forma lúcida, só vem a somar...
> O exemplo do Amo Chohan em cima do Eloquent é perfeito, se você adaptar este uso do *Decorator Pattern* aos repositórios, é algo que pode vir a torná-los ainda mais interessantes...
>
> E é isso. É urgente que muitos entendam que o *Repository Pattern* não é o que muito destes pacotes implementam. Porque isso muitas vezes gera um custo de tempo desnecessário e não raro causa aquilo que chamam de débito técnico (de *technical debt*: https://en.wikipedia.org/wiki/Technical_debt).

Espero que esta resposta venha a acrescentar à todos os motivos pelos quais "pacotes mágicos" de repositórios não são recomendados. 👍

**Comment by paulofreitas** [comment]
Como os tópicos deste pacote são recorrentes no grupo do Facebook e eu estou sempre advogando contra, achei relevante acrescentar aqui outros argumentos de uma nova resposta que dei por lá: 

Transcrevo aqui a resposta ipsis-litteris para ser usada futuramente quando eu ou quem mais desejar precisar usá-la, de modo que ela seja mais fácil de ser encontrada:

> Recomendo sempre que se crie seus próprios repositórios, afinal repositórios nada mais são do que um design pattern para abstração da camada de acesso aos dados, nada mais do que isso.
>
> O pacote andersao/l5-repository é uma violação do Repository Pattern e não existe nenhuma razão (e em certos casos até mesmo vantagem) de ter uma camada de repositórios usando ele. O princípio existencial do Repository Pattern é a abstração e este pacote além de ter uma API completamente acoplada ao Eloquent ainda expõe métodos que violam a própria razão de existir dos repositórios.
>
> Que sentido faz um repositório ter métodos como findByField(), with(), has() e whereHas()? Isso é papel do ORM, o Eloquent já faz isso.
> Se você vai construir uma consulta com a API do repositório, porque diabos você está usando repositórios? A razão de existir dos repositórios é justamente ABSTRAIR isso. Se um repositório te permite construir uma consulta ele não é um repositório, ele é um erro de projeto - isso o ORM já faz.
> Até mesmo métodos como create() e update() não fazem parte dos repositórios. Repositórios são coleções - collections. Você pode adicionar elementos a coleções? Pode. Como? Salvando instâncias do model, não criando elas dentro dele. Por isso um repositório que segue o Repository Pattern usa o método save(Model). Você passa uma instância do model e ele salva ela. Fim. E como eu atualizo? Com o mesmo método save(). Você usou o método getById(). Ele retornou um model. Você altera o model e envia ele pro save() do repositório. Isso é o padrão, e ele é assim porque ele foi pensado no Data Mapper onde os objetos não possuem essa funcionalidade de se salvarem, no Data Mapper as entidades (o que se conhece como model no Laravel) são classes PHP puras, o que chamam de POPOs (Plain Old PHP Objects). Você preenche as propriedades do objeto e envia ele pro repositório que por sua vez saberá como salvá-lo. No Active Record por mais que o objeto saiba salvar a si mesmo o Repository Pattern é o mesmo, você apenas finge que o objeto do model é burro.
>
> Ainda na parte de consultas complexas/dinâmicas você pode e até mesmo deve usar o Criteria Pattern, mas até aqui este pacote viola isso. O conceito de injetar criterias de forma implícita é outra violação do Repository Pattern, você deve ser explícito sempre. O método deve dizer: eu aceito criterias do tipo tal. Até porque se não for explícito você está violando o princípio da responsabilidade única do SOLID. Se um método aceita qualquer criteria sem requerir ela como argumento, você está violando o SOLID: https://robsoncastilho.com.br/2013/02/06/principios-solid-principio-da-responsabilidade-unica-srp/
>
> Há ainda muitos outros problemas. Por exemplo é outro completo anti-pattern um repositório base (o repositório abstrato do qual os repositórios concretos extendem) ter diversos métodos públicos. Porque diabos eu vou expor todos estes métodos no meu repositório concreto se eu vou implementar apenas dois métodos? Porque diabos eu vou gerar a documentação do código com vários métodos que sequer são usados na base de código? Porque diabos eu vou permitir que usem um repositório concreto além daquilo que foi implementado nele? Isso é completamente contrário não apenas ao Repository Pattern mas também na questão de boas práticas de arquitetura de software, este é o princípio da segregação de interface do SOLID: https://robsoncastilho.com.br/2013/04/14/principios-solid-principio-da-segregacao-de-interface-isp/
>
> Enfim, daria para prolongar muito mais, mas já falei mais sobre isso neste tópico do fórum: https://github.com/laravelbrasil/forum/issues/23#issuecomment-281468700
> Como é um assunto que sempre volta achei relevante expandir ainda mais a razão de eu sempre advogar contra. Porque se ninguém fizer isso a tendência é que mais e mais pessoas aprendam conceitos errados.
>
> O fato é: usar esse pacote ou o Eloquent diretamente não tem diferença nenhuma. Se por um lado ele te apresenta a importantes conceitos como o Criteria Pattern e Presenter Pattern, por outro ele ensina o conceito de repositórios completamente errado, uma visão de quem nunca conheceu o pattern propriamente dito. Veja como os repositórios funcionam no Data Mapper (padrão do Doctrine), foi nele que os repositórios surgiram. É exatamente desta forma que se usa o pattern. Ele também pode ser usado com Active Record (o padrão do Eloquent)? Pode, mas você deve usá-lo seguindo o mesmo princípio de abstração. Do contrário não é um repositório, é um ORM em cima de outro ORM, uma camada sem razão de existir.
>
> O máximo que eu posso recomendar é o pacote https://github.com/artesaos/warehouse da comunidade.
> Primeiro porque ele é baseado em contratos e você é livre para usar somente aqueles que precisar. Ele tem ainda um contrato base completamente enxuto, 3 métodos. Todos os outros de operações CRUD podem ser usados sob demanda, não expondo desta forma métodos que não serão usados. Alguns métodos CRUD violam a parte do método create()/update() mas essa violação em si é das menores, não é nenhum pecado fazer isso.
> De modo geral o pacote foi codificado levando em conta o verdadeiro Repository Pattern e por conta disso sempre faço questão de mencioná-lo, porque ele é uma das poucas exceções. Se você quiser poupar o trabalho de escrever algumas classes base ele é uma excelente opção e até já implementa a parte de transformers do Fractal. Não usando ele opte por criar sua própria base usando ele como um exemplo a ser seguido. :wink:

**Comment by TiagoSilvaPereira** [comment]
Tenho aprendido bastante com essas issues à respeito dos repositórios. Uma dúvida que não quer calar é quanto à operações mais comuns como: 

```php
$user = User::find($id);
```

Eu devo transformar em algo assim?

```php
$user = $this->userRepository->findById($id);
```

Ou seja, considerando que provavelmente eu nunca vá remover o Eloquent do meu projeto, no final ainda é recomendável encapsular até esse tipo de query simples no repositório?

**Comment by paulofreitas** [comment]
@TiagoSilvaPereira Se estiver usando repositórios **deve**. 👍 

Note que ao usar repositórios nenhuma outra classe deve acessar o banco de dados para obter ou salvar dados - servir como camada de acesso aos dados é o **propósito fundamental** de utilizar repositórios. Quando você os implementa, toda e qualquer classe que pretenda obter ou salvar dados deve usar os repositórios para fazer isso. Mesmo usando Active Record, neste caso você finge que o *model* é burro. 😜 

Porque isso é importante? Porque do contrário você não precisaria do *Repository pattern*, talvez no máximo o *Query pattern*. Você pode usar apenas o Eloquent e ainda assim estar usando repositórios. E não se engane, não sendo um projeto muito pequeno isso ainda irá agregar valor ao projeto mesmo que em princípio não pareça.

Quer um bom exemplo? Pense em *caching*. Quando é dito que os repositórios permitem implementar diferentes mecanismos de acesso aos dados, isso inclui *cache stores*. Pense numa implementação de repositório que use o Eloquent diretamente sem *caching*. Agora pense numa outra que estende a primeira e sobrecarrega métodos onde se deseja implementar *caching* das consultas. Com isso temos dois mecanismos de acesso aos dados que internamente usam o Eloquent cada qual ao seu modo. E isso te permite habilitar ou desabilitar o *caching* de dados da aplicação com uma simples troca de *binding* no *container*. Não é mágica, trata-se simplesmente de fazer bom uso dos *design patterns*. 😄 

Tente imaginar como você poderia fazer isso de modo simples e com a mesma granularidade sem repositórios e sem violar princípios do SOLID. Sacou a idéia?

No caso de salvar dados tu simplesmente segue o mesmo princípio do *Data Mapper pattern*: provê um método *save()* ou *store()* no repositório que receba uma instância do *model* que ele manipula e chama o método *save()* do *model* dentro dele. Você simplesmente finge que o *model* do Active Record é burro e não sabe se salvar. Isso não é apenas para atender o *Repository pattern* estritamente mas é também o meio pelo qual você irá atender ao princípio LSP do SOLID. Isto é, *design patterns* como o *Repository* requerem que você siga os princípios do SOLID para serem corretamente implementados. 👍 

Creio que acabei respondendo além do que foi perguntado, mas achei a pergunta muito pertinente e que merecia uma resposta aprofundada. 😀 

Abraços!

**Comment by zabaala** [comment]
> Quer um bom exemplo? Pense em caching. Quando é dito que os repositórios permitem implementar diferentes mecanismos de acesso aos dados, isso inclui cache stores. Pense numa implementação de repositório que use o Eloquent diretamente sem caching. Agora pense numa outra que estende a primeira e sobrecarrega métodos onde se deseja implementar caching das consultas. Com isso temos dois mecanismos de acesso aos dados que internamente usam o Eloquent cada qual ao seu modo. E isso te permite habilitar ou desabilitar o caching de dados da aplicação com uma simples troca de binding no container. Não é mágica, trata-se simplesmente de fazer bom uso dos design patterns. 😄

Neste caso, complementaria que uma classe pode utilizar a outra também. 

Ex.: `CacheProductRepository::getAll()` poderia usar `DbProductRepository::getAll()` para criar o cache, caso ele não existisse, e ambas implementariam a `interface ProductRepository`.

Já para o caso desse vídeo do laracasts **https://laracasts.com/lessons/scopes-repositories-and-query-objects**, uma terceira alternativa seria implementar [Method Objects](https://refactoring.guru/replace-method-with-method-object) e chamá-los dentro do repositório.

Ex:
### Method Object
```php
// 
class GetAllProducts
{
    public function get()
    {
        return Product::where(/* product complex query*/)->get();
    }
}
```
### Product repository
```php

class DbProductRepository
{
    public function getAll()
    {
        return (new GetAllProducts)->get();
    }
}
```

### Same Controller class
```php

class SameController extends Controller
{
    public function index(DbProductRepository $repository)
    {
        return $repository->getAll();
    }
}
```

Desta forma você não permitiria acesso aos dados por fora do repositório e diminuiria a possibilidade de violação do SRP.

**Comment by TiagoSilvaPereira** [comment]
@paulofreitas @zabaala Muito obrigado pelas respostas detalhadas. Tenho certeza que isso tem ajudado muitos, como eu. Perfeito, finalmente consegui terminar o projeto com uma boa implementação de Repository. Seguindo as dicas de outros posts, optei por criar minha própria implementação, com base no [artesaos/warehouse](https://github.com/artesaos/warehouse/), substituindo o l5-repository que eu utilizava até então.

Até o momento o maior benefício que percebi foi o reaproveitamento (quase rolaram lágrimas de ver o código tão bonito 😆 ), em alguns locais que minhas queries estavam duplicadas, agora uma simples chamada ao repository resolve o problema. Tenho certeza que existem muitos outros benefícios e vou procurar aprofundar-me no assunto, é realmente muito interessante.

Agradeço muito pela disposição em ajudar!

Abraços
