### ISSUE TITLE
Laravel e Redes Sociais

### ISSUE THREAD

**Issue by gabmaxs** [laravelbrasil/forum#24]
Estou aprendendo a usar o Laravel Socialite, mas na documentação só fala sobre o login com rede social, queria saber se com o próprio Socialite tem como compartilhar coisa com o facebook, se não, existe algum outro pacote do Laravel para auxiliar nisso?

**Comment by paulofreitas** [comment]
Não, o Laravel Socialite é um package genérico focado apenas em autenticação em redes sociais. :+1:

Para interagir com o Facebook você pode usar o [vinkla/laravel-facebook](https://github.com/vinkla/laravel-facebook). Note que ele é apenas um *bridge/wrapper* para o [Facebook SDK for PHP](https://github.com/facebook/php-graph-sdk), de modo a facilitar o uso dentro do Laravel.

Como demonstrado no README do package, a documentação que vai te interessar é a do próprio SDK do Facebook: https://developers.facebook.com/docs/reference/php

Indo direto à dúvida, tudo que tu irá precisar é:

- Instalar o package com `composer require vinkla/facebook`
- Adicionar o service provider `Vinkla\Facebook\FacebookServiceProvider::class` no array `providers` do arquivo `config/app.php`
- Adicionar o facade `'Facebook' => Vinkla\Facebook\Facades\Facebook::class` no array `aliases` do arquivo `config/app.php`
- Publicar o arquivo de configuração do package com `php artisan vendor:publish`
- [Criar um app no Facebook](https://developers.facebook.com/apps) para obter seu APP_ID e APP_SECRET
- Editar o arquivo `config/facebook.php` com as credenciais do seu app
- Usar o método `Facebook::post()` para publicar, conforme [demonstrado aqui](https://developers.facebook.com/docs/php/Facebook/5.0.0#post)

Você também pode precisar obter um *access token* para realizar a publicação, não abordei aqui pois vai depender de como você irá fazer isso. Você pode tanto usar o próprio *Laravel Facebook* como continuar usando o *Laravel Socialite* para isso, no caso da chamada do método `Facebook::post()` basta passar o *access-token* no terceiro argumento. :wink:

Para mais informações, consulte a documentação do Facebook SDK. 👍 

Não faz parte da sua pergunta mas, se um dia precisar trabalhar com notificações no Facebook, você pode estar usando o package [Facebook Notifications Channel](http://laravel-notification-channels.com/facebook/). :wink:

**Comment by hernandev** [comment]
@Max618 a resposta do @paulofreitas foi esclarecedora sobre o assunto? dê um feedback :)

**Comment by gabmaxs** [comment]
Desculpa, fiquei meio atolado com outras coisas essa semana, obg pela ajuda @paulofreitas, ajudou mto msm!

**Comment by paulofreitas** [comment]
Sem problemas, @Max618! O problema foi resolvido então, certo? 😃

Estarei marcando a dúvida como resolvida para facilitar a filtragem das dúvidas em aberto. Caso precise acrescentar algo, no entanto, a dúvida continua aberta para ser comentada. 😉

Abraço! o/
