### ISSUE TITLE
[resolvido] Ordenação de Queues

### ISSUE THREAD

**Issue by zabaala** [laravelbrasil/forum#25]
É possível ordenar arbitrariamente Queues?

## Problema Encontrado
Possuo uma API que recebe dados de um webhook de um dos serviços financeiros externos que utilizamos aqui na empresa. Ai a situação é a seguinte: pra toda nova fatura (invoice) é gerado um pagamento (payment) e essas entidades, respectivamente, possuem uma relação 1-N. 

Seguindo o fluxo, cada requisição em `/foo/bar/webhook` informa um evento e, de acordo com o evento, ele é processado.

>O cache tá aí nesse meio, tá? Falaremos já já sobre ele...

Pra uma melhor abordagem, o sistema é de Assinaturas, com cobranças recorrentes, e seu fluxo se assemelha ao seguinte:

1. Registramos o novo assinante;
2. Criamos uma nova assinatura, relacionando-a ao assinante; 
3. Processamos o que é necessário internamente; e
4. Submetemos a subscrição para o serviço externo.

Depois disso, precisamos receber (e tratar) os gatilhos oriundos do webhook. Nesse momento o sistema está esperando os dados dos eventos `invoices.created` e `payment.created`, exatamente nessa ordem, para registrar essas informações e seguir o fluxo. 

O problema é que esses eventos estão chegando na ordem inversa, como mostra o meu access_log:

```
0.0.0.0 - - [21/Feb/2017:18:30:33 +0000] "POST /foo/bar/webhook HTTP/1.1" 422 16   "-" "Go-http-client/1.1" "-" {"date":"21/02/2017 15:30:32","env":"prod","event":"customer.created", ...}
0.0.0.0 - - [21/Feb/2017:18:30:34 +0000] "POST /foo/bar/webhook HTTP/1.1" 422 16   "-" "Go-http-client/1.1" "-" {"date":"21/02/2017 15:30:34","env":"prod","event":"subscription.created", ...}
0.0.0.0 - - [21/Feb/2017:18:30:34 +0000] "POST /foo/bar/webhook HTTP/1.1" 404 1520 "-" "Go-http-client/1.1" "-" {"date":"21/02/2017 15:30:34","env":"prod","event":"payment.created", ...}
0.0.0.0 - - [21/Feb/2017:18:30:35 +0000] "POST /foo/bar/webhook HTTP/1.1" 200 14   "-" "Go-http-client/1.1" "-" {"date":"21/02/2017 15:30:34","env":"prod","event":"invoice.created", ...}
```

Como mostrado acima, o evento `payment.created` acontece antes do `invoice.created`, além de retornar 404.

Diante disso, pensei no seguinte:
Receber as requisições e para o evento `payment.created` deixá-lo falhar até o `invoice.created` acontecer. A minha dúvida é:

1. Quando um job falha, suas retentativas acontecem de que forma na fila? Outros jobs são executados antes de uma nova tentativa ou ele vai tentar novamente até falhar, para depois partir para um próximo job?

2. Existe alguma forma de ordenar os Jobs? Se isso fosse possível eu resolveria o problema.

Alguém consegue fazer uma outra leitura desse paradigma? Pq eu só vejo dessa forma.

## Solução

Defini uma ordem de prioridade para as queues. Coloque o Job que trabalha com o processamento do evento `invoice.created` como **high** e o Job que processa o `payment.created` como **low**. Complementar a isso, apliquei um delay de 30 segundos ao Job que processa os eventos  `payment.created`. A primeira alternativa já havia funcionado, mas, por precaução, preferi complementar com o delay pra evitar qq problema.

Eu ainda não entendo como as queues funcionam internamente. Se alguém souber como funcionam esses cálculos que definem essas ordens de prioridades, por favor complemente aqui. Acho de grande importância compreender melhor essa questão.

Estou fazendo alguns outros testes para dar o problema como resolvido. Mas por enquanto, é isso.

Obrigado e um abraço à todos.

**Comment by paulofreitas** [comment]
É realmente muito estranho o evento *payment.created* estar chegando antes do *invoice.created*... 🤔  

Sobre a primeira pergunta, isso vai depender de quantos *workers* tu está rodando. Se estiver rodando apenas um *worker*, até onde sei os jobs serão executados sincronamente, de acordo com a ordem em que foram disparados, até que falhem todas as tentativas e o *worker* pule para o próximo *job* após registrar o *job* atual na tabela de *jobs* que falharam. É possível ainda rodar *jobs* em paralelo colocando múltiplos *workers* em execução &ndash; cada um irá processar um *job* por vez, até que terminem ou falhem. :+1:

Quanto a ordenação, creio que o esquema de priorização em diferentes *queues* demonstrado no [início da documentação](https://laravel.com/docs/5.4/queues#introduction) das *queues* e mais além no item [Queues Priorities](https://laravel.com/docs/5.4/queues#queue-priorities) possa resolver esta questão. Você irá disparar os *jobs* em diferentes *queues* e colocará o *worker* para processar estas *queues* na ordem de prioridade que quiser, podendo assim processar um *job* com prioridade maior antes de um *job* de menor prioridade. :wink:

Talvez também possa ser o caso de processar o evento *invoice.created* com delay, não? Creio ser outra medida possível para resolver este problema. 👍

**Comment by zabaala** [comment]
@paulofreitas Obrigado pela resposta.

É realmente esdrúxulo esse problema. Surreal, até diria. Mas é o que tem pra hoje. hehehehe

Eu estou nesse momento fazendo as modificações para que o processamento das queues funcione de acordo com o seu segundo comentário, pois foi a primeira coisa que me veio em mente. Mas, ainda assim, fico na dúvida irá funcionar. Vou colocar `payment.created` em low priority e `invoice.created` em high priority. Não acho que vá funcionar, mas estou tentando isso e tentarei jogar um delay também.

Quanto aos workers em paralelo, como funciona? Nunca os fiz funcionar assim.

Abraço.

**Comment by paulofreitas** [comment]
> É realmente esdrúxulo esse problema. Surreal, até diria. Mas é o que tem pra hoje. hehehehe

HAHAHA! 🤣 

> Mas, ainda assim, fico na dúvida irá funcionar. Vou colocar payment.created em low priority e invoice.created em high priority. Não acho que vá funcionar, mas estou tentando isso e tentarei jogar um delay também.

Confesso que fiquei na dúvida também, mas até onde sei, ainda que precise combinar com um *delay*, isso deve resolver o problema. :+1:

> Quanto aos workers em paralelo, como funciona? Nunca os fiz funcionar assim.

Li sobre isso pela primeira vez [no fórum do Laracasts](https://laracasts.com/discuss/channels/general-discussion/how-to-speed-up-queues/replies/37925), mas vendo agora colocaram um exemplo na própria documentação, na parte sobre o Supervisor: https://laravel.com/docs/5.4/queues#supervisor-configuration 😃 
Quando tu usa o `num_procs` do Supervisor, ele vai executar o comando especificado abrindo estes N processos e mantendo eles abertos o tempo todo. Evidente que, sem o Supervisor, também seria possível rodar o `php artisan queue:work` múltiplas vezes, o problema aqui é que eles iriam morrer em algum ponto... Como o `queue:work` faz um *pop* na lista de *jobs* pendentes, não existe o risco de um *worker* pegar o *job* que outro já pegou. E aqui ainda cabem inúmeras variações de configuração possíveis, já que tu pode especificar qual *driver* cada *worker* irá processar, quais *queues* ele poderá processar, etc. Coisa linda! :grin:

Abraço! o/

**Comment by rafaelpazio** [comment]
@zabaala, não sei se entendi direito o questionamento, mais se entendi, tenho um problema parecido!

Ainda não desenvolvi isso, porém precisarei em breve ter uma operação seja executada em ordem. Explico: Ao criar um novo usuário, precisarei fazer varias solicitações externas para concluir o cadastro, essas solicitações precisam obrigatoriamente ter uma sequência.

- Realiza a primeira chamada a API, se OK, vai pra próxima
- Realiza a segunda chamada a API, se falhar, não vai executar as próximas.

O que pensei (ainda não cheguei a testar essa idéia, e nem sei se ficaria legal), é criar uma classe que vai controlar isso.

1) Ao realizar o cadastro do usuário, chamo um método dessa classe que vai adicionar a queue o primeiro job.
2) Quando a queue pegar essa job e executar, se ocorreu tudo certo, vai chamar outro método passando um parâmetro informando qual job executou. A classe vai adicionar o próxima job na queue.
3) A queue vai executar o segundo job e no final se falhar, não vai ser adicionado o próximo job na queue até que esse segundo retorne OK.
4) Ao final da operação, ao chamar o método que adiciona a queue, vai verificar que não terá próxima e operação concluída.

Dessa forma consigo controlar a ordem que precisa ser executada, e se algum dia precisar alterar essa ordem, altero somente nessa classe.

Como falei, ainda não implementei isso, e nem sei se ficaria legal dessa forma, porém em breve precisarei implementar isso e até agora foi a única idéia que tive pra isso!

**Comment by zabaala** [comment]
@rafaelpazio No meu caso é diferente.

Pra o que você quer fazer, você pode dar um bind na execução das queues (Um Queue::failing(...), por ex) e ir avançando, parando ou retrocedendo com o processo de cadastro.

No meu caso, eu recebo as requisições ao invés de fazê-las, como é o seu caso.

Estou fazendo uns testes aqui e respondo em breve com a solução.

**Comment by zabaala** [comment]
@paulofreitas vi agora tua resposta. 

Atualizei a issue com a solução que adotei. Vou dar uma lida na documentação pra entender melhor.
Você sabe, internamente, como as queues funcionam?

Essa é a minha maior dúvida. Fiquei com uma sensação de que "funcionou, mas não sei o pq", exceto pelo óbvio delay. hehehehe

Abraço.

**Comment by paulofreitas** [comment]
@zabaala Rapaz, tipo, saber no sentido de ter exata consciência (até mesmo vaga lembrança kkk) de todos os passos envolvidos, definitivamente não... hahahaha Mas olhando o código do framework em si partindo do comando `queue:work`, dá pra entender um pouco o processo e as inúmeras decisões que o framework toma antes de efetivamente processar qualquer *job*. :+1:

Alguns dos arquivos que ajudam a entender a parte mais importante de todo o processo, do momento do `dispatch()` ao processamento do *job*, são estes:

- [`Illuminate\Bus\Dispatcher`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Bus/Dispatcher.php)
- [`Illuminate\Bus\Queueable`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Bus/Queueable.php)
- [`Illuminate\Queue\Console\WorkCommand`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Console/WorkCommand.php)
- [`Illuminate\Queue\Worker`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Worker.php)
- [`Illuminate\Queue\Queue`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Queue.php)
- [`Illuminate\Queue\DatabaseQueue`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/DatabaseQueue.php) *
- [`Illuminate\Queue\Jobs\Job`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Jobs/Job.php)

A implementação de *jobs* e *queues* vai bem mais além, mas olhando estes arquivos já dá pra ter uma idéia de como as coisas funcionam internamente e porque dá pra gente dizer *isso deve funcionar* mesmo sem ter certeza. rs 😝 

\* A implementação do *driver* de banco de dados é a mais fácil de entender, no código dela fica bem simples de sacar a idéia de como os *jobs* ficam "reservados" enquanto há um *worker* trabalhando neles.

Especificamente sobre a ordem de priorização das *queues*, isso é resolvido no [`Illuminate\Queue\Worker->getNextJob()`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Worker.php#L232). Ao rodar o comando `php artisan queue:work --queue=high,default`, por exemplo, internamente o `Worker` irá usar essa ordem fornecida para obter o próximo *job* disponível na conexão (ao não passar nada, internamente ele irá receber apenas a *queue* `default`). No momento em que ele estiver obtendo novos *jobs* podem ter vários *jobs* disponíveis em várias *queues*, ao passar a ordem das *queues* fazemos com que ele priorize alguns *jobs* em detrimento de outros. Sim, quem projetou isso merece um prêmio! 😁 

Creio que isso ajudará a entender melhor! 👍

O importante mesmo é que agora está funcionando! 😁

**Comment by zabaala** [comment]
Valeu, @paulofreitas!!!

Vou dar uma estudada. Se encontrar algo relevante e que ainda não tenha sido citado aqui, eu complemento. 

PS: Realmente funcionou. 

Abraço.
