### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by kneipp** [laravelbrasil/forum#26]
Tenho uma relação one-to-one entre User e Profile.
Cada Profile pode ser: Pessoa Física ou Pessoa Jurídica.

Quais as melhores abordagens para a modelagem e relacionamento?

Algumas pessoas sugeriram que fazer a separação dos modelos Users e Profiles seria um tanto over mas misturar os dados de entidades diferentes parece um erro. A seguir um rascunho dos modelos.

---

## Abordagem

Inicialmente rascunhei os seguintes modelos:

users
- email
- password

profiles
- user_id (fk)
- profile_id (indice)
- profile_type (company ou users)

profile_companies ou profile_legal_persons (na falta de um termo melhor)
- company_name
- social_name
- manager_name
- cnpj
- avatar
- etc

profile_users ou profile_natural_people (na falta de um termo melhor)
- name
- cpf
- avatar
- etc

**Comment by jeanmalves** [comment]
Na minha opinião acho que Users deixa como está e criar Profile, ProfileUser, ProfileCompany.
Profile os itens em comum com ProfileUser e ProfileCompany.
Pode ter outras configurações, depende da sua necessidade.

**Comment by paulofreitas** [comment]
> Algumas pessoas sugeriram que fazer a separação dos modelos Users e Profiles seria um tanto over mas misturar os dados de entidades diferentes parece um erro

Com certeza misturar entidades vai contra todos os princípios da [normalização de dados](https://en.wikipedia.org/wiki/Database_normalization). 👍

Evidente que tudo depende dos requisitos e da possibilidade deles se alterarem, mas a princípio eu não acho necessariamente errado ter um relacionamento 1:1 até porque neste caso você está usando uma relação polimórfica para relacionar os atributos adicionais de cada usuário.

A questão aqui é que, sendo o requisito um usuário só poder ser uma pessoa física **ou** jurídica (e nunca as duas ao mesmo tempo), você não precisa de 4 tabelas, mas apenas 3. Faz mais sentido ter 4 tabelas se um usuário puder ser pessoa física **e** pessoa jurídica ao mesmo tempo, mas não penso ser errado você usar esta estrutura também nos casos em que o requisito implica num relacionamento 1:1. Afinal, se o requisito mudar e um usuário puder ter tanto uma pessoa física como jurídica, ao usar 4 tabelas você não precisaria mexer no *schema*, apenas no código. 😛 

Infelizmente a documentação do Laravel ainda não aborda os relacionamentos polimórficos 1:1. No teu caso, caso o requisito nunca mude, a estrutura em 3 tabelas poderia ficar assim (tomei a liberdade de adotar outras nomenclaturas para te sugerir um padrão mais usual):

*Schemas*:

```
users
    id - integer
    email - string
    password_digest - string
    contactable_id - integer
    contactable_type - string
```
```
companies
    id - integer
    legal_name - string
    trade_name - string
    tax_number - char(14)
    avatar - string
```
```
people
    id - integer
    first_name - string
    last_name - string
    gender - char(1)
    birthdate - date
    tax_number - char(11)
    avatar - string
```

*Models*:

```php
<?php

namespace App\Users;

class User
{
    protected $table = 'users';

    protected $with = ['contact'];

    public function contact()
    {
        return $this->morphTo('contact', 'contactable_type', 'contactable_id');
    }

    public function isCompany()
    {
        return $this->contactable_type == Company::class;
    }

    public function isPerson()
    {
        return $this->contactable_type == Person::class;
    }
}
```
```php
<?php

namespace App\Users;

class Company
{
    protected $table = 'companies';

    public function user()
    {
        return $this->morphOne(User::class, 'contact', 'contactable_type', 'contactable_id');
    }
}
```
```php
<?php

namespace App\Users;

class Person
{
    protected $table = 'people';

    public function user()
    {
        return $this->morphOne(User::class, 'contact', 'contactable_type', 'contactable_id');
    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}
```

Exemplos:

```php
<?php

$user = User::with('contact')->find(1);

if ($user->isPerson()) {
    print "Usuário: {$user->contact->full_name}";
}

if($user->isCompany()) {
    print "Empresa: {$user->contact->trade_name}";
}
```

**Comment by kneipp** [comment]
@jeanmalves @paulofreitas obrigado.

@paulofreitas Sobre as relações polimórficas: https://laravel.com/docs/5.4/eloquent-relationships#polymorphic-relations

**Comment by paulofreitas** [comment]
> @paulofreitas Sobre as relações polimórficas: https://laravel.com/docs/5.4/eloquent-relationships#polymorphic-relations

Sim sim, essa parte da documentação eu conheço e estou sempre referenciando no grupo do Facebook (hehehehe 😝), o que eu me referia é que ela não aborda exemplos com o `morphOne()`, aliás a documentação sequer menciona a existência dele - só conhecendo a API e o código do framework em si para saber que ele existe. 👍

**Comment by kneipp** [comment]
Mais uma referência: https://laravel.com/api/5.4/

**Comment by hernandev** [comment]
Eu acho relações polimórficas um grande canhão pra resolver esse problema.

Eu faria uma tabela de usuários, e uma pra perfis, onde um perfil é uma empresa ou profissional.

Tirando documentos e poucas mudanças, os perfis deveriam pelo menos ser parecidos, e eu faria na mesma tabela.

@kneipp não se esqueça de nos informar a qual solução chegou, e por quê

**Comment by kneipp** [comment]
Fala pessoal optarei pela opção mais simples e se ficar mais complexo com relacionamentos polimórficos.

**Comment by matheusgomes17** [comment]
@paulofreitas e se eu quiser criar um Model Factory para essa relação polimórfica que você sugestionou, poderia me dar algum exemplo de como o fazer?

**Comment by elvispdosreis** [comment]
Eu sou novo no eloquent como eu faço para retornar apenas a entidade correta de acordo com o tipo dela  no caso "pessoa", no doctrine isso e meio automatico


```
{
  "id": 8,
  "uuid": "ae1d40b5-ca91-4cad-9429-1432c613bf5d",
  "pessoa_type": "pessoa_juridica",
  "pessoa_id": 6,
  "deleted_at": null,
  "created_at": "2022-01-23T12:03:02.000000Z",
  "updated_at": "2022-01-23T12:03:02.000000Z",
  "pessoa": {
    "id": 6,
    "uuid": "40a3938f-a9c2-4c9d-819c-87fdf5bb06e2",
    "cnpj": "18986024000127",
    "inscricao_estadual": "142308714",
    "razao_social": "Solano Comercial Ltda.",
    "nome_fantasia": null,
    "substituto": true,
    "prestador": false,
    "deleted_at": null,
    "created_at": "2022-01-23T12:03:01.000000Z",
    "updated_at": "2022-01-23T12:03:01.000000Z",
    "porte": {
      "id": 5,
      "nome": "Micro Empresário individual"
    },
    "natureza": {
      "id": 1112,
      "tipo_id": 1,
      "nome": "Autarquia Estadual ou do Distrito Federal",
      "qsa": false,
      "tipo": {
        "id": 1,
        "nome": "Administração Pública"
      }
    },
    "situacao": {
      "id": 4,
      "nome": "Pendente"
    }
  }
}
```
