### ISSUE TITLE
Agrupar dados de um relacionamento

### ISSUE THREAD

**Issue by mandado** [laravelbrasil/forum#27]
Galera preciso agrupar meu relacionamento por data assim: 

```
  ['22/02/2017' => ['posts do mes aqui], '23/02/2017'=>[posts do mes aqui]]
```
Minha query: 
```
$this->users->where('id', $id)
        ->with(['posts' => function($query) {
               $query->select('id','title','content','date')->groupBy('date','id');
        }])->get();
```

Tentei usar group by mas não rolou, to sem ideia de como fazer isso. podem me dar um norte ?

**Comment by andreportaro** [comment]
Jorge, este não é o funcionamento do Group by do MySQL.

Lembre se que quando você dá um Group by num model, é só um atalho pra
escrever uma query.  No caso, quando vc executar isso você vai agrupar os
resultados pela data..
https://dev.mysql.com/doc/mysql/en/group-by-functions.html

Na verdade você quer puxar todos os registros, e com um algoritmo simples
reordenar os resultados dá query numa nova collection.

Em qui, 23 de fev de 2017 23:15, Jorge Roberto Tomaz Junior <
notifications@github.com> escreveu:

**Comment by mandado** [comment]
to usando postgres. mas o agrupamento não é no users e sim no relacionamento posts,  e também ele não ta agrupando da forma que quero agrupar.

**Comment by andreportaro** [comment]
🤔
https://www.tutorialspoint.com/postgresql/postgresql_group_by.htm

Mesmo assim, o Group by é uma forma de agrupar e agregar valores.

Você quer simplesmente obter do banco os posts ordenados por data.
O próximo trabalho é reordenar os itens em uma nova collection.

Em qui, 23 de fev de 2017 23:31, Jorge Roberto Tomaz Junior <
notifications@github.com> escreveu:

**Comment by mandado** [comment]
neste caso vou te que usr o collection do laravel pra fazer isso ?

**Comment by kleberarruda** [comment]
Tenta assim: 

``` $this->users->where('id', $id)
        ->with(['posts' => function($query) {
               $query->select('id','title','content','date');
        }])->get()->groupBy('date');

**Comment by mandado** [comment]
rolou não :/

**Comment by lizarti** [comment]
Você realmente precisa trazer o User com os posts dentro?

Se você puder trazer pela relação inversa, digo, de buscar os posts de dado user_id, você pode tentar algo assim:

```
$posts= Post::where('user_id', '=', $user)->get()->groupBy(function($item) {
      return $item->date->format('d-M-y');
    });
return $posts;
```
Você ainda pode trazer o User com eager loading antes do 'get', mas vai trazer o user para todos os posts (talvez seja chato).

Se você já estiver trazendo outras informações do User, diria pra fazer duas consultas separadas (o resto e essa) e depois juntar antes de retornar.

**Comment by paulofreitas** [comment]
O @lizarti chamou a atenção para um ponto relevante que talvez tu não tenha percebido...

Na sua tentativa, tu está essencialmente buscando um usuário e retornando ele, ao mesmo tempo em que tenta reordenar/agrupar o relacionamento *posts* dele. Isso de fato não irá funcionar. :+1:

A informação que tu quer são os *posts*, então é eles que você precisa buscar em primeiro plano. Se tu estiver usando um repositório, por exemplo, essa operação seria algo como `PostRepository->byUser(User $user)`, isto é, faria parte do repositório de *posts*.

No caso de você ter apenas o `$user_id`,  o exemplo do @lizarti é o caminho que você deveria percorrer. Se você já tiver o `$user`, você pode usar os demais métodos no relacionamento `$user->posts()`. 😉 

Assim, num eventual `PostRepository`, você teria algo como isso aqui:

```php
<php

namespace App\Posts;

use App\Users\User;

class PostRepository
{
    public function byUser($user)
    {
        $posts = ($user instanceof User) ? $user->posts() : $this->posts->whereUserId($user);

        return $posts->get()->groupBy(function ($post) {
            return $post->date->format('d/m/Y');
        });
    }
}
```

Note que em ambos os casos a consulta só faz um *select* com *where*, o agrupamento fica por conta da *collection* retornada pelo Eloquent. Deste modo as coisas ficam muito mais simples. :wink:

**Comment by andreportaro** [comment]
Galera, a questão é essencialmente que o Jorge não entendeu onde era
responsabilidade do eloquent e da query do banco de dados vs
responsabilidade do processamento da aplicação.

O exemplo do @lizarti ilustra exatamente isso, mas já está concatenado com
funções de collection:

$posts= Post::where('user_id', '=', $user)->get(); // retorna posts do banco

$posts = $posts->groupBy(function($item) { return
$item->date->format('d-M-y'); }); return $posts; // função que utiliza o
método do eloquent para agrupar por chave.

É importante explicar o que está acontecendo, além de mostrar o código, mas
é exatamente esse o processo!

Em sex, 24 de fev de 2017 07:24, Paulo Freitas <notifications@github.com>
escreveu:

**Comment by mandado** [comment]
@lizarti precisava sim. mas acho que vai ser mais complexo fazer assim, porque a ideia era trazer os posts dentro de acoordeon agrupados por data (que seria  o titulo dos accordeon ).

@paulofreitas eu precisava retornar os dados do usuário e também os posts a cada iteração do usuário. ( mas acho que vou ter que numa página retornar só os usuários e no outro os posts )

**Comment by paulofreitas** [comment]
@mandado Então no caso tu também está listando os usuários? Confesso que a princípio não entendi dessa forma, até por conta do `$this->users->where()`...

No caso de voce estar listando os usuários e ao mesmo tempo listando os *posts* de cada um, a dica do `groupBy()` após receber os dados se mantém. Tu só precisa fazer o *eager-load* do relacionamento *posts* e manipular a informação depois de receber ela. Algo assim:

```php
$users = User::with(['posts' => function ($query) {
        $query->latest('date');
    }])
    ->get()
    ->map(function (&$user) {
        $user->posts = $user->posts->groupBy(function ($post) {
            return $post->date->format('d/m/Y');
        });

        return $user;
    });
```

Sim, funciona! 😄

**Comment by mandado** [comment]
@paulofreitas funfou lindamente!!
