### ISSUE TITLE
Utilizar WSDL com certificado SSL expirado

### ISSUE THREAD

**Issue by aurimar** [laravelbrasil/forum#28]
## Descrição Geral do Problema
Pessoal preciso consumir de WS que o certificado SSL está expirado.
Tenho que forçar a aprovação SSL na chamada.

Consigo chamar o Client mais não sei como fazer o (call) chamada do método. 

## Problema Encontrado

Utilizei de recursos para ser passado no Client

```php
$params = [
    'soap_version' => SOAP_1_2, 
    'trace' => 1, 
    'exceptions' => 1, 
    'connection_timeout' => 180, 
    'cache_wsdl' => WSDL_CACHE_NONE
];

$client = new SoapClient('https://.../wsdl', $params);
```

Com faço essa mesma forma para o call ?
alguém pode me ajudar?

---

## Abordagem

Esse WSDL ainda funciona com o asmx versão antiga do WebService .net
Desde já agradeço a todos.
Abraços.

---

**Comment by hernandev** [comment]
@aurimar, por favor, especifique melhor a questão, aparentemente, ela não é relacionada com Laravel e você provavelmente irá conseguir ajuda mais facilmente nos canais adequados.

Então, só pra te dar um norte, se estiver usando NuSoap, o cliente HTTP é sempre o CURL,

então, no NuSoap, dá pra desativar as validações:

```
$client->setCurlOption(CURLOPT_SSLCERT, 'caminho_do_certificado');
$client->setCurlOption(CURLOPT_SSLKEY, 'caminho da chave privada');
$client->setCurlOption(CURLOPT_SSL_VERIFYHOST, false);
$client->setCurlOption(CURLOPT_SSL_VERIFYPEER, false);
```

Porem, acredito que o servidor do WS irá recusar a chamada.

No cliente soap nativo do PHP, você pode desativar a verificação na chave

```php
$params = [
    'soap_version' => SOAP_1_2, 
    'trace' => 1, 
    'exceptions' => 1, 
    'connection_timeout' => 180, 
    'cache_wsdl' => WSDL_CACHE_NONE,
    'stream_context' => [
        'ssl' => [
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        ]
    ]
];

$client = new SoapClient('https://.../wsdl', $params);
```

Espero que ajude.

Irei fechar essa pergunta por não ser relacionado a Laravel.
