### ISSUE TITLE
Retornar campo Status(Char) como String

### ISSUE THREAD

**Issue by jhonattasantos** [laravelbrasil/forum#29]
Como vocês fazem para o seguinte cenario:

Tabela no banco tem o campo status(char)
E status pode ser por exemplo: P, E e C;
onde: P = "**Pronto**", E = "**Espera**", C = "**Cancelado**"

Quando faço a consulta, logicamente ele vai me retornar P,E ou C.
Só que eu quero que ele retorne os nomes.

Pesquisei sobre usar const e enum... mas não consegui bons exemplos.

:/

Help me senão eu vou tratar isso no front-end :/

**Comment by JoseCage** [comment]
@JhonattaSantos Outro jeito seria criar uma tabela por exemplo com nome "**status**" e na tabela onde atualmente tem o campo *status* (que é do tipo char), muda por um status_id (nteger) que será referência a tabela status (campo: **id**), que no meu exemplo ficaria:

| campo     | Tipo     |
| :------------- | :------------- |
| status_id  | integer(11) |
| status       | string (40) |

-----
E como dizia, na tabela onde tú precisa inserir o status, vai apenas inserir o id do status. E quando for exibir o status pega o status pelo id(**_status_id_**) e exibe o nome (**_status_**):

| Campo | Valor|
|:--------|:-----------|
|status_id | 1 |
|status| Pronto|
|status_id | 2 |
|status| Espera |

 `$status = Status::where('id, 1)->pluck('status');`


**PS**: Posso estar errado em algum ponto. Mas creio que dá pra ter uma luz..

**Comment by zabaala** [comment]
Uma outra alternativa também é você mapear esse vetor no seu model e utilizar algo como o Presenter pra retornar essas informações, caso você não queira salvá-las no banco.

**Comment by paulofreitas** [comment]
A princípio um *Presenter* realmente seria uma ótima opção para estar resolvendo isto, já que se trata exatamente de algo relacionado a apresentação. É um perfeito caso de uso do *Decorator Pattern*. :smiley:

É possível ir além, no entanto. Numa arquitetura centrada no domínio (DDD/Hexagonal), o *status* certamente seria um objeto de valor (*Value Object*), onde poderia se auto-validar, por exemplo. Em alguns casos ele poderia ser uma entidade (*Entity*) e estar no banco de dados, mas não sendo o caso, ele certamente seria um VO.

Mas isso ainda não responde a pergunta: como fazer um *lookup* do nome de um *status* pelo código, se VOs são imutáveis e não se pode usar repositórios para VOs?

A resposta é: usando outro *Value Object*. 😄

Um exemplo perfeito para o seu caso são os VOs [`Geography\CountryCode`](https://github.com/nicolopignatelli/valueobjects/blob/master/src/Geography/CountryCode.php) e [ `Geography\CountryCodeName`](https://github.com/nicolopignatelli/valueobjects/blob/master/src/Geography/CountryCodeName.php) da biblioteca [ValueObjects](https://github.com/nicolopignatelli/valueobjects). Note que o VO `CountryCode` é um `Enum` e tudo que o VO `CountryCodeName` tem é um método estático que aceita um `CountryCode` e retorna seu respectivo `CountryCodeName` por meio de um *lookup*. Este é um exemplo perfeito de como você pode estar resolvendo isso através de conceitos mais ricos voltados ao domínio.

Neste exemplo, tudo que você precisa fazer é: `CountryCodeName::getName(new CountryCode('BR'))`. Eu particularmente usaria um método `fromCode()` ao invés de `getName()`, mas aí já é questão de preferência pessoal.

Seu caso seguiria exatamente este mesmo princípio. :+1:

**Comment by cagartner** [comment]
@JhonattaSantos Conseguiu resolver o problema? Estou fechando a demanda visto o longo tempo sem atualizações, qualquer coisa basta reabrir.

Abraços!
