### ISSUE TITLE
Formatar erros de validação no Lumen

### ISSUE THREAD

**Issue by flyingluscas** [laravelbrasil/forum#30]
Estou migrando uma API em Laravel para Lumen, e precisei formatar os erros de validação.

> Consegui solucionar o problema, então isso é uma dica e também uma forma de descobrir se existe uma alternativa melhor.

## Problema Encontrado

Atualmente o formato padrão dos erros é retornado dessa forma

``` json
{
    "email": [
        "The email must be a valid email address."
    ],
    "password": [
        "The password must be at least 6 characters."
    ]
}
```

Mas quero que seja retornado neste formato

``` json
{
    "errors": [
        "The email must be a valid email address.",
        "The password must be at least 6 characters."
    ]
}
```

## Abordagem

Bom, dando uma olhada no código fonte do Lumen, descobri que esse formato é definido em um método chamado **[formatValidationErrors](https://github.com/laravel/lumen-framework/blob/5.4/src/Routing/ProvidesConvenienceMethods.php#L97-L104)** da trait **ProvidesConvenienceMethods**, e o [controller base do Lumen](https://github.com/laravel/lumen-framework/blob/5.4/src/Routing/Controller.php#L7) implementa essa trait.

## Solução

Bom, com essa informação, de que o controller base implementa essa trait, simplesmente reescrevi o método no meu controller base, e funcionou certinho :)

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Validation\Validator;
use Laravel\Lumen\Routing\Controller as BaseController;

class Controller extends BaseController
{
    /**
     * Format validation errors output.
     *
     * @param  Validator $validator
     * 
     * @return array
     */
    protected function formatValidationErrors(Validator $validator)
    {
        return [
            'errors' => $validator->errors()->all(),
        ]; 
    }
}
```

Caso alguém tenha uma solução melhor, mais simples e fácil comenta ai :D

**Comment by meneguite** [comment]
@flyingluscas não vejo uma solução melhor para sua necessidade.. mas ao fazer isso perde a informação de quais fields deram erro na validação, o que se não fizer diferença para você, tudo bem, mas se precisar dela em um futuro pode te trazer problemas..

**Comment by flyingluscas** [comment]
@meneguite Sim, mas claro que nada me impede de colocar também os campos que não passaram na validação dentro do array de errors, o formato ali é livre, na minha situação, achei mais simples dessa forma :)

**Comment by hernandev** [comment]
1) Seria fácil iterar no frontend os erros e exibi-los :)

2) Se precisar transformar um array multi-dimensional em um array unidimensional, use o helper `array_flatten()`

Exemplo `array_flatten()`:

**Array de errors sugerido**
```php
$errors = [
     "email" => [
         "The email must be a valid email address.",
     ],
     "password" => [
         "The password must be at least 6 characters.",
     ],
];
```

**Aplicando a função**
```
$errors = array_flatten($errors);
```

**Resultado**
```
[
     "The email must be a valid email address.",
     "The password must be at least 6 characters.",
]
```

Se o Luman não tiver esse helper, você pode portar a lógica, que é basicamente um array_walk_recursive (creio eu pq não olhei internamente)

**Comment by cagartner** [comment]
Olá

Estou finalizando essa demanda porque acredito que já tenha todas as soluções adequadas já discutida.

Abraços!
