### ISSUE TITLE
Mudar o padrão de hash de usuários no laravel

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#31]
Boa noite pessoal, 
eu tenho um banco de dados com varios usuários em um site e estou refazendo minha página com laravel. O problema é que eu uso um outro método de criptografia nessas contas e preciso aproveitar meu banco de dados. 

Como eu mudo o método de criptografia utilizada em meu sistema?

Obs: eu estou utilizando o login do laravel, criado com oartisan por make:auth

**Comment by IgorDePaula** [comment]
Eu diria pra extender a classe que faz o auth e sobrescrever o metodo que faz a verificação da senha. Isso é OO: herança e polimorfismo.

**Comment by gabrieldesousah** [comment]
Compreendo a ideia. Mas devido a minha inexperiência com Laravel não sei
onde devo ir para fazer isso. Os arquivos q devo alterar e como(usando o
padrão Laravel)

Este email foi escrito no celular. Desculpe-me por qualquer erro gramatical
e de má escrita.

Em 2 de mar de 2017 21:48, "Igor C. de Paula" <notifications@github.com>
escreveu:

**Comment by hernandev** [comment]
@Gabrieldesousah o Laravel suporta drivers de autenticação.

Esses drivers recebem o nome de `Guards`

Você pode criar um novo `Guard` (ou extender o padrão), e para ativá-lo como macanismo de autenticação, o que você precisa fazer é registrá-lo em `config/auth.php`

Veja na documentação, existe um exemplo de como fazer isso:

https://laravel.com/docs/5.4/authentication#adding-custom-guards

**Comment by gabrieldesousah** [comment]
Mudei meus planos: como o bcrypt é melhor do que meu sistema de autenticação, quero pegar a senha digitada do usuário e ver se ela bate com a do banco antigo. após isso, caso as senhas coincidam eu quero que criptografe em bcrypt e salva as duas senhas, a em md5 e a em bcrypt uma do lado da outra para q no futuro eu use apenas um dos logins.

--
Eu tentei alterar os arquivos do laravel que utilizam o bcrypt e alterar para md5 mas ainda assim não consigo fazer o login. 

--
Utilizando a ideia de reescrever a classe estou com problemas em identificar onde o Laravel pega a senha e a criptografa para em seguida olhar o banco de dados. eu não sei qual é esse arquivo e por isso não dou conta de mudar os padrões da senha

**Comment by gabrieldesousah** [comment]
pensei em uma forma diferente: Não precisa criar duas colunas, basta verificar se a senha antiga bate com o md5 e em seguida atualizar a senha com o bcrypt.

**Comment by paulofreitas** [comment]
Para autenticar com o mecanismo antigo e o padrão do Laravel ao mesmo tempo e ainda migrar os *password digests* para o novo formato ao autenticar um usuário com sucesso você precisará criar o seu próprio *user provider*. :wink:

A propósito, essa é talvez a melhor forma de resolver este requisito em específico. 👍 

Eu não cheguei a testar, mas deve funcionar. O importante aqui é demonstrar como você poderá fazer isso, já que no seu caso pode mudar uma coisa ou outra.


### Criando seu próprio *user provider*

Crie uma classe `LegacyUserProvider` que estenda a implementação existente do `EloquentUserProvider`:

```php
<?php

namespace App\Extensions;

use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;
use Illuminate\Contracts\Auth\UserProvider;

class LegacyUserProvider extends EloquentUserProvider implements UserProvider
{
    /**
     * Validate a user against the given credentials.
     *
     * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
     * @param  array                                       $credentials
     * @return bool
     */
    public function validateCredentials(UserContract $user, array $credentials)
    {
        $plain = $credentials['password'];
        $digest = $user->getAuthPassword();

        // Legacy authentication mode
        if (strlen($digest) == 32 && hash('md5', $plain) == $digest) {
            $this->updatePasswordDigest($user, $digest);

            return true;
        }

        // Fallback to the stronger bcrypt authentication
        return $this->hasher->check($plain, $digest);
    }

    /**
     * Update the password digest for the given user in storage.
     *
     * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
     * @param  string                                      $digest
     * @return void
     */
    protected function updatePasswordDigest(UserContract $user, $digest)
    {
        $user->password = $this->hasher->make($digest);
        $timestamps = $user->timestamps;
        $user->timestamps = false;
        $user->save();
        $user->timestamps = $timestamps;
    }
}
```
Salve o arquivo em *app/Extensions/LegacyUserProvider.php*.

### Registrando seu novo *user provider*

Altere o arquivo *app/Providers/AuthServiceProvider.php* para registrar seu novo *user provider* customizado:

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Auth;
use App\Extensions\LegacyUserProvider;
use Illuminate\Support\ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * Register any application authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Auth::provider('legacy', function ($app, array $config) {
            return new LegacyUserProvider($app->make('hash'),
                                          $config->get('auth.providers.users.model'));
        });
    }
}
```

Altere o arquivo *config/auth.php* para usar o novo *user provider* ao invés do *driver* padrão `eloquent`:

```php
    'providers' => [
        'users' => [
            'driver' => 'legacy', // substitua 'eloquent' por 'legacy'
            'model' => App\User::class,
        ],
    ],
```

Pronto! :smiley:

Você terá uma estrutura com uma única coluna para senhas, sendo que você partirá de uma implementação legada em MD5 e irá gradualmente atualizar as senhas para o novo formato Bcrypt cada vez que um usuário autenticar-se com sucesso. :smile:

Quando você identificar que o mecanismo já cumpriu a função dele, basta remover o código adicionado e reverter o *driver* padrão para o `eloquent`.

Um adendo: certifique-se de não limitar o campo de senhas na *migration*, usando apenas `$table->string('password')` para o campo como ocorre numa instalação padrão do Laravel, de modo que as senhas geradas através do Bcrypt possam ser armazenadas sem problemas.

**Comment by gabrieldesousah** [comment]
Show de bola! Tava tentando fugir desse formato para aproveitar as
vantagens do Laravel.. mas pelo jeito não terá como mesmo. Obrigado!

Este email foi escrito no celular. Desculpe-me por qualquer erro gramatical
e de má escrita.

Em 3 de mar de 2017 15:20, "Paulo Freitas" <notifications@github.com>
escreveu:

**Comment by paulofreitas** [comment]
Não sei se entendi o que disse, mas note que isso te permite usar o mecanismo de autenticação do Laravel sem alteração alguma. Faça você a autenticação através do *facade* `Auth` ou *dependency injection* ou ainda usando o *scaffolding* de autenticação que já oferece tudo pronto, essa modificação do *user provider* ocorre num nível mais baixo do framework. Isso quer dizer que ao usar o `Auth::attempt()`, por exemplo, o sistema estará executando o código do seu *user provider* e permitindo usar 2 esquemas de *password digest* diferentes sem que isso afete outras partes da aplicação que se situam num nível mais alto - o que é outra vantagem do Laravel. :smiley:

Note que esse detalhe específico de autenticação legada fica isolado no *user provider* e é executado num nível mais baixo pelo framework, de modo que você não precise se preocupar com isso em nenhuma outra parte da aplicação. :+1:

**Comment by gabrieldesousah** [comment]
Muito obrigado @paulofreitas vou testar e em seguida atualizo aqui!

**Comment by cagartner** [comment]
@Gabrieldesousah conseguiu testar? Podemos fechar essa issue?

**Comment by gabrieldesousah** [comment]
Não consegui resolver meu problema não.. mas pode fechar sim, futuramente
tento de novo

Em 4 de abr de 2017 15:19, "Carlos Augusto Gartner" <
notifications@github.com> escreveu:
