### ISSUE TITLE
Hospedagem para laravel

### ISSUE THREAD

**Issue by gabmaxs** [laravelbrasil/forum#34]
Estou criando um projeto laravel com um professor, e ele quer colocar o "beta" do programa online

## Problema Encontrado
Gostaria de saber, se para hospedar um projeto laravel pode ser usado qualquer provedor de hospedagem, ou se tem q ser algum provedor mais específico. Alguma dica de hospedagem?

**Comment by cagartner** [comment]
Olha, sempre indico Digital Ocean, Amazon, Linode.

Hospedagem brasileiras sempre vai dar uma dor de cabeça para deixar funcionando.

**Comment by wilcorrea** [comment]
A Umbler tem um template Laravel, não é tão eficiente quanto um VPS, mas tem um preço acessível e um painel intuitivo http://help.umbler.com/hc/pt-br/articles/208765446-Utilizando-o-Composer-na-Umbler

**Comment by gabmaxs** [comment]
Obg pelas dicas, olhei tds e gostei bastante do Umbler.

**Comment by renanoliveira0** [comment]
Qualquer cloud que contenha docker...eu particularmente vou de AWS em todos
os projetos que posso decidir isso...

**Comment by cagartner** [comment]
Como se trata de um assunto especulativo e pessoal, estou fechando essa issue, caso seja necessário acrescentar mais informações basta reabrir.
