### ISSUE TITLE
União de queries

### ISSUE THREAD

**Issue by alewp** [laravelbrasil/forum#35]
![screenshot_2017-03-13_00-04-49](https://cloud.githubusercontent.com/assets/26371225/23840040/cb32db4c-0780-11e7-8380-0ebcae1dbfc5.png)

Tenho duas queries:

```php
$total_questions_by_modules = Module::leftJoin('questions', 'modules.id', '=', 'questions.module_id')
    ->join('courses', 'modules.course_id', '=', 'courses.id')
    ->select(DB::raw('modules.id, modules.title, count(questions.id) as total'))
    ->groupBy('modules.id')
    ->orderBy('courses.id')
    ->get();
```

```php
$total_question_module_user = User::find($user_id)
    ->join('scores', 'users.id', '=', 'scores.user_id')
    ->join('questions', 'scores.question_id', '=', 'questions.id')
    ->join('modules', 'questions.module_id', '=', 'modules.id')
    ->join('courses', 'modules.course_id', '=', 'courses.id')
    ->select(DB::raw('modules.id, modules.title, count(DISTINCT questions.id) AS count'))
    ->groupBy('modules.id')
    ->orderBy('courses.id')
    ->get();
```

Como unificar essas duas queries, isto é, retornar em uma única consulta: module id, title, total geral de questions por modules, total questions por modules de um user?

**Comment by paulofreitas** [comment]
Antes de propor minha resposta, note que a segunda consulta não irá retornar o valor desejado. Você não pode usar o `User::find()` e continuar construindo a consulta com o *query builder* - ao fazer isso, o Laravel irá ignorar a filtragem pelo *id* do usuário.

Para funcionar como esperado isso teria que ter sido declarado desta forma:

```php
$total_question_module_user = User::select(DB::raw('modules.id, modules.title, count(DISTINCT questions.id) AS count'))
    ->join('scores', 'users.id', '=', 'scores.user_id')
    ->join('questions', 'scores.question_id', '=', 'questions.id')
    ->join('modules', 'questions.module_id', '=', 'modules.id')
    ->join('courses', 'modules.course_id', '=', 'courses.id')
    ->where('users.id', 3)
    ->groupBy('modules.id')
    ->orderBy('courses.id')
    ->get();
```

---

Minha resposta é baseada no Laravel 5.3+ e o que ela propõe é usar o Eloquent.

Antes de tudo, é válido mencionar que ela supõe que os seus *models* estejam com os relacionamentos devidamente configurados.

A primeira consulta pode ser reduzida nisso aqui através do método [`withCount()`](https://laravel.com/docs/5.4/eloquent-relationships#counting-related-models):

```
$modules = Module::select('id', 'title') // opcional
    ->withCount('questions') // através do relacionamento questions() que se espera existir
    ->orderBy('course_id')
    ->get();
```

Sim, uma única consulta será gerada. Internamente o Laravel irá usar uma *sub-query* para contar a quantidade de perguntas por módulo. Os dados retornados neste caso serão: *id*, *title* e *questions_count*.

Tá, mas e para obter a quantidade de perguntas de um módulo que um usuário já respondeu? Essa é a parte engenhosa. 😄 

O primeiro passo é adicionar um novo relacionamento ao *model* `Module`:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    /* ... */

    public function scores()
    {
        return $this->hasManyThrough(Score::class, Question::class);
    }

    /* ... */
}
```

Sim, as pontuações estão relacionadas às perguntas, e aqui nós temos um atalho para as pontuações de todas as perguntas de um dado módulo. Isso será útil para o passo a seguir.

Usaremos o `withCount()` novamente, mas agora precisaremos usar um *hack* para instruir o Laravel a contar corretamente - nada que afete muito a legibilidade do código:

```php
$modules = Module::select('id', 'title') // opcional
    ->withCount([
        'questions',
        'scores AS user_questions' => function ($query) use ($user_id) {
            $query->select(DB::raw('COUNT(DISTINCT question_id)'))
                ->where('user_id', $user_id);
        }
    ])
    ->orderBy('course_id')
    ->get();
```
Sim, esse é o código final e responde ao que foi perguntado. O retorno será: *id*, *title*, *questions_count* e *user_questions_count*.

Ao usar o `withCount()` e dentro realizar um *select* estamos mudando o comportamento normal do método. Como criamos o atalho para as pontuações das perguntas do módulo, ao fazer o `COUNT(DISTINCT question_id)` estamos simplesmente obtendo o total de perguntas respondidas pelo usuário filtrado no `where()`. Note que neste caso usamos um apelido para a coluna (aliás, isso não está documentado) para que não fosse retornado *scores_count*, o que seria uma informação um tanto quanto ambígua.

Isso é tudo. 😃

**Comment by alewp** [comment]
@paulofreitas, excelente. Muito bom!!!

Dúvida: com eloquent dá pra realizar todos os tipos de consultas? ou tem casos que só com o query builder?

**Comment by paulofreitas** [comment]
@alewp Não digo que o Eloquent por si só sirva 100% das vezes, mas chutando baixo eu diria que ele cobre 90% dos casos. Muitos sistemas sem muita complexidade podem ser feitos 100% com Eloquent uma vez que os relacionamentos estejam corretamente definidos. 😃 

É válido mencionar que internamente o Eloquent usa o próprio Query Builder, aliás, uma versão estendida dele: [Illuminate\Database\Eloquent\Builder](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php). Ele tem métodos próprios para simplificar alguns casos comuns de *fluent queries* com o Query Builder como é o caso do `withCount()`, `has()`, `whereHas()` e afins, e [em certos métodos delega o processamento para o Query Builder](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Builder.php#L1328). 

Quando se diz usar o Eloquent ao invés do Query Builder, é pensar em como o Eloquent poderia resolver determinada situação no lugar do Query Builder, isto é, um conceito *Eloquent first*. Quando se trabalha com os relacionamentos do Eloquent, o conceito de *joins* das *fluent queries* se torna praticamente desnecessário, raramente (para não dizer provavelmente nunca) você irá precisar usar um *join* se estiver realizando uma dada consulta da melhor maneira possível através do Eloquent. 😃 

Precisa contar a quantidade de registros de um relacionamento? Use o `withCount()`.

Precisa retornar apenas registros que possuam registros em um relacionamento? Use o `has()`.

Precisa retornar apenas registros que possuam registros em um relacionamento sob determinada condição? Use o `whereHas()`.

E por aí vai... Uma das poucas situações onde o uso do Query Builder será inevitável é em *reporting*, a geração de relatórios. Casos mais simples o Eloquent dará conta, enquanto casos mais complexos vão acabar usando o Query Builder mais diretamente.

De modo geral o Eloquent é um grande facilitador dentro do Laravel e seu uso é recomendável. Ele torna a implementação de alguns padrões de projeto como o *Repository Pattern* mais trabalhosa mas ainda assim é uma excelente opção de ORM que simplifica bastante o código de uma aplicação. 😉

**Comment by alewp** [comment]
@paulofreitas Show. Obrigado!

**Comment by PriPML** [comment]
Alguém sabe me dizer como ignorar um relacionamento? Uma das minhas entidades está trazendo o seu relacionamento com endereço, mas como não preciso do endereço dessa entidade, para otimizar quero removê-lo e trazer apenas o relacionamento principal, que me interessa.

**Comment by davidrtpereira** [comment]
@PriPML esta ISSUE está encerrada.
Recomendo abrir outra ISSUE e trazer a sua duvida já com o exemplo em código que está usando.
Desta forma conseguimos te orientar melhor e sanar suas duvidas.
