### ISSUE TITLE
hospedagem no cPanel apenas mostra os arquivos

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#36]
Descrição Geral do Problema
bom dia galera, tudo bom? Estou hospedando o meu site laravel num servidor cPanel (o dominio está como "dominio de complemento"). 

## Problema Encontrado
O problema é que quando acesso a página apenas mostra os arquivos, deem uma olhada: http://inovacaonaborracha.ml/

Para eu ver o design eu acesso: http://inovacaonaborracha.ml/public/ 
mas isso não permite o processamento do PHP...
---

## Abordagem
Já tentei editar o arquivo .htaccess na raiz do meu laravel para o seguinte código:
`Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]`

Ainda sem sucesso..
---

**Comment by wilcorrea** [comment]
Você não precisa colocar seu projeto na raiz da hospedagem. Pode colocar fora do public_html/www e mover seu index para dentro da pasta que é exposta alterando caminhos caso seja necessário.

**Comment by gabrieldesousah** [comment]
@wilcorrea é isso mesmo que estou fazendo. o problema é q o laravel não usa index.php pra sua raiz.. ele usa provavelmente o server.php, embora eu não sei bem como que ele funciona exatamente..

**Comment by wilcorrea** [comment]
@Gabrieldesousah pelo que eu entendi o seu projeto está todo na pasta que é exposta para o apache na sua hospesagem. Não é essa a ideia. Você precisa mudar a sua pasta pública e expor apenas o que está lá. A ideia de usar um .htaccess pra fazer o redirecionamento é ruim (falo por experiência própria).

https://laracasts.com/discuss/channels/general-discussion/where-do-you-set-public-directory-laravel-5

**Comment by gabrieldesousah** [comment]
Ainda não consegui ser bem sucedido nessa operação...
Eu estou com o arquivo server.php que ele reconhece o conteúdo, mas não o css e o js.. e com a pasta /public/ que reconhece apenas a parte visual.

A minha estrutura de pastas é a seguinte:

/meusite.com
...

--/publlic_html
--/www
--/Laravel

os arquivos do Laravel estão na pastas /--laravel. o que vc me sugere é retirar dae a pasta public:

/--Laravel
   --/--public

e por ela dentro do meusite.com/public_html? Se for isso ainda não consegui o código ideal para o laravel reconhecer e abrir a página..

**Comment by gabrieldesousah** [comment]
Pessoal, eu coloquei para redirecionar direto para o http://inovacaonaborracha.ml/public/ e parece que todo os servidor está rodando corretamente.. eu só quero nesse caso então parar de mostrar o /public/ e acessá-lo mesmo por http://inovacaonaborracha.ml

**Comment by cagartner** [comment]
Para deixar claro, o Laravel usa index.php como entrada, o server serve para o comando `php artisan serve`.

o Cpanel usa a pasta public_html como root do apache, você vai precisar mudar o nome da pasta `public` do Laravel para `public_html`, no link que o @wilcorrea mandou mostra algumas opções de como mudar o código do Laravel para reconhecer que a pasta  `public` mudou.

Sua estrutura de pasta no servidor deverá ficar assim: 

/meusite.com
--/app
--/bootstrap
--/config
--/database
--/public_html // Era antes a pasta public do Laravel
--/resources
--/routes
--/storage
--/teste
--/vendor
./artisan
./... // Demais arquivos do laravel

**Comment by ezaca** [comment]
@Gabrieldesousah , acesse o link [https://inovacaonaborracha.ml/.env](https://inovacaonaborracha.ml/.env).

Nenhuma senha foi comprometida, mas é recomendável você gerar novamente a chave da aplicação. Eu consegui colocar um site Laravel no cPanel do Hostinger por colocar o projeto todo na pasta privada e colocar só os arquivos públicos na pasta `public` ou `html` ou `www` (depende o lugar). Você provavelmente tem essa opção também, não?

**Comment by gabrieldesousah** [comment]
@exaca, o site está funcionando perfeitamente, o problema é que apenas funciona mostrando o /public/ é isso que eu queria remover..

**Comment by ezaca** [comment]
Como você ainda não resolveu, me responda essas questões:
1. Você entendeu que atualmente você expôs todo o seu projeto, configurações e sessões ao público?
2. Você sabe qual é o seu diretório público?
3. Você quer que o seu diretório público acesse o projeto dentro da pasta "Laravel"?

**Se** e **somente se** a suas respostas forem:
1. Sim, eu vou remover os arquivos do projeto do diretório público.
2. Sim, é o `www`.
3. Sim, por algum motivo eu não quero deixar tudo no diretório raiz, mas dentro da pasta "Laravel".

**Então** faça o seguinte:
1. Remova as coisas do diretório público (`www`).
2. Copie os arquivos da pasta `public` do Laravel para o diretório público `www`.
3. Depois de copiar, pode remover a `public` do Laravel se acha que vai confundir. Ela é inútil.
4. Pode remover aquele `/public_html` também SE não estiver ocupando pra nada. Provavelmente não.
5. Localize o arquivo `index.php` da pasta pública: `/www/index.php`
6. Edite este arquivo `/www/index.php` assim:
    a. Todas as strings que começarem com `'/../bootstrap'`
    b. Devem ser alteradas para incluir uma pasta extra `'/../Laravel/bootstrap'`
    c. Isso por que você não tem o seu projeto na pasta raiz, mas na pasta `/Laravel`.
    d. Ao total devem ser 2 substituições, nas linhas 22 e 36.

Se não entender, diga **o que** não entendeu. Se as respostas forem diferentes, diga quais são.
Mas não deixe do jeito que está. Se você criar um sistema de login no site, ou um arquivo com dados sensíveis (senhas, tokens), por exemplo, do jeito que está agora você entrega todos esses dados publicamente! Até seus logs estão públicos em https://inovacaonaborracha.ml/storage/ atualmente.

PS: é @ezaca, de Zacarias haha

**Comment by sayhicoelho** [comment]
Olá, Gabriel. Você pode tentar dessa maneira:

/meusite.com
--/laravel
--/public_html

1. Você vai mover todos os arquivos da pasta `public` que fica dentro de `laravel` para a pasta `public_html`;
2. Abra e edite o arquivo` index.php` (que agora está na `public_html`);
3. Na linha **22**, você vai deixar assim: `require __DIR__.'/../laravel/bootstrap/autoload.php';`
4. Na linha **36**, você vai deixar assim: `$app = require_once __DIR__.'/../laravel/bootstrap/app.php';`
5. Abaixo da linha **36** você vai acrescentar:

```
$app->bind('path.public', function() {
    return __DIR__;
});

```
Veja se funciona. Atualmente uso essa estrutura.

PS: Os únicos arquivos que ficarão expostos ao público são os que estarão na pasta `public_html`. Seu projeto Laravel ficará seguro.

**Comment by cagartner** [comment]
Vou fechar essa demanda por falta de resposta do autor e visto que já foi respondida várias vezes a solução ideal.

**Comment by gabrieldesousah** [comment]
Uma solução bem simples é apenas direcionar o domínio de complemento para a
pasta pública diretamente. Muito obrigado pela ajuda de todos

Em 4 de abr de 2017 15:05, "Carlos Augusto Gartner" <
notifications@github.com> escreveu:
