### ISSUE TITLE
Postgres lança exceção quando usa token client_credentials em rota protegida com auth:api

### ISSUE THREAD

**Issue by danteldev** [laravelbrasil/forum#37]
Usando o laravel passport quando eu tento acessar uma rota protegida com o auth:api middleware usando um token gerado com grant type cliente_credentials, ao invés de receber a resposta `{"error":"Unauthenticated."}` Eu recebo a exceção listada abaixo.
Então quando TokenGuard tenta receber um User através do EloquentUserProvider, internamente ele envia uma string vazia como parametro (pois não existe usuário no token gerado via client_credentials) e o postgres lança exceção pois não faz cast automático de '' para int.

> QueryException in Connection.php line 647:
> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" (SQL: select * from "users" where "users"."id" = limit 1)
> in Connection.php line 647
> at Connection->runQueryCallback('select * from "users" where "users"."id" = ? limit 1', array(''), object(Closure)) in Connection.php line 607
> at Connection->run('select * from "users" where "users"."id" = ? limit 1', array(''), object(Closure)) in Connection.php line 326
> at Connection->select('select * from "users" where "users"."id" = ? limit 1', array(''), true) in Builder.php line 1718
> at Builder->runSelect() in Builder.php line 1703
> at Builder->get(array('*')) in Builder.php line 493
> at Builder->getModels(array('*')) in Builder.php line 477
> at Builder->get(array('*')) in Builder.php line 409
> at Builder->first(array('*')) in Builder.php line 284
> at Builder->find('') in EloquentUserProvider.php line 47
> at EloquentUserProvider->retrieveById('') in TokenGuard.php line 116
> at TokenGuard->authenticateViaBearerToken(object(Request)) in TokenGuard.php line 90
> at TokenGuard->user(object(Request)) in PassportServiceProvider.php line 251
> at PassportServiceProvider->Laravel\Passport\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in RequestGuard.php line 54
> at RequestGuard->user() in GuardHelpers.php line 49
> at RequestGuard->check() in Authenticate.php line 61
> at Authenticate->authenticate(array('api')) in Authenticate.php line 41
> at Authenticate->handle(object(Request), object(Closure), 'api') in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ThrottleRequests.php line 49
> at ThrottleRequests->handle(object(Request), object(Closure), '60', '1') in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Router.php line 561
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
> at Router->dispatchToRoute(object(Request)) in Router.php line 498
> at Router->dispatch(object(Request)) in Kernel.php line 174
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
> at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
> at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
> at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Kernel.php line 149
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
> at Kernel->handle(object(Request)) in index.php line 53
> at require_once('/home/dantel/Projects/api-cotacoesecompras/public/index.php') in server.php line 21

EloquentUserProvider implementa a função retrieveById desta forma:
```
public function retrieveById($identifier)
    {
        return $this->createModel()->newQuery()->find($identifier);
    }
```

O que basicamente é: 
```
$model = new \App\User(); 
$model->newQuery()->find('');
```

O que funciona normal em sqlite (não testei outro banco de dados), mas lança exceção no postgres.
Tem alguma forma  de corrigir isto sem ser necessário alterar o código dentro do próprio Laravel/Passport?

**Comment by JuaumCruz** [comment]
Acredito que o problema é no próprio framework que não verifica (ou converte) o tipo do dado antes de fazer a comparação, pois ele tem acesso ao model e poderia usar o incrementing para verificar se o valor deveria ser convertido pra int antes da comparação.

Fiz essa modificação, testei e passou a funcionar normalmente.
Segue o link do pull request que fiz com a modificação sugerida: https://github.com/laravel/framework/pull/18364

**Comment by danteldev** [comment]
Obrigado @JuaumCruz !

**Comment by paulofreitas** [comment]
Eu não tenho como testar, posso estar inclusive falando besteira, mas creio que isso deveria ser corrigido no próprio Laravel Passport: https://github.com/laravel/passport/blob/master/src/Guards/TokenGuard.php#L116

Me parece errado enviar uma string vazia para o método `$this->provider->retrieveById()`. Se tivesse um `$psr->getAttribute('oauth_user_id') ?: null` lá ia passar `null` como parâmetro e acredito que isso corrigiria o problema. Não tenho certeza se isso de fato funcionaria, mas creio que a solução deva ocorrer por aí.

É compreensível ele ter fechado a PR no contexto que ele visualizou o problema mas ele não entendeu que em princípio esse código do Laravel Passport não devia estar passando a string vazia para o `UserProvider`, pois é isso que gera problemas em alguns bancos e em outros não. 🤔

**Comment by JuaumCruz** [comment]
Só existe um problema, o passport não tem acesso ao model. Ele usa o framework pra isso, então pra ele não tem como ou porque validar. Se o id do user for um uuid ou uma string, iria funcionar normalmente. 
Acredito que o método whereKey em si é que deveria fazer essa conversão de tipos caso o model indique que sua chave primária é do tipo incrementing. 
Não entendo porque é interessante fazer cast do dado capturado do banco para o model, mas não se é quando usa o mesmo model para fazer a comparação, gerando comportamento diferente em banco distintos. 
Bem no meu caso eu vou deixar esse código alterado no próprio framework, porque não acredito ser responsabilidade de quem usa fornecer algo que não quebre a aplicação. Só falta eu fazer um formulário e deixar lançar exceção porque o usuário não mandou o tipo de dado que eu esperava.

**Comment by paulofreitas** [comment]
O ponto é que não faz sentido enviar uma string vazia para o método `retrieveById()` do `UserProvider` em nenhum contexto. E isso vem do `Guards\TokenGuard` do Passport. Isso deveria ser tratado pelo simples fato que você não está enviando uma informação válida para o contexto onde ela é usada.

Outro ponto é que também não faz muito sentido fazer *casting* para *integer* e transformar a *string* vazia para 0 (zero) e buscar no banco pelo *id* 0 (zero) porque em certos bancos e configurações o 0 (zero) é um valor aceito na coluna de auto-incremento.

Creio eu que a questão é que em princípio o Passport não deveria enviar uma *string* vazia, devendo enviar `empty($id) ? null : $id` ao invés de apenas `$id`. 👍 

Inclusive pelo que testei aqui o PostgreSQL não permite usar uma *string* vazia como chave primária mesmo que o tipo da PK seja *string*. 🤔

**Comment by JuaumCruz** [comment]
Não que eu usaria, mas o postgres aceita string vazia em varchar primary key sim.

**Comment by paulofreitas** [comment]
*My bad*. De fato testei agora novamente e funciona, devo ter cometido algum outro engano, pois havia dado erro. 😆 

Justamente, não que seja algo que qualquer um de nós usaríamos, mas enfim...

Creio que o ponto do Taylor era sobre não ser da responsabilidade do `Eloquent\Builder` e `Query\Builder` fazer essa conversão. Porque se o campo é *integer* e você envia *string*, isso é um erro da aplicação - quer seja enviando uma *string* vazia, letras, letras e números, etc. O problema do *integer casting* é que, por exemplo, se você passar a *string* `'123asdsada'`, ele vai pesquisar pelo *id* 123 - isso introduz um comportamento inesperado.

O que o Taylor não entendeu (provavelmente porque ele não viu esse *stack trace* todo) é que o próprio Passport está gerando esse problema quando tenta obter o `'oauth_user_id'` e recebe uma *string* vazia. Isso ao meu ver deveria ser filtrado pelo Passport e, analisando bem, ele nem deveria passar nada para o `UserProvider->retrieveById()` nesta condição, devendo falhar antes por não ter um `oauth_user_id`. 👍
