### ISSUE TITLE
Testes falhando com a Biblioteca Monolog

### ISSUE THREAD

**Issue by wsduarteoficial** [laravelbrasil/forum#38]
Os testes estão falhando ao adicionar a Biblioteca Monolog.

Uma simples linha em qualquer objeto, falha meu testes

`\Log::info('This is some useful information.');`

Interessante que pelo browser registra o log corretamente em laravel.log

`[2017-03-15 11:59:18] local.INFO: This is some useful information. `

Alguma dica ou configuração que tem que ser setada?

Grato!

**Comment by pedromdev** [comment]
Algum erro foi exibido nos testes? E qual servidor está tentando usar?

Eu tive um problema semelhante a esse quando testava algumas funcionalidades, e não funcionava, e quando rodava a minha aplicação no Apache funcionava. Tudo porque o usuário que você está rodando os testes e o usuário que o Apache usa para atender as requisições são diferentes.

**Comment by wsduarteoficial** [comment]
Não mostra nenhum erro e os testes são local!

`local.INFO:`

**Comment by pedromdev** [comment]
Você pode dizer qual é o servidor que está usando e qual é o sistema operacional?

**Comment by wsduarteoficial** [comment]
Apache2 com Ubuntu 16.04 LTS

**Comment by pedromdev** [comment]
Beleza. Isso me parece problema de permissão de usuário, onde o usuário www-data do Apache tem permissão de escrita nesse arquivo mas o usuário que você está usando para executar os testes não tem.

Peço que verifique essas permissões e veja se parece com essas:

``
-rw-r--r--  1 www-data www-data 4096 Mar 10 13:11 laravel.log
``

Se for esse o caso, configure um grupo para esse arquivo de modo que os usuários desse grupo tenham permissão de escrita nesse arquivo. Isto pode ser feito da seguinte forma:

```shell
sudo addgroup app
sudo usermod -a -G app www-data
sudo usermod -a -G app meuusuario
sudo chgrp app laravel.log
sudo chmod 664 laravel.log
```
Aqui você cria um grupo pra aplicação, diz quais usuários vão ser adicionados a ele, informa o grupo nos proprietários do arquivo e diz agora que esse grupo tem permissão de leitura e escrita:

``
-rw-rw-r--  1 www-data app 4096 Mar 10 13:11 laravel.log
``

OBS.: Se estiver fazendo isso localmente, pode ser necessário reiniciar a sessão do seu usuário.

**Comment by wsduarteoficial** [comment]
Show @pedromdev, resolvido!

Muitíssimo obrigado, valeu!

**Comment by cagartner** [comment]
Visto que foi resolvido estou fechando o issue.
