### ISSUE TITLE
Iniciante no Laravel

### ISSUE THREAD

**Issue by crazyshock** [laravelbrasil/forum#42]
Olá, 

Estou iniciando na jornada Laravel e estou tendo algumas dificuldades que não consegui encontrar uma solução nas pesquisas.

Bom meu objetivo hoje é criar toda a minha aplicação trabalhando em formato API, terei 2 situações, terei a parte WEB e o APP. Até aqui está ok.
Como vou trabalhar na API  preciso usar Tokens para validar meus usuários e permitir que alterem algo do sistema.
Para está solução encontrei o JWT. Estou usando ele, está gerando o meu token tudo certinho e bonitinho. A dúvida está nas routas que a minha aplicação WEB irá validar, por exemplo, quando a pessoa acessar o link: www.meusite.com.br/ ele precisa verifica se está logado, se não estiver será redirecionado para o meusite.com.br/login que é a pagina de login.

O problema de tudo é, como que irei verificar se existe um token criado? Quando eu fazer o login eu armazeno esse Token em uma Sessão ? Assim verifico se a sessão existe e faço os redirecionamentos? Ou qual a melhor forma?

Para exemplificar melhor estou colocando abaixo o meu Routes.php

```php

Route::get('/', function(){
	//preciso verificar se o usuario esta logado ou nao
});

Route::group(['prefix' => 'api'], function () {
	
	Route::get('/', function () {
      return response()->json(['message' => 'Jobs API', 'status' => 'Connected']);;
  	});

    Route::post('/auth/login', 'UsuarioController@login');    
});

```

A minha função de "auth/login" estou retornando apenas uma resposta em JSON com o Token gerado e a data que vai expirar.

O meu problema é nesta rota que é o link da minha pagina principal... 
```php
Route::get('/', function(){
	//preciso verificar se o usuario esta logado ou nao
});
```
Se estivesse logado por exemplo iria chamar "return view(index)".

para entender melhor como que está a minha função de Login segue abaixo:

```php
public function login(AuthenticateRequest $request) {        
      // Get only email and password from request
      $credentials = $request->only('usuario', 'senha');

      // Get user by email
      $user = User::where('usuario', $credentials['usuario'])->first();
      // $company = DB::table('empresas_funcionario')->where('usuario', $credentials['usuario'])->first();

      // Validate Company
      if(!$user) {
        return response()->json([
          'result' => false,
          'error' => Lang::get('messages.userInvalid')
        ], 401);
      }

      // Validate Password
      if (md5($credentials['senha']) != $user->senha ) {
          return response()->json([
            'result' => false,
            'error' => Lang::get('messages.passInvalid')
          ], 401);
      }

      // Generate Token
      $token = JWTAuth::fromUser($user);

      // Get expiration time
      $objectToken = JWTAuth::setToken($token);
      // $expiration = JWTAuth::decode($objectToken->getToken())->get('exp');

      return response()->json([
        'com' => $user,
        'access_token' => $token,
        'token_type' => 'gestor'
      ]);
    }
```

Agradeço a ajuda antecipadamente e desculpe se postei algo errado.

**Comment by lincolnbrito** [comment]
@crazyshock se sua API for Restful ela tem que ser stateless, ou seja, não guardar estado. Então você não deve guardar o token na sessão, deve ser armazenado no cliente via local storage, por exemplo.

> O problema de tudo é, como que irei verificar se existe um token criado? 

O token gerado na API deve ser passado em todas as requisições, se for válido/inválido a API irá informar.

Me corrijam se estiver errado

**Comment by crazyshock** [comment]
@lincolnbrito você está certo, problema é que estou usando está mesma autenticação na página Web ou seja a ideia é criar apenas uma função de 'login', por exemplo, utilizar tanto no meu App como também na minha página da Web.

Problema que quando eu abro o meu site: www.meusite.com/ ele vai cair na Route::get("/") certo? nesse momento eu preciso verificar se ele está logado ou não, se não estiver logado preciso mostrar a tela de login, porém como estou trabalhando com a Api Restful eu não tenho o Token do usuário ainda ele precisa ir primeiro para tela de 'login'.

E a pergunta é? O que eu faço? Hahaha

Entendeu mais ou menos a ideia? 

Obrigado pela sua respostas.

**Comment by cagartner** [comment]
@crazyshock estou finalizando essa demanda porque vejo que a pergunta é mais relacionado à frontend na tratação da autenticação no SPA e não na aplicação.

Dá uma olhada no exemplo de SPA do @codecast: https://github.com/codecasts/spa-starter-kit

E acredito que sua pergunta será melhor respondida lá tb: https://forum.codecasts.com.br/
