### ISSUE TITLE
Task Scheduling chamando classe

### ISSUE THREAD

**Issue by andretrevas** [laravelbrasil/forum#43]
Criei uma Task a qual vai chamar uma função todos os dias em determinado horário. Essa task vai simplesmente chamar uma função dentro de uma das minhas classes. Porém, quando tento executar aparece um erro no logs.txt do Laravel.
Já configurei uma cron no servidor:

    * * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1

## Problema Encontrado
Meu arquivo Kernel.php está da seguinte forma

    <?php

    namespace App\Console;

    use Illuminate\Console\Scheduling\Schedule;
    use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
    use App\Library\ImportData;

    class Kernel extends ConsoleKernel
    {
        /**
         * The Artisan commands provided by your application.
         *
         * @var array
         */
        protected $commands = [
            //
        ];

        /**
         * Define the application's command schedule.
         *
         * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
         * @return void
         */
        protected function schedule(Schedule $schedule)
        {
            $schedule->call(function () {
                ImportData::getImport();
            })
            ->dailyAt('03:00')
            ->timezone('America/Sao_Paulo')
            ->appendOutputTo(public_path() . '/schedule.txt');
        }

        /**
         * Register the Closure based commands for the application.
         *
         * @return void
         */
        protected function commands()
        {
            require base_path('routes/console.php');
        }
    }

Minha classe ImportData está assim:

    <?php

    namespace App\Library;

    use App\User;
    use Illuminate\Support\Facades\Hash;

    class ImportData {
        public static function getImport() {
            try {
                self::getImportFile("Inf_imvs_ativ.xml", 1);
            } catch (\Exception $e) {
                $path = storage_path() . '/logs';
                if (!is_dir($path)) {
                    mkdir($path, 0777);
                }
                $myfile = fopen($path . '/erro.txt', "a");
                fwrite($myfile, $e->getMessage() . PHP_EOL);
                fclose($myfile);
            }
        }
    }

No arquivo de log temos:

```
#50 /var/www/novoCM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/novoCM/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /var/www/novoCM/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}
```

Não gera o log de erro que coloquei, nem o arquivo schedule.txt

**Comment by paulofreitas** [comment]
O log foi suprimido quase todo, mas aparentemente nada ali tem relação com o problema. 👍 

É bem provável que a *task* do Cron não esteja corretamente configurada. Como ela está enviando a saída e os erros pro `/dev/null`, nenhum erro é reportado pelo Cron.

Me confirme se no seu `crontab -l` a *task* do Cron foi configurada assim:

    * * * * * php /var/www/novoCM/artisan schedule:run >> /dev/null 2>&1

Note que o caminho aponta para o seu projeto. A documentação do Laravel peca em deixar mais evidente de que você deve mudar o tal do `/path/to/artisan`. Se não estiver assim, edite a linha da *task* em conformidade através do `crontab -e`, salvando o arquivo através do <kbd>Ctrl + X</kbd> e depois <kbd>Y</kbd> e <kbd>Enter</kbd>.

Observe que fica mais fácil de testar os comandos implementando eles em [classes de comando próprias](https://laravel.com/docs/5.4/artisan#writing-commands), de modo que você pode executá-los diretamente pelo `artisan` a fim de se certificar de que estão funcionando a contento e apenas referenciar eles no *scheduler* do `Console\Kernel`. :wink:

Uma maneira de preencher automaticamente o caminho correto para o *artisan* é usar este *snippet* quando estiver registrando o *task scheduler* de um projeto Laravel no Cron. Basta navegar no terminal até a raiz do projeto e rodar o comando a seguir:

    (crontab -l 2>/dev/null; echo "* * * * * `pwd`/artisan schedule:run >>/dev/null 2>&1") | sort -u - | crontab -

Ele é mágico o bastante para adicionar apenas uma entrada no Cron por mais que você execute o comando mais de uma vez. 😄 

Adicione ele ao arquivo `~/.bash_profile` através de um *alias* e você poderá usar um comando para fazer isso *automagicamente* sempre que precisar. Algo assim:

    alias install_task_scheduler='(crontab -l 2>/dev/null; echo "* * * * * `pwd`/artisan schedule:run >>/dev/null 2>&1") | sort -u - | crontab -'

Deste modo, bastaria rodar o comando `install_task_scheduler` na raiz de um projeto Laravel e pronto, o *task scheduler* deste projeto foi adicionado ao Cron. 😃

**Comment by andretrevas** [comment]
paulofreitas, obrigado pela ajuda.

O log do Laravel constava apenas aquilo (na verdade o que vinha antes não tinha nada a ver com o problema).

De qualquer forma, segui as suas orientações.
O comando crontab -l retornou:

    * * * * * php /var/www/novoCM/artisan schedule:run >> /dev/null 2>&1

Como não estava funcionando (testei apenas executar uma cron mais simples), removi a cron, utilizei o comando que você passou acima e reiniciei o servidor. Ao executar o comando crontab -l novamente, o retorno foi aparentemente o mesmo, porém agora funcionou normal. Não sei exatamente o que aconteceu (talvez algum erro na configuração da cron, visto que a primeira fiz via ajenti), mas agora está resolvido.

Obrigado pela ajuda. A dica que fica é conferir se a cron foi corretamente configurada.
