### ISSUE TITLE
Consulta SQL Laravel

### ISSUE THREAD

**Issue by crazyshock** [laravelbrasil/forum#44]
Galera, possuo atualmente o seguinte SQL:

```php

$result = DB::table('empresas_funcionario')                
                ->leftJoin('empresas', 'empresas.cod_empresa', '=', 'empresas_funcionario.cod_empresa')
                ->leftJoin('sistema_empresas', 'sistema_empresas.cod_sistema_empresa', '=', 'empresas_funcionario.cod_sistema_empresa')
                ->select(
                        array(
                                'empresas_funcionario.*', 
                                'empresas.nome as nome_empresa', 
                                'empresas.cod_marca',
                                'empresas.ativo as ativo_empresa',
                                'sistema_empresas.cod_sistema_empresa',
                                'sistema_empresas.imagem'
                            )
                        )
                ->whereColumn([
                    ['usuario', '=', $user['usuario'] ],
                    ['senha', '=', md5($user['senha']) ] ])
                ->first();
```
o Resultado do SQL acima está sendo isso...

```sql
SELECT 
  `empresas_funcionario`.*,
  `empresas`.`nome` AS `nome_empresa`,
  `empresas`.`cod_marca`,
  `empresas`.`ativo ativo_empresa`,
  `sistema_empresas`.`cod_sistema_empresa`,
  `sistema_empresas`.`imagem` 
FROM
  `empresas_funcionario` 
  LEFT JOIN `empresas` 
    ON `empresas`.`cod_empresa` = `empresas_funcionario`.`cod_empresa` 
  LEFT JOIN `sistema_empresas` 
    ON `sistema_empresas`.`cod_sistema_empresa` = `empresas_funcionario`.`cod_sistema_empresa` 
WHERE (
    `usuario` = `demo` 
    AND `senha` = `fe01ce2a7fbac8fafaed7c982a04e229`
  ) 
LIMIT 1 
```

O problema está sendo aqui:
```sql
`usuario` = `demo` 
    AND `senha` = `fe01ce2a7fbac8fafaed7c982a04e229`
```
Ao invés de envolver a variável entre Aspas ele colocou essa acento agudo.. 
O que faço pra informar que é string ou se fosse inteiro ser apenas o numeral e assim por diante..

**Comment by ezaca** [comment]
Por que você está usando `whereColumn` ao invés de um `where` simples?

O que você quer é algo assim:
```php
[...]
                ->where('usuario', '=', (string)$user['usuario'])
                ->where('senha', '=', md5($user['senha']))
                ->first();
```

### ATENÇÃO!
Você tem outros problemas ali:
1. Você não está dizendo que tabela vêm "usuario" e "senha", e isso pode causar ambiguidades. É melhor dizer a tabela e a coluna, ex: `empresas_funcionario.senha`.
1. MD5 é inseguro para este tipo de hash. Use [password_hash](http://php.net/manual/pt_BR/function.password-hash.php) e [password_verify](http://php.net/manual/pt_BR/function.password-verify.php) para este tipo de tarefa.
1. Incluir as senhas nas buscas pode fazer com que ela vá parar em arquivos de _log_ do Laravel e do MySQL. Consulte o usuário trazendo o campo de senha e compare a senha usando `password_verify`.

Além disso, por que você não está usando Eloquent? Se você precisa mesmo fazer esses joins assim, você pode usar [Local Scopes](https://laravel.com/docs/5.4/eloquent#query-scopes). Mas também pode usar [os relacionamentos](https://laravel.com/docs/5.4/eloquent-relationships) do próprio Eloquent (considerando que você criou os relacionamentos e definiu os campos $hidden):

```php
$model = User::where('usuario', '=', (string)$user['usuario']) // Verifica quem é o usuário.
    ->with(['empresas', 'sistema_empresas']) // Traz os relacionamentos de empresas e sistema_empresas.
    ->first(); // Traz o primeiro registro que encontrar.

if (! $model)
    abort(404, 'Usuário não existe'); // Se o first retornar nulo, nada parecido foi encontrado.

if (! password_verify($user['senha'], $model->senha))
    abort(401, 'Senha incorreta'); // Verifica a senha criada por password_hash.

// Se quiser, ao invés de "abort" pode usar a função auxiliar "abort_if" ou implementar seu código.
// Trabalha com o $model, que é o Eloquent do usuário autenticado.
```

Ah, e também seria bom usar o sistema de [autenticação do Laravel](https://laravel.com/docs/5.4/authentication). Eu tentei fazer um próprio para ter mais liberdade nas regras de negócio e só tive problemas.

**Comment by paulofreitas** [comment]
Como muito bem apontado pelo amigo @ezaca, o problema está em usar o método `whereColumn()` - ele é suposto em ser usado para comparar colunas. Como você está passando os dados, você deve usar o `where()` mesmo. 👍 

Acompanho a recomendação do nobre @ezaca: considere usar o Eloquent! 😃 
Quando tiver um tempinho sobrando, recomendo você acompanhar os casos #35 e #39, onde eu puder explicar detalhadamente porque usar o Eloquent é importante e como ele simplifica a nossa vida. 👍 

**A recomendação de não incluir a senha na própria consulta também é muito importante! Excelente observação, @ezaca!** :wink:

No caso do MD5 estar sendo usado por conta de um sistema legado, talvez você possa se interessar em promover uma migração gradual para o Bcrypt (padrão do Laravel) à medida que os usuários forem se autenticando. Abordei um *approach* disso no tópico #31. 👍 

No mais a brilhante resposta do amigo @ezaca já respondeu tudo! 😁

**Comment by crazyshock** [comment]
Opá muito obrigado @paulofreitas e @ezaca estarei vendo sim e agradeço pela atenção e pelas dicas!
Ainda estou novo no mundo laravel...

**Comment by cagartner** [comment]
@crazyshock só uma coisa que esqueceram de mencionar no mysql '`' funciona como string, não tem problema...

**Comment by cagartner** [comment]
@crazyshock devido ao longo tempo sem resposta estou fechando essa demanda.

**Comment by BalbinoRosas123** [comment]
uuu,,### iii### ,iuu### ### ### ### 

> 

- [`**uuiuiu**`]([url](uiu

           #@@@@@@@@@@uiuuiiuur

))
