### ISSUE TITLE
Trabalhando com Views Blade

### ISSUE THREAD

**Issue by crazyshock** [laravelbrasil/forum#45]
E ai galera tudo bem?

Uma outra dúvida de iniciante por aqui... 
Estou trabalhando com as views do Laravel e até o momento eu montei o meu Layout padrão e assim eu criei outras views por exemplo o Menu que vai ter os links.. 

Até então ficou assim:

```html
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ $titulo or 'Painel Web Gestor de Clientes' }}</title>
      <link rel="stylesheet" type="text/css" href="{{ asset('assets/lib/stroke-7/style.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ asset('assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ asset('assets/lib/theme-switcher/theme-switcher.min.css') }}"/>
      <link type="text/css" href="{{ asset('assets/css/app.css') }}" rel="stylesheet">
   </head>
   <body>
      <nav class="navbar navbar-full navbar-inverse navbar-fixed-top mai-top-header">
         <div class="container">
            <a href="#" class="navbar-brand2">
               <img src="{{ asset('assets/img/logo.png') }}" height="50">
            </a>
            <!--Left Menu-->
            <ul class="nav navbar-nav mai-top-nav">
               <!-- Criar menus futuramente. -->
            </ul>
            <!--Icons Menu-->
            <!-- <ul class="navbar-nav float-lg-right mai-icons-nav">
               <li class="dropdown nav-item mai-messages">
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span class="icon s7-comment"></span></a>
                  <ul class="dropdown-menu">
                     <li>
                        <div class="title">Messages</div>
                        <div class="mai-scroller">
                           <div class="content">
                              <ul>
                                 <li>
                                    <a href="#">
                                       <div class="img"><img src="assets/img/avatars/img1.jpg"></div>
                                       <div class="content"><span class="date">16 Sept</span><span class="name">Victor Jara</span><span class="desc">The song that has been brave, will always be the new song. </span></div>
                                    </a>
                                 </li>                                 
                              </ul>
                           </div>
                        </div>
                        <div class="footer"> <a href="#">View all messages</a></div>
                     </li>
                  </ul>
               </li>
               <li class="dropdown nav-item mai-notifications">
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span class="icon s7-bell"></span><span class="indicator"></span></a>
                  <ul class="dropdown-menu">
                     <li>
                        <div class="title">Notifications</div>
                        <div class="mai-scroller">
                           <div class="content">
                              <ul>
                                 <li>
                                    <a href="#">
                                       <div class="icon"><span class="s7-check"></span></div>
                                       <div class="content"><span class="desc">This is a new message for my dear friend <strong>Rob</strong>.</span><span class="date">10 minutes ago</span></div>
                                    </a>
                                 </li>                                 
                              </ul>
                           </div>
                        </div>
                        <div class="footer"> <a href="#">View all notifications</a></div>
                     </li>
                  </ul>
               </li>               
            </ul> -->
            <!--User Menu-->
            <ul class="nav navbar-nav float-lg-right mai-user-nav">
               <li class="dropdown nav-item">
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle nav-link">
                     <img src="{{ url('uploads/empresas/') }}{{ Auth::user()->cod_sistema_empresa }}/{{ Auth::user()->imagem }}"><span class="user-name">{{ Auth::user()->nome }}</span>
                     <span class="angle-down s7-angle-down"></span>
                  </a>
                  <div role="menu" class="dropdown-menu">
                     <!-- <a href="#" class="dropdown-item"> 
                        <span class="icon s7-home"> </span>My Account
                     </a>
                     <a href="#" class="dropdown-item"> 
                        <span class="icon s7-user"> </span>Profile
                     </a>
                     <a href="#" class="dropdown-item"> 
                        <span class="icon s7-cash"> </span>Billing
                     </a>
                     <a href="#" class="dropdown-item"> 
                        <span class="icon s7-tools"> </span>Settings
                     </a> -->
                     <a href="{{ URL::route('account-sign-out') }}" class="dropdown-item"> 
                        <span class="icon s7-power"> </span>@lang('messages.logout')
                     </a>
                  </div>
               </li>
            </ul>
         </div>
      </nav>
      <div class="mai-wrapper">
         <nav class="navbar mai-sub-header">
            <div class="container">
               <!-- MENU -->
               @include('menu')               
               <!--Search input-->
               <!-- <div class="search">
                  <input type="text" placeholder="Search..." name="q"><span class="s7-search"></span>
               </div> -->
            </div>
         </nav>
         <div class="main-content container">
            @yield('content')
         </div>
      </div>
      <script src="{{ asset('assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
      <script src="{{ asset('assets/lib/tether/js/tether.min.js') }}" type="text/javascript"></script>
      <script src="{{ asset('assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
      <script src="{{ asset('assets/lib/bootstrap/dist/js/bootstrap.min.js') }}" type="text/javascript"></script>
      <script src="{{ asset('assets/js/app.js') }}" type="text/javascript"></script>
      
      <script type="text/javascript">
         $(document).ready(function(){
          //initialize the javascript
          App.init();
         });
         
      </script>
   </body>
</html>
```

A Duvida surgiu no seguinte quesito..  a minha view MENU será gerada dinamicamente conforme o usuario estiver logado, como que vou fazer para quando o include do menu for chamado eu chamar alguma função ou algo que iria aplicar os dados do menu nesta view?

Fiquei perdido nesse ponto.. pq nas minhas rotas eu chamo por exemplo o índex nele sei que tem opção para passar parâmetros, mas esse menu ta dentro dele.. 

Agradeço ajuda antecipadamente.

**Comment by fabiosperotto** [comment]
Você pode utilizar View Composers [1], onde toda vez que a determinada view menu for renderizada, dados são requisitados e disponibilizados para a mesma. Você deve registrá-la com um Service Provider [2] que contenha no método boot() algo como:

`
View::composer('layouts/menu', function($view) //acessando via Facade
{
    $menu = //realize aqui o processamento de que precisar, buscar menus do banco de dados, etc...
    $view->with('menu', $menu); //disponibilizando $menu na view
});
`
Supondo que você tenha colocado o arquivo de view em algo como /resources/views/layouts/menu.blade.php.

Não se esqueça de registrar seu novo service provider no array providers em config/app.php

Refs:
[1] [(https://laravel.com/docs/5.4/views#view-composers](https://laravel.com/docs/5.4/views#view-composers)
[2] (https://laravel.com/docs/5.4/providers)[https://laravel.com/docs/5.4/providers]

**Comment by fabiosperotto** [comment]
Você pode utilizar View Composers [1], onde toda vez que a determinada view menu for renderizada, dados são requisitados e disponibilizados para a mesma. Você pode registrá-la com um Service Provider [2] que contenha no método boot() algo como:

```php
View::composer('layouts/menu', function($view) //acessando via Facade
{
    $menu = //realize aqui o processamento de precisar, buscar menus do banco de dados, etc...
    $view->with('menu', $menu); //disponibilizando $menu na view
});
```

Supondo que você tenha colocado o arquivo de view em algo como /resources/views/layouts/menu.blade.php.

Se criou um novo Service Provider, não se esqueça de registrá-lo no array providers em config/app.php

Refs:
[1] https://laravel.com/docs/5.4/views#view-composers
[2] https://laravel.com/docs/5.4/providers

**Comment by crazyshock** [comment]
@fabiosperotto  mutissimo obrigado pela resposta.
Não querendo abusar porém nao consegui entender a questão do Service Provider.. esse exemplo que você citou View::Composer, eu colocaria ele em que local? Nas rotas?

Unica coisa que eu fiz ate agora foi uma Classe chamada Menu.php e nela coloquei para retornar um Array dos menus que tenho no banco.. Apenas isto.

Além dos links que voce citou teria algo mais didático para mim? 

Agradeço muito pela atenção e pela ajuda já citado.

**Comment by fabiosperotto** [comment]
Tranquilo, tentarei detalhar melhor que repassei.
No caso a view composer não tem a ver com rotas, estamos nos relacionando mais com o service container e boot da aplicação.

Um service provider, como fornecedor de serviços, ficará disponível para a aplicação na sua inicialização (bootstrap do Laravel). Dê uma olhada no conteúdo de config/app.php no array de providers, o Laravel literalmente dá boot em todos eles e quando precisar criar um novo provider para que a aplicação use, basta adicionar lá que o serviço tornar-se-á disponível para toda a aplicação. Com isso, se um service provider ativo estiver "carregando" dados para uma view, não é necessário fazer mais nada em rotas e controllers. Basta informar dentro do método boot() o view composer que quando o framework der boot em todos os serviços, aqueles dados serão disponibilizados para a view. 

Para tentar ser mais didático, segue o código:

1. Criado um service provider via comando:
`php artisan make:provider MenuProvider`

2. Siga para app/Providers e abra o MenuProvider.php, lá informe algo como:

```php
<?php

namespace App\Providers;

use App\Menu;
use Illuminate\Support\ServiceProvider;

class MenuProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {             
        View::composer('layouts/menu', function($view) //acessando via Facade
        {
            $menu = Menu::all();
            $view->with('menu', $menu); //disponibilizando $menu na view
        });            
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

3. Em config/app.php, adicione no final do array provider: App\Providers\MenuProvider::class,

Pronto, agora no menu.blade.php você já tens acesso a $menu preenchido pelo novo provider..

**Comment by crazyshock** [comment]
@fabiosperotto brother... muitooo obrigado!!! Agora consegui entender como que funciona o Provider... 
Ja vou fazer os meus testes aqui.. obrigado novamente pela paciência!!!!

**Comment by paulofreitas** [comment]
Só pra complementar a excelente resposta do @fabiosperotto, note que você também pode declarar os *view composers* em classes próprias, como demonstrado na documentação através da classe `ProfileComposer`. 👍 

Isso ajuda a melhor organizar o código consideravelmente, permitindo ainda usar o *container* para injetar dependências no construtor. É uma excelente forma de aderir ao princípio da responsabilidade única (SRP). Particularmente é uma opção que adoto na grande maioria das vezes.

No caso do *service provider*, que também precisará ser usado, você pode centralizar todos *view composers* e *view creators* num único *provider*, o qual você poderia chamar de `ViewServiceProvider`, podendo separar o registro dos *composers* em métodos separados para manter o código limpo. :wink:

**Comment by crazyshock** [comment]
@paulofreitas Opá, que show. Agradeço muito a sua dica.
E como comentei com o Fabio, você teria algum artigo ou algo que exemplifica isso na prática?

Agradeço novamente a ajuda!!

**Comment by omarkdev** [comment]
@crazyshock Na própia documentação do Laravel tem ambos os exemplos: [https://laravel.com/docs/5.4/views#view-composers](https://laravel.com/docs/5.4/views#view-composers); Você também pode dar uma olhada nesse pequeno tutorial do scotch.io: [https://scotch.io/tutorials/sharing-data-between-views-using-laravel-view-composers](https://scotch.io/tutorials/sharing-data-between-views-using-laravel-view-composers)

**Comment by DOUGLASMD1** [comment]
Dando uma olhada na questão, me surgiu uma duvida:

Tenho um layout, nele utilizo o View Composers, porém so para receber dados. Gostaria de saber como eu posso passar um parâmetro para o View Composers para me retorna um dado especifico ?
