### ISSUE TITLE
Criar Eloquent Relation Personalizado

### ISSUE THREAD

**Issue by rscorrea** [laravelbrasil/forum#46]
Descrição Geral do Problema

## Dúvida
Pessoal, tenho 2 models. Model A e model B.

```
class A extends Model {
    public function modelB()
    {
        return $this->belongsToMany( 'App\B' );
    }
}

class B extends Model {
    public function modelA()
    {
        return $this->belongsToMany( 'App\A' );
    }
}
```

Gostaria de retornar todos os registro do Model B caso não haja nenhum registro especificado na tabela A_B da relação.

Exemplo: Tabela A_B está vazia... Então, quando eu fizer A->modelB(); retorna toda a tabela B

Caso, tabela A_B contenha alguma relação, A->modelB() retorna só o que estiver nessa tabela

Deu pra entender?
---

**Comment by ezaca** [comment]
Não sei se eu peguei a ideia. Se for como eu entendi, seria meio complexo e quase sem uso implementar isso no Laravel. Por que você precisaria de algo assim?

Mesmo assim, não teria como você testar se a relação veio com 0 elementos ou mais e, a partir dali, ir para o segundo caso?

Um código não testado, só pra repassar a ideia:
```php
$tableA = TableA::with('tableB')->find(1); // Pega um item da tabela A com o relacionamento pra B por A_B (hasManyThrough deve resolver).
if ($tableA->tableB->count() > 0) // Se tiver registros B no relacionamento A_B
    $tablesB = $tableA->tableB; // então: pega eles.
else
    $tablesB = TableB::all(); // senão: pega todos da tabela B.
```

**Comment by natanaelphp** [comment]
Isso me parece uma regra de negócio específica da sua aplicação. 
Acredito q o ideal seria você implementar um código, como o que o @ezaca mostrou acima, em uma classe sua de repositório ou serviço.

**Comment by omarkdev** [comment]
@rscorrea estou finalizado esta issue devido ao longo tempo sem respostas.
