### ISSUE TITLE
Como fazer um SSO usando Laravel + Firebase + Dingo

### ISSUE THREAD

**Issue by claudiobastos** [laravelbrasil/forum#53]
Eu tenho vários sistemas webs e vários clientes mobile.
Gostaria de ter um #sso (#singlesignon) usando Laravel + Firebase que me permitisse integrá-los de maneira segura e gerenciável, para acessar APIs internas.

## Problema Encontrado
Não encontrei uma referência/tutorial/artigo integral que me ajudasse a desenvolver a solução completa e ainda não domino completamente os conceitos envolvidos.
Suponho que parte do problema envolva Passport que me ajudaria com alguma parte do OAuth2 (embora não esteja certo disso).
Também penso que devo usar o Dingo como solução para estruturar minhas #apis, mas também não sei como integrá-lo dentro da arquitetura geral.

---

## Abordagem
Já cheguei a usar autenticação no Laravel usando Firebase usando um pacote [falta completar](url).

Tenho lido a respeido do OAuth2 para dominar os conceitos necessários.
Eu fiz o tutorial da documentação oficial do Passport, e o coloquei _funcionando_ numa aplicação Laravel (5.4).
Vi também que é possível cadastrar clientes, mas ainda não está claro a gerência para meus vários sistemas de forma que cada cliente só possa recuperar um conjunto de informações.

Gostaria de alguma orientação em que direção avançar.

---

## Atualização 1

---

**Comment by zabaala** [comment]
@claudiobastos, ainda aceita respostas?

Estou testando esse pacote aqui: https://github.com/jasny/sso. Sem mistérios. Só ler e wiki e botar pra rodar.

**Comment by claudiobastos** [comment]
Valeu, vou dar uma olhada

**Comment by zabaala** [comment]
@claudiobastos mexendo nas minhas coisas, encontrei esse diagrama aqui. O criei quando estava com a idéia inicial do SSO borbulhando na cabeça.

![jrdf8l5nis7qsx5s-5f73d](https://user-images.githubusercontent.com/4934492/28491911-8bf45c2e-6ecf-11e7-8bfb-3172affddea5.png)

Um detalhe ou outro mudou, mas ele representa bem o contexto atual dos testes que estou fazendo. Espero que te ajude em algo. 

Abraço.
