### ISSUE TITLE
Subdomínio

### ISSUE THREAD

**Issue by rogerio-pereira** [laravelbrasil/forum#54]
Pessoal boa noite, acabei de desenvolver minha primeira aplicação em Laravel, e estou com algumas dúvidas referente a subdominos...

# Situação
Fiz o upload dos arquivos para o servidor, rodei as migrations, alterei o arquivo .env

Quando rodo o sistema roda certinho... quando vou acessar um subdomínio, se acesso via https, recebo a mensagem
Error: 503 - Service Unavailable
Domínio temporariamente indisponível

se acesso via http, recebo a mensagem
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, email@dominio.com.br and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Na minha máquina roda certinho

# Minhas Duvidas
Preciso criar um subdomínio na hospedagem, ou o proprio laravel ja cuida disso (eu criei)
Em contato com o pessoal da hospedagem me informaram que poderia ser devido ao DNS do domínio ter sido alterado hoje, que pode ser que nao propagou

**Comment by petrenkorf** [comment]
Você precisa criar um subdomínio na hospedagem e fazer os ajustes necessários nas rotas da sua aplicação.

O Laravel em si possui um mecanismo para tratar subdomínios, mas apenas para interpretar sua URL, então você precisa configurar manualmente o DNS e o servidor web para suportar esse tipo de aplicação.

**Comment by rogerio-pereira** [comment]
estou tendo um problema...
localmente está funcionando... no meu arquivo de virtualhost o subdomínio esta apontando para a pasta public.... mas quando eu crio o subdomínio na hospedagem ele cria uma pasta dentro de public... acredito que esse seja meu problema, não estar direcionando para a public e sim para a public/subdomain...

Criei um link simbolico mas nao consegui tbm

**Comment by cagartner** [comment]
@rogerio-pereira, você nao deve criar um subdonimio via hospedagem, apenas cria um CNAME no teu gerenciador de DNS para o endereço do site normal, exemplo:

Exemplo:  CNAME `subdomain.domain.com` `domain.com.`

O que vai acontecer é que toda a requisição de `subdomain.domain.com` vai para domain.com onde está seu Laravel e lá será feito a verificação do subdomínio.

Você provavelmente está usando um Cpanel da vida, correto? Nesse caso os subdomínios deles são para aplicações diferentes.

Espero que tenha ajudado.

**Comment by petrenkorf** [comment]
Só complementando a resposta do @cagartner 

Nesse caso do CPanel, se você tiver acesso ao painel ou shell, você pode remover a pasta que foi criada para o subdomínio e criar um link simbólico para a pasta da sua aplicação. Particularmente eu não gosto dessa opção para aplicações médias ou grandes, mas para soluções pequenas acaba funcionando.

**Comment by rogerio-pereira** [comment]
@cagartner tentei fazer isso mas nao deu certo... leva algum tempo para efetivar a alteração de DNS

@petrisrf eu crio o link para a pasta raiz do laravel ou para a public?

**Comment by petrenkorf** [comment]
@rogerio-pereira Para a pasta public. Sobre a demora de propagação do DNS, você pode forçar o apontamento local para o servidor que você vai utilizar, já que a "consulta" de DNS local tem prioridade, só não esquecer de remover depois :)

**Comment by rogerio-pereira** [comment]
@petrisrf ja tentei fazer o link para a pasta public nao deu certo... continua me retornando erro 503

Error: 503 - Service Unavailable
Domínio temporariamente indisponível

**Comment by rogerio-pereira** [comment]
Engraçado que eu apaguei o subdominio, apaguei o link, e continua me retornando erro 503, so nao apaguei o cname

**Comment by cagartner** [comment]
@rogerio-pereira Responda essa questão:

Quando você entra no domínio principal ele funciona?

Caso a resposta seja sim, exclua todos os subdomínios no cpanel, e crie o CNAME do subdomínio novamente, após criado, entre no navegador no subdomínio e **DEVERÁ** cair no site principal.

Tente criar um sudominio fake para teste como `exemplo.dominio.com.br`

Seria bom também você conseguir acessos aos logs do servidor, porque esse erro 503 deve ter gerado o log.

Abraços!

**Comment by rogerio-pereira** [comment]
@cagartner 
quando removo do routes o subdominio ele funciona
quando adiciono 
Route::get('/', function(){
    return 'Site';
});
tbm vejo escrito Site

Exclusao de subdominios tbm ja fiz
Criar um subdomínio fake usando o cname acontece a mesma coisa (Erro 503)
sobre os logs vou ver com a hospedagem e posto aqui

**Comment by rogerio-pereira** [comment]
Conseguiiii
Faltava o certificado SSL para o domínio
Muito obrigado @petrisrf @cagartner 
como eu marco como solucionado?

**Comment by rogerio-pereira** [comment]
Conseguii
Muito obrigado @cagartner @petrisrf 
Estava faltando configurar o certificado SSL no domínio
