### ISSUE TITLE
Página de erro diferente em um mesmo sistema (resources/errors/*.php)

### ISSUE THREAD

**Issue by luscas** [laravelbrasil/forum#64]
E aí, gostaria de pedir à ajuda de vocês..
**É o seguinte**:
Eu tô fazendo um site no qual o painel/site são juntos.

_Eu sei como setar a página de erro do site (em resources/errors/*.php)_, **mas como eu faço com que a página de erro do site seja diferente da página do erro do painel?**

**Solução** - @paulofreitas 
https://github.com/laravelbrasil/forum/issues/64#issuecomment-298686030

**Comment by joaosalless** [comment]
Uma alternativa seria incluir uma view parcial de acordo com o primeiro segmento da url solicitada.

Exemplo para a página de erros do tipo 404, supondo que você acessa o painel através da url "/admin":

```blade
@if(request()->segment(1) === 'admin')
    @include('admin.errors.404')
@else
    @include('site.errors.404')
@endif
```

Ou, você pode usar a mesma lógica da função `request()->segment(1)` para aplicar um estilo css diferente em um layout para as páginas de erro. E então você estende esse layout em todas as páginas de erro.

**Comment by deleugpn** [comment]
Sobrescrever o método `renderHttpException()` em App\Exception\Handler é uma ótima opção pra isso.

**Comment by paulofreitas** [comment]
Tratar isso no `App\Exception\Handler` é de fato o caminho mais adequado para esta situação, já que este arquivo existe exatamente para ser modificado conforme a necessidade. 👍 

Em geral isso pode ser feito sobrecarregando (modificando) o método `render()`, neste caso em específico de exceções HTTP você pode estar sobrecarregando o método `renderHttpException()` conforme apontado pelo @deleugpn: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L185

Isso pode ser feito da seguinte forma:

```php
<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Auth\AuthenticationException;
use Symfony\Component\HttpKernel\Exception\HttpException; // linha adicionada
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /* ... */

    /**
     * Render the given HttpException.
     *
     * @param  \Symfony\Component\HttpKernel\Exception\HttpException  $e
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function renderHttpException(HttpException $e)
    {
        $status = $e->getStatusCode();

        view()->replaceNamespace('errors', [
            resource_path(request()->is('admin/*') ? 'views/errors/admin' : 'views/errors')
        ]);

        if (view()->exists("errors::{$status}")) {
            return response()->view(
                "errors::{$status}",
                ['exception' => $e],
                $status,
                $e->getHeaders()
            );
        }

        return parent::renderHttpException($e);
    }

    /* ... */
}
```

Neste exemplo as *views* de erros do site ficam no diretório `resources/views/errors` e as *views* de erros do painel administrativo ficam em `resources/views/errors/admin`. :wink:

**Comment by luscas** [comment]
Obrigado pela à atenção. thanks @paulofreitas!
