### ISSUE TITLE
Salvar múltiplos arquivos

### ISSUE THREAD

**Issue by marceloamp2** [laravelbrasil/forum#65]
O código abaixo cria uma modalidade e salva um arquivo para essa modalidade. Como poderia fazer para salvar multiplos arquivos? Coloquei name:"image[]" e multiple no input, minha dúvida é como fazer no método.

## Problema Encontrado
    public function store(Request $request)
    {
        $input = $request->all();
        $modality = new Modality($input);
        $modality->save();

        $image = $request->image;
        $imageName = $image->getClientOriginalName();
        $image->name = $imageName;
        $image = new Image();
        $image->imageable_id = $modality->id;
        $image->imageable_type = Modality::class;
        $path = $request->file('image')->storeAs('public', $imageName);
        $image->save();
    }

---

## Abordagem
Você já tentou alguma solução, descreva aqui.

---

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by cagartner** [comment]
No caso quando você adiciona o [] no input você receberá um array no Request.

```php
public function store(Request $request)
{
    $input = $request->all();
    $modality = new Modality($input);
    $modality->save();

    $images = $request->image;
    
    foreach ($images as $image) {
        $imageName = $image->getClientOriginalName();
        
        $imageBd = new Image();
        $imageBd->name = $imageName;
        $imageBd->imageable_id = $modality->id;
        $imageBd->imageable_type = Modality::class;
        $path = $request->file('image')->storeAs('public', $imageName);
        $imageBd->save();
    }

}
```
