### ISSUE TITLE
Problemas com PHP Artisan Migrate

### ISSUE THREAD

**Issue by dieggop** [laravelbrasil/forum#66]
Tentei rodar o Php Artisan Migrate e acusou este problema, nunca me ocorreu ele antes....

## Problema Encontrado
Galera, bom dia.
Vocês já tiveram este problema ao rodar o php artisan migrate?

Q:\unita>php artisan migrate

[Illuminate\Database\QueryException]
iconv_strpos(): Detected an illegal character in input string (SQL: select * from information_schema.tables where table_schema = baseunita and table_name = migrations)

[ErrorException]
iconv_strpos(): Detected an illegal character in input string

---

## Abordagem
Tentei limpar a base de dados por completa e não rolou!

---

## Atualização 1

---

## Solução
Galerinha, consegui solucionar... 
Eu mudei de terminal, não entendi bem mas funcionou! Eu abri o Putty e conectei com o infeliz no server e rodei o comando. Funcionou!!! 
Antes estava usando o terminal do PhpStorm!

**Comment by cagartner** [comment]
A principio me parece um problema de encode da tabela, você mudou o encode da conexão ou do banco de dados?

As vezes o banco pode estar em iso e a tabela em utf8, ou a tabela em iso e a conexão em utf8.

Espero ter ajudado.

**Comment by dieggop** [comment]
A bronca é ... já havia rodado outras vezes hehehehe!!! Hoje foi que veio frescar!!!

**Comment by cagartner** [comment]
Hm.. o banco é compartilhado? Ou está no seu local?

**Comment by dieggop** [comment]
Local! 
Consegui fazer funcionar, mudei de terminal... acredita nisso?

**Comment by cagartner** [comment]
Show! Vou marcar como resolvido :)
