### ISSUE TITLE
Modelagem de sistema

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#67]
Pessoal, bom dia!

Estou desenvolvendo um sistema para a farmácia básica do município onde moro e, nele, tenho a necessidade de armazenar dados de pessoas físicas (paciente, médico, farmacêutico) e pessoas jurídicas (fornecedor, laboratório, empresa e filial). Para modelar, pensei na abordagem de Pessoa extendendo para Pessoa Física e Pessoa Jurídica, com cada forma sendo composta por um registro de pessoa e adicionando os dados específicos de cada situação. Alguma outra sugestão? Confesso que sempre me perco nessas questões...

**Comment by cagartner** [comment]
Opa @maykonmendel 

É uma dúvida bem recorrente aqui na comunidade, tenta dar uma lida na discussão: https://github.com/laravelbrasil/forum/issues/26

Nela possui um problema semelhante que foi abordado algumas soluções.

Abraços!

**Comment by maykonmendel** [comment]
Opa @cagartner 

Agradeço pela contribuição. Vou ler (não tinha encontrado ao pesquisar outras Issues).

Abraços!

**Comment by cagartner** [comment]
Se ficar alguma dúvida pode comentar aqui que ficaremos feliz em ajudar :)

**Comment by maykonmendel** [comment]
Pelo post indicado, eu estou no caminho certo, pois assim estou separando as entidades do sistema com suas especialidades. Aumenta um pouco de código, mas fica mais fácil de compreender o sistema depois.

**Comment by maykonmendel** [comment]
@cagartner 
Pensei em criar a classe Pessoa (id, nome, razao_apelido, documento, nascimento_fundacao) e criar, por exemplo a classe Paciente (id, id_pessoa, rg, orgao_expedidor, sexo, estado_civil, cartao_nacional, numero_prontuario). Essa abordagem eu encontrei no repositório do LaraERP. Estaria correta?

Ou então, criar a classe Pessoa (id, tipo_pessoa, situacao, observacao, data_cadastro) e as classes PessoaFisica (id, id_pessoa, nome, cpf, rg ...) e PessoaJuridica (id, id_pessoa, razao_social, cnpj, ...) ?

**Comment by IgorDePaula** [comment]
Onde eu trabalho tenho um sistema onde tenho esses 2 tipos de login: pessoa fisica e juridica.

Como faço, tenho uma unica tabela de users, onde nessa tabela tenho um campo que determina o papel, o tipo de usuario, onde for um usuario de pessoa juridica faço uma atribuicao dele a (no caso) instituicao (empresa), pois essa empresa pode ter varios contatos vinculados a ela que podem realizar as mesmas tarefas. 

Se  uma pessoa for desligada de la, o outro contato dessa empresa continua o trabalho com seu login individual. 

Laravel ter permite fazer essa modelagem de diversas maneiras, precisa ver com mais detalhe essa regra de negocio, como cada um vai fazer login, principalmente.

**Comment by maykonmendel** [comment]
@IgorDePaula 

Nesse caso a única pessoa que irá operar o sistema será o farmacêutico. A questão é como modelar o sistema de forma que fique com os dados normalizados e na convenção da orientação a objetos. A questão usuário/tipo eu já tenho noção como fazer, a questão são as pessoas mesmo.

**Comment by IgorDePaula** [comment]
Mas entao, vc tem uma tabela de usuario, uma de empresa, vc pode fazer um
relacionamento N:M entre esses quando houver, e o login continua normal.

Em 4 de maio de 2017 14:07, maykonmendel <notifications@github.com>
escreveu:
