### ISSUE TITLE
Mensagem de Login Inválido

### ISSUE THREAD

**Issue by ghost** [laravelbrasil/forum#70]
Como eu posso fazer para que me retorne a mensagem de login inválido? Tenho já no meu Controller, mas coloquei apenas para ele retornar para a página de login... em sistemas passados usando PDO, eu abria uma session e ao retornar para a página de login e visse essa session, ele mostraria, e após isso ele "matava". No Laravel 5.4 tem alguma forma mais prática para isso? Mostrar uma DIV com o Alert?

**Comment by maykonmendel** [comment]
Bibliotecas como Pnotify.js ou Verify.Notify.js resolveriam seu problema.

Pnotify ->https://github.com/sciactive/pnotify
Verify.Notify.js -> http://verifyjs.jpillora.com/

**Comment by cagartner** [comment]
@renanmiranda 

Você pode criar um arquivo do tipo "partial" `errors.blade.php` e colocar ele como include no header do seu layout: `@include('errors')`

Dentro do seu arquivo errors.blade.php você coloca o seguinte conteúdo:
```php 
// Errors de validação
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

// Mensagens informativas
@if (session('info'))
    <div class="alert alert-info">
        {{ session('info') }}
    </div>
@endif

// Mensagem de avisos
@if (session('warning'))
    <div class="alert alert-warning">
        {{ session('warning') }}
    </div>
@endif

// Mensagem de error
@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif
```

No seu retorno do controller você vai fazer retornar assim:

```php
// Retorno informativos
return back()->withInput()->withInfo("Aviso informativo");

// Retorno de avisos
return back()->withInput()->withWarning("Aviso de warning");

// Retorno de erros
return back()->withInput()->withError("Erro de aplicação");
```

**Comment by ghost** [comment]
@cagartner, utilizei a forma que vc indicou, ficou bem melhor, e ainda tenho autonomia para trabalhar com o restante das notificações. Obrigado

**Comment by cagartner** [comment]
Legal, estou fechando essa issue visto que foi resolvido :)
