### ISSUE TITLE
[Dúvida] Template Gentelella

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#71]
Pessoal, bom dia!

Estou querendo utilizar o template Gentelella no meu sistema que estou desenvolvendo. Existem alguns repositórios com esse template já incluso, porém são carregados de erros e demandaria muito mais tempo só para corrigir. Então, gostaria de saber se alguém já utilizou e, se sim, se para usar foi mesma maneira como se fosse com o bootstrap ou qualquer outro css?

**Comment by fhpimenta** [comment]
Cara, eu uso o template [AdminLTE2](https://almsaeedstudio.com/themes/AdminLTE/index2.html), e é bem tranquilo de usar. Ele é baseado no bootstrap, então as mesmas classes do bootstrap encontram-se lá.
No caso do Gentelella, ele também é baseado em bootstrap, então vai seguir o mesmo princípio.

**Comment by flavianohonorato** [comment]
Também uso o AdminLTE, inclusive tem 2 ótimos pacotes caso você não queira ficar importando os assets na mão.
`https://github.com/acacha/adminlte-laravel`
`https://github.com/jeroennoten/Laravel-AdminLTE`

**Comment by maykonmendel** [comment]
@fhpimenta e @flavianohonorato 

Agradeço a colaboração de vocês. Vou ver qual dos dois usar, pois gosto de ambos os templates. Importar os assets na mão é enjoado mas considero tranquilo de fazer.

**Comment by hernandev** [comment]
```
<humor>
```

Eu uso esse tema aqui:

http://code.divshot.com/geo-bootstrap/

```
</humor>
```

Temas não vão mudar muito, se tu usar a base e ir customizando as suas necessidades. se  tu usa bootstrap é questão de adaptação.

o Laravel já traz por padrão um setup com o boostrap sass, tu pode implementar as mudanças dos temas em cima disso ou partir do zero.

**Comment by LucasASilva-Dev** [comment]
Cara... Eu usei o Gentelella daqui: https://github.com/Labs64/laravel-boilerplate... Deu muita dor de cabeça pra separar tudo e fazer funcionar... Mas o tempo gasto nisso foi menor do que iniciar do 0 copiando e colando cada item e etc... Então eu aconselho a usar :)

**Comment by maykonmendel** [comment]
@lordobob 

Vou ver qual a melhor opção se aplica ao meu projeto. Valeu.

**Comment by maykonmendel** [comment]
@lordobob 

Quando você fala em "separar tudo", você se refere a retirar os arquivos css de dentro da pasta gentelella e colocar na pasta assets?
