### ISSUE TITLE
Merge PDF Amazon S3

### ISSUE THREAD

**Issue by dalcero** [laravelbrasil/forum#73]
## Problema Encontrado
Olá pessoal. 
Estou precisando realizar a união de vários PDF's que estão salvos no Amazon S3.

---

## Abordagem
Estava utilizando o pacote [https://github.com/hanneskod/libmergepdf](url) para o Merge, quando os arquivos estavam sendo salvos localmente estava suprindo as necessidades. 

Agora que estamos salvando no S3 este pacote não está funcionando, pois eu preciso passar a URL completa e não somente o Path como eu fazia antes.

Quando tento adicionar o arquivo.

$pdf->addFromFile('url_completa'), ocorre o erro..

Exception in Merger.php line 82:
'http://XXXXXXX.1f67d2fd7e760f157b264e72c83f3fdc.pdf' is not a valid file

---

## Solução
A solução abaixo citada resolveu o problema..

**Comment by Maykonn** [comment]
@dalcero Usar o addRaw() dessa lib pode funcionar. 
Use cURL ou file_get_contents() para obter o conteúdo do pdf como string e então passe para o addRaw().
