### ISSUE TITLE
Pasta padrão das Models

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#76]
Pessoal, boa tarde!

Eu gostaria de criar uma pasta dentro de App chamada Models e ali colocar todas as models. Como mudar a configuração padrão do Laravel?

**Comment by deleugpn** [comment]
Sobrescreve o comando que gera modelos.

```
[01:19 PM]-[root@php7]-[/var/www/tests/binary-column]
# php artisan make:command MyModelMakeCommand
Console command created successfully.
```

Registra seu comando personalizado em `App\Console\Kernel`

```
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        \App\Console\Commands\MyModelMakeCommand::class
    ];
```

Na classe do seu comando personalizado, extenda o comando padrão `ModelMakeCommand` e sobrescreva os métodos `getPath()` e `rootNamespace()`

```
<?php

namespace App\Console\Commands;

use Illuminate\Foundation\Console\ModelMakeCommand;

class MyModelMakeCommand extends ModelMakeCommand
{
    protected function getPath($name)
    {
        $name = str_replace_first($this->rootNamespace(), '', $name);

        return $this->laravel['path'].'/Models/'.str_replace('\\', '/', $name).'.php';
    }

    /**
     * Get the root namespace for the class.
     *
     * @return string
     */
    protected function rootNamespace()
    {
        return $this->laravel->getNamespace() . 'Models';
    }

}
```

Depois disso, toda vez que você usar `php artisan make:model MyModel`, o arquivo será escrito dentro de `app/models/` com o `namespace App\Models;`

**Comment by flavianohonorato** [comment]
Nesse caso só criar Normalmente​e usar namespace.

**Comment by flavianohonorato** [comment]
Ops, agora que vi que já tinham respondido, estou pelo celular e não consegui editar ou apagar, alguém pode fazer isso?

**Comment by maykonmendel** [comment]
@deleugpn 

Testei e não funcionou. Qual a versão do seu Laravel?

**Comment by deleugpn** [comment]
5.4.23

**Comment by maykonmendel** [comment]
Vou tentar outros métodos. Valeu pela colaboração.

**Comment by deleugpn** [comment]
Se você explicar o que que não funcionou, qual a mensagem de erro e qual versão do Laravel você precisa, talvez eu possa te ajudar. O importante na explicação que dei não é bem o código exato (apesar de funcionar no 5.4), mas o conceito. Você pode mover todos os seus `models` para a pasta `App/Models` manualmente e simplesmente usar o `namespace` corretamente. Mas quando você diz

> Como mudar a configuração padrão do Laravel?

imaginei que estivesse se referindo ao gerador de modelo, que é um comando `artisan` que pode ser sobrescrito.

**Comment by maykonmendel** [comment]
Acho que me expressei mal. Eu gostaria que quando fosse rodado o comando, ele gerasse direto dentro da nova pasta.

**Comment by deleugpn** [comment]
Então o caminho é o que expliquei na primeira resposta mesmo. Extende o comando `ModelMakeCommand`  e sobrescreve os métodos que definem a `pasta` e `namespace`.

**Comment by maykonmendel** [comment]
Vou tentar de novo. Percebi que alguns arquivos foram excluídos pela IDE (não me pergunte por que) e talvez o que seja necessário a esses comandos tenham ido juntos. Se der certo, informo aqui.

**Comment by maykonmendel** [comment]
@deleugpn 

Funcionou. Agradeço pela colaboração.

**Comment by JoseCage** [comment]
Opa @deleugpn valeu a ajuda com o código acima.. NUnca pensei na alternativa de sobrescrever o comando e normalmente rodo sempre **`artisan make:model Models/ModelName`**.. Agora o caminho sempre curto.. :+1: :package:
