### ISSUE TITLE
Local de salvamento dos arquivos de estilo

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#79]
Pessoal, boa noite.

Me surgiu uma dúvida aqui. Quando trabalhei pela primeira vez com laravel, me recordo que meu parceiro de desenvolvimento colocou arquivos como css, img e js na pasta public. O certo seria na public ou em assets?

**Comment by cagartner** [comment]
@maykonmendel  css, img e js compilados na pasta public, scss, arquivos .vue, JS em desenvolvimento em resources/assets.

Ai você usa o Laravel Mix: https://laravel.com/docs/5.4/mix para compilar esses caras e colocar na public.

**Comment by maykonmendel** [comment]
@cagartner 

Perfeito! Vou testar e assim que puder dou um feedback. Só mais uma dúvida: instalar os pacotes manualmente ou utilizar o bower, por exemplo?

**Comment by omarkdev** [comment]
Você pode fazer das duas maneiras, mas recomendo instalar os pacotes usando bower, npm ou outros, já que você consegue importá-los, assim não fica com muitos arquivos "inúteis" no repositório.
