### ISSUE TITLE
IDE utilizada com o Laravel

### ISSUE THREAD

**Issue by marabesi** [laravelbrasil/forum#8]
## Descrição Geral do Problema

Beleza galera? Recentemente eu venho testando várias IDE's e editores de texto para desenvolver com o Laravel/HTML/CSS/JS. 

E hoje optei por continuar com o PHPStorm por alguns motivos. O primeiro deles é o auto complete que a ferramenta possui, de longe é a melhor(mesmo quando o retorno não é explícito através dos blocos de comentários). 

O segundo é a facilidade em navegar pelos namespaces apenas segurando o CTRL/CMD, ou seja, eu não preciso ficar caaçando arquivo para abri-lo.

O terceiro é a integração com bancos de dados pela IDE, eu não preciso usar nenhum outro programa para fazer acesso a base (Esses três são os mais gritantes, mas existem outros pequenos motivos).

## Problema Encontrado

Bom, até hoje não encontrei nenhuma outra IDE tirando o netbeans que faça algo parecido com o PHPStorm. 

O que percebi é que quando escolho um editor de texto é necessário instalar 2000 plugins para chegar algo "parecido" com uma IDE.

Eu gostaria de saber qual é o setup utilizado por cada um de vocês e qual o motivo, se é leveza, features ou facilidade de uso etc.

## Abordagem

IDE's e editores que já testei :

- Netbeans (é bem parecido porém é mais pesado do que o PHPStorm)
- sublime (Precisei instalar plugins)
- atom (Precisei instalar plugins)
- visual code (Precisei instalar plugins)
- VIM (Precisei instalar plugins)

---

**Comment by giordanolima** [comment]
Cara eu usei o NetBeans a vida toda pelos mesmos motivos que tu descreveu...
Nunca cheguei a usar o PHPStorm pq acho que não justifica investir tanto dinheiro numa IDE, já que tem o NetBeans free... Então não tenho comparar em relação a esses dois onde cada um é melho/pior que o outro...
O que eu vejo é que existe um certe preconceito da galera com o NB só pq é a mesma IDE que os javeiros usam, mas até hoje me atendeu mais do que bem e nunca me senti com necessidade de desembolsar uma pequena fortuna pelo PHPStorm...

Aaah sobre o NB ser pesado, eu já ouvi MUITA gente (muita gente mesmo!) reclamando do PHPStorm justamente por ele ser pesado... Rodando o NB em Linux nunca tive problemas com desempenho...

Um abraço!

**Comment by marlon-david** [comment]
Uso SublimeText, com o plugin SublimeCodeIntel para autocomplete.
Os principais motivos são a leveza e praticidade (os atalhos de teclado são os melhores). O que eu acho mais essencial é o recurso de multi-cursor, se não tiver isso, nem chego a experimentar o editor ou IDE. Sinto falta de alguns recursos como integração com banco/git, mas não chega a ser um problema tão grande.
Sem ser o sublime, a IDE que consegui usar por mais tempo é o PHPStorm. De vez em quando abro o NetBeans, mas sem perceber acabo clicando no ícone do SublimeText por estar mais acostumado

**Comment by flyingluscas** [comment]
Uso o Sublime a um bom tempo já, tentei usar Atom, NetBeans, PHPStorm entre outros, mas na minha experiencia o Sublime sempre se sobre saiu em relação aos outros editores e IDEs que testei, principalmente na questão do desempenho.

Mas uma coisa é verdade, o Sublime puro é um pouco complicado de usar, mas ele tem muitos plugins que facilitam bastante a minha vida, principalmente quando se trata de PHP, segue alguns dos principais plugins que uso nele.

- AdvancedNewFile
- AutoFileName
- CodeComplice
- DocBlockr
- EditorConfig
- Emmet
- Laravel 5 Artisan
- Laravel Blade Highlighter
- Local History
- Material Theme
- PHP Companion
- PHP Getters and Setters
- SideBarEnhancements
- SyncSettings (o xeroso, todo mundo que usa Sublime deveria conhecer esse plugin)

E mesmo com tudo isso de plugin instalado, ele não deixa de ter um bom desempenho durante o desenvolvimento (pelo menos comigo hehehe), e fora os plugins, existem outras customizações como key bindings e snippets que me ajudam bastante também.

Cheguei a um ponto com o Sublime que não me vejo hoje precisando de um outro editor ou IDE, mas claro, se aparacer algo que atenda melhor as minhas necessidades e com o mesmo desempenho ou melhor, posso considerar a troca :)

> Essa questão do namespace, nas últimas versões do Sublime, basta passar o mouse em cima do namespace e ele te mostra os arquivos onde ele foi definido, o mesmo vale para classes, funções, variáveis e etc.

**Comment by wilcorrea** [comment]
Uso PHPStorm e preciso desativar alguns plugins para começar a usar. Uso nele o terminal, o plugin de banco de dados e o rest client, além de ativar a integração com o composer ; )

**Comment by rpaggi** [comment]
Eu estava usando o Sublime antes, agora consegui uma licença de 1 ano do PHPStorm e atualmente estou testando ele.

**Comment by cristiano-pacheco** [comment]
Uso o PHPStorm, Ide perfeita para minhas necessidades.

Tenho a integração nativa com banco de dados, utilizo alguns plugins para integrar com docker, vagrant, phpunit.

ótima ferramenta para debugar, no frontend me ajuda bastante com javascript(es6), sass, less, vue e seja la o que for que eu precisar! 

enfim, adoro esta ide e pra mim vale muito a pena pagar a licença.

**Comment by developermiranda** [comment]
Usar PHPStorm, é tipo caminho sem volta. Testei várias IDEs e editores, mas não obtive a mesma experiência.

**Comment by paulofreitas** [comment]
Uso Sublime Text 3 e Visual Studio Code, ambos por motivos de leveza e personalização. :+1:

Leveza principalmente. Pra viver com lags e freezes já bastam os navegadores que devoram a memória toda da máquina... Nunca me foi coerente precisar de +4 GB de RAM para codificar. Tenho um Macbook Pro mid-2012 com seu Core i5 de 2.5GHz e 4GB RAM DDR3 e não penso em trocá-lo tão cedo. Consigo navegar, escutar música, baixar torrents, usar o terminal, codificar, conversar no Slack e outras coisas mais ao mesmo tempo usando estes editores. Com editores como Atom/Brackets e IDEs como PHPStorm não dá pra fazer isso sem aporrinhação. Eu sempre tento provar o contrário, mas ainda não consegui. 🤣 

Por outro lado também nunca gostei de IDEs. Muitos recursos de que eu não usarei ou não me interessam e, no caso do PHPStorm, eu ainda teria de pagar por isso. É exatamente os plugins que me interessam &ndash; eu posso deixar o editor do jeito que eu quero, assim como eu também faço nos navegadores. Nada a mais nem a menos do que eu preciso. Dá para ser tão produtivo quanto usar uma IDE, tudo é uma questão de saber personalizar o workflow neste sentido. O Sublime, por exemplo, dá pra fazer muita coisa inimaginável... Livros como o [Sublime Text Power User Book](https://sublimetextbook.com) e séries com a [Sublime Text Mastery do Laracasts](https://laracasts.com/series/sublime-text-mastery) estão aí para mostrar isso. Integração com terminal, Git, Composer, Gulp, Grunt, Npm, Xdebug, PHPUnit, PHP Code Sniffer, etc., etc., etc. 👍 

Nos últimos anos tenho usado mais o Sublime, isso desde de quando só existia o Sublime Text 2... Mas recentemente o VSCode tem me despertado bastante interesse! Inclusive já tenho usado ele para algumas codificações. É um editor que tem evoluído muito rápido (os últimos 8 releases foram lançados num período de 8 meses), tem ótimos recursos (o IntelliSense dele é simplesmente sensacional!), suporte a plugins (com boa oferta de plugins inclusive) e ainda consegue [ser rápido e eficiente no uso de memória](https://blog.xinhong.me/post/sublime-text-vs-vscode-vs-atom-performance-dec-2016/) - sem contar que é visualmente bem trabalhado! Se a Microsoft continuar assim tem tudo para se tornar minha primeira opção. 😄 

@flyingluscas Complementando a lista de plugins essenciais do Sublime: GitGutter, SublimeCodeIntel, SublimeLinter e TodoReview. 😃 

Para trabalhar com o banco de dados, geralmente uso MySQL e não usaria outra coisa que não o [Sequel Pro](http://sequelpro.com/) (para coisas simples) ou o [MySQL Workbench](https://www.mysql.com/products/workbench/) (para todo o resto). 😜

**Comment by hernandev** [comment]
Sou um ávido defensor do PHPStorm, por alguns motivos que vou listar abaixo.

A maioria dos plugins e customizações de editores de texto não chegam a ofertar todas as funcionalidades de uma ferramenta especializada.

A grande questão é perder muito tempo achando milhares de plugins descontinuados ou "vencidos" para resolver problemas simples com editores de texto.

Coisas como integração com GIT, novas classes inteligentes com integração direta com o namespace PSR-4, são apenas adicionais interessantes.

O verdadeiro poder de uma IDE, e no caso do PHP, o que o PHPStorm faz com grandeza é o nível de compreensão e integração com o projeto.

No PHPStorm, você pode refatorar um método e o mesmo se refletir nos usos do mesmo, clica com control em cima de um método e cair direto na definição. Esse nível de integração é praticamente impossível em editores de texto.

Pra projetos realmente grandes, com classes sendo herdadas muitas vezes, e de complexidade demasiada, é que uma IDE se sobresai. Por exemplo, ao abrir uma interface, é possível navegar diretamente para as implementações, e vice versa, se você está fazendo override em um método, dá pra ver isso nitidamente na IDE, além de dicas de padrões e performance.

Porem, eu não uso 100% tudo na IDE, coisas como GIT, Terminal e Banco de Dados, eu prefiro usar ferramentas específicas e separadas.

 Desculpe a falta de tecnicalidade na afirmação a seguir, mas comparar editores de texto com uma IDE que suporta 100% da linguagem, é como preferir um Fiat Uno a uma Ferrari, pelo motivo do Uno gastar menos gasolina.

**Comment by insign** [comment]
Concordo com o @hernandev , O Sublime Text é realmente muito leve, mas a qualidade de trabalho do PhpStorm compensa e muito. Quem não conhece ou não se esforçou pra conhecer diz que prefere outra IDE. Mas quem aprende a usar, nunca mais quer saber de outro adoçante™.

É tipo matemática e várias coisas na vida, quem não sabe usar, odeia.

**Comment by Zizaco** [comment]
Uso Sublime Text 3 com:

- CodeComplice
- DocBlockr
- SublimeLinter
- All Autocomplete
- GitGutter
- WakaTime
...E outros menos importantes

Menos é mais 😛

**edit:**

| Dev Raiz                 | Dev Nutella                          |
|--------------------------|-------------------------------------|
| Usa Vim, Sublime ou Atom | Usa NetBeans, PHPStorm, Aptana, etc |

:joy:

**edit²:**

_Pessoal, eu estou brincando sobre "dev nutella". IDEs podem sim ser muito úteis._

**Comment by zabaala** [comment]
Sem querer tretar a treta 😂 :

>**Como utilizar esse fórum:**
...
> 6. Evite perguntas de cunho especulatório, como Qual o melhor e mais belo provedor do Interior do Quixadá?. Esse tipo de discussão cabe melhor nos chats como Slack.

**Comment by joaosalless** [comment]
Atualmente, utilizo PhpStorm com:

- WakaTime
- Laravel Plugin
- Git Flow Integration

Já utilizei Gedit, Sublime Text e Atom, mas depois que conheci o PhpStorm abandonei todos os outros.

Concordo que o Sublime Text é de longe o mais leve, abre arquivos grandes sem travar e ainda utilizo-o raramente, mas quando se trata de um projeto Php, utilizo o PhpStorm. Hoje percebo como já perdi tempo tentando identificar erros bobos que uma IDE poderia identificar em tempo real. 

Concordo com @hernandev. Em projetos que utilizam muitos namespaces, muitas interfaces e heranças, uma IDE é essencial.

No que diz respeito a licença do PhpStorm, eu acho o preço justo. Vale cada centavo.

**Comment by guaracyalima** [comment]
Eu uso e indico PhpStorm pela facilidade do autocompletar.

**Comment by pxpm** [comment]
Uso o PhpStorm, gosto da interface e das funcionalidades!!

**Comment by hernandev** [comment]
@marabesi essa questão por depender de gostos pessoais, nunca chegará a uma conclusão, irei fechá-la para não constar na lista de dúvidas, mas o mesmo não deve impedir a discussão futura do tópico

**Comment by lucassena** [comment]
Ué, mas qual é o problema em continuar com o PhpStorm? Afinal, dizem que é a melhor IDE para programar em PHP.

Mas para mim a melhor é aquela que você se adapta melhor, eu por exemplo uso muito o Eclipse pelos mesmos motivos que você citou o PhpStorm, ele faz tudo isso, é free mas é um pouco mais lento em algumas situações.

Abraços

**Comment by randercarlos** [comment]
Atualmente, eu utilizo bastante o visual studio code e o eclipse PDT. Já usei PHPStorm, Atom e Netbeans e percebo que os 2 primeiros possuem muito mais plugins e atualizações. 

Pra mim, atualmente, a melhor IDE free para desenvolvimento em PHP é o Eclipse PDT porque´, como ele vem do Java, as atualizações dele são mais constantes e o autocomplete dele é gerado diretamente do código fonte do projeto. Então, independentemente do framework utilizado, o autocomplete vai conseguir localizar os métodos, classes e atributos da classe.

PHPStorm não uso por ser pago. Sempre dou preferência por IDEs gratuitas e o Netbeans parece que foi abandonado. Ele não sai dessa versão 8.2 há 2 anos e o autocomplete dele é muito ruim.

**Comment by lucassena** [comment]
Sim @randercarlos, muita gente tem preconceito com o Eclipse, mas é uma IDE muita boa e gratuita e que está ficando cada vez mais leve.

**Comment by franklinmatos** [comment]
eu particularmente uso eclipse para desenvolver java e estou usando o vscode, por ser mais leve mas não tenho experiência suficiente para dizer se é o melhor. Pegarei as indicações de plugins que o colega mencionou acima e vou testar....

**Comment by DiogoFilhoDeMorais** [comment]
Uso o Visual Code Studio para Linux.
Facilidades:
- Instalação de plugins fácil;
- Gama de plugins muito grande;
- Interface amigável;
- Atalhos resolvidos;
- Aprimoramentos constantes pela Microsoft;
- Leveza;
- Funções a perder de vista;

Dificuldades;
- A ampla variedade de plugins requer testes para se ter instalada a que te atende melhor;

Não vejo mais problemas, e sim mais benefícios.

**Comment by leonardomalves** [comment]
> Uso Sublime Text 3 com:
> 
> * CodeComplice
> * DocBlockr
> * SublimeLinter
> * All Autocomplete
> * GitGutter
> * WakaTime
>   ...E outros menos importantes
> 
> Menos é mais 😛
> 
> **edit:**
> 
> Dev Raiz	Dev Nutella
> Usa Vim, Sublime ou Atom	Usa NetBeans, PHPStorm, Aptana, etc
> 😂
> 
> **edit²:**
> 
> _Pessoal, eu estou brincando sobre "dev nutella". IDEs podem sim ser muito úteis._

Nossa, depois de 20 anos de dev descobri que sou nutella kkkkkkkkkk

**Comment by lucassena** [comment]
> > Uso Sublime Text 3 com:
> > 
> > * CodeComplice
> > * DocBlockr
> > * SublimeLinter
> > * All Autocomplete
> > * GitGutter
> > * WakaTime
> >   ...E outros menos importantes
> > 
> > Menos é mais stuck_out_tongue
> > **edit:**
> > Dev Raiz	Dev Nutella
> > Usa Vim, Sublime ou Atom	Usa NetBeans, PHPStorm, Aptana, etc
> > joy
> > **edit²:**
> > _Pessoal, eu estou brincando sobre "dev nutella". IDEs podem sim ser muito úteis._
> 
> Nossa, depois de 20 anos de dev descobri que sou nutella kkkkkkkkkk

Hahahah, eu acho muito bonito a deslumbrância dos programadores de 18-25 anos dizendo que é um programador raiz porque usa Vim, melhor ainda com o Sublime (comecei a programar antes disso existir).
