### ISSUE TITLE
Hospedagem compartilhada hostgator

### ISSUE THREAD

**Issue by msmacorin** [laravelbrasil/forum#83]
[RESOLVIDO]

Descrição Geral do Problema

## Problema Encontrado

Estou com problemas em um app que deve ser instalado numa hospedagem compartilhada do Hostgator.
Eles tem uma pasta public_html que é onde ficam os arquivos do app. Fiz clone do meu projeto lá e ai, para acesso ficou: _meudominio.com/nomedoprojeto/public_ . Depois copie todo o conteudo de dentro da pasta do meu projeto e joguei pra raiz do public_html, entao para acessar o app a url ficou _meudominio.com/public_ .

Acontece que nenhuma rota minha funciona. O que eu poderia fazer ?
Qual o melhor procedimento pra deploy num ambiente como este ?

Obrigado.

---

## Abordagem
Já tentei o seguinte:
 - já deixei APP_URL em .env como _meudominio.com/_ e como _meudomino.com/public_ => nenhum dos dois funcionou.

## Solução
Fiz o que me instruiram no facebook, basicamente é seguir os passos deste video: https://youtu.be/8rVISPgbu4M

**Comment by cagartner** [comment]
Boa noite @msmacorin.

Na discussão https://github.com/laravelbrasil/forum/issues/36 foi apresentado umas soluções para um caso parecido com o seu.

Já deu uma olhada lá?

Abraços!

**Comment by msmacorin** [comment]
Obrigado @cagartner !
Abração.
