### ISSUE TITLE
save() está duplicando os dados no banco de dados

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#85]
Descrição Geral do Problema

Pessoal, não sei por qual motivo, mas quando eu salvo um registro no banco de dados, o laravel tá criando duas linhas e não apenas umas no banco de dados. Isso aparentemente só acontece com o código:

```php
        $action = new Action();
        $action->user_id = $user_id;
        $action->action = "view";
        $action->material_id = $material;
        $action->save();`
```

## A action:

```php
public function show_file($material)
    {
        $user_id = Auth::user() ? Auth::user()->id : null;

        $action = new Action();
        $action->user_id = $user_id;
        $action->action = "view";
        $action->material_id = $material;
        $action->save();
        
        $material  =  Material::find($material);
        $file_path = 'storage' . '/' .
                     'materials' . '/' .
                      $material->file;
        return view('materials.file', [
            'material' => $material, 
            'file_path' => $file_path
        ]);
    }
```

Olha o banco de dados:
https://uploaddeimagens.com.br/imagens/sem_fsfas-png

# Solução

Resolvi fazendo uma requisição no banco de dados para olhar se já existe o arquivo salvo, se sim atualiza:

```
$action = Action::find($material);
        $action->user_id = $user_id;
        $action->action = "view";
        $action->material_id = $material;
        $action->save();

```

**Comment by cagartner** [comment]
Bom dia.

Será que essa classe "Material" não possui algum observer que cria uma action? Isso é uma requisição ajax, pode ser que esteja efetuando duas requisições, tenta criar uns logs para ver onde ta passando.

Abraços!

**Comment by gabrieldesousah** [comment]
O que seria esse observer @cagartner?


Ps.Eu não sei como criar logs.. Vou tentar descobrir na documentação do Laravel

Abraço!

**Comment by paulofreitas** [comment]
Para o *timestamp* estar diferente em ambos registros é bem provável que esta rota está sendo requisitada mais de uma vez... :wink:
