### ISSUE TITLE
Agrupamento com eloquent

### ISSUE THREAD

**Issue by gabrieldesousah** [laravelbrasil/forum#86]
Pessoal, gostaria de fazer agrupamentos avançados com Eloquent, atualmente faço com mysql puro, mas gostaria de usar outras ferramentas como paginação e por isso preciso do Eloquent

## Problema Encontrado
Atualmente uso o seguinte código:

```php
$keywords = DB::select("
        SELECT keywords, Count(keywords) AS ContKeywords
        FROM searches
        GROUP BY keywords
        ORDER BY ContKeywords DESC
        ");
```

e quero que fique do mesmo modelo disso:

```php
$contents = Content::orderby('name')->where('area = exatas')->get();
```

**Comment by deleugpn** [comment]
```
$keywords = Search::orderBy('ContKeywords')->groupBy('keywords')->get(['keywords']);
$count = $keywords->count();
```

**Comment by paulofreitas** [comment]
```php
$keywords = Search::select('keywords', DB::raw('COUNT(keywords) AS count'))
    ->groupBy('keywords')
    ->orderBy('count', 'desc')
    ->get();
```
A documentação do *Query Builder* é bem vasta: https://laravel.com/docs/5.4/queries

**Comment by Gabrieldesousah** [comment]
Resolvi fazendo uma requisição no banco de dados para olhar se já existe o arquivo salvo, se sim atualiza:

$action = Action::find($material);
        $action->user_id = $user_id;
        $action->action = "view";
        $action->material_id = $material;
        $action->save();

**Comment by gabrieldesousah** [comment]
Muitíssimo obrigado. Consegui fazer exatamente o que eu queria!

**Comment by omarkdev** [comment]
Aparentemente o problema foi resolvido, estou fechando esta issue.
