### ISSUE TITLE
Mostrar informações do servidor

### ISSUE THREAD

**Issue by maykonmendel** [laravelbrasil/forum#88]
Pessoal, boa tarde.

Eu gostaria de exibir as seguintes informações na minha página inicial:

-Servidor (IP/nome/porta)
-Banco de dados
-Versão do Sistema
-Versão do Framework

Como proceder utilizando o laravel?

**Comment by zabaala** [comment]
As informações de servidor e banco, você pode encontrar em $_SERVER.
Versão do sistema: 

 - Se for o sistema operacional, roda um shell_exec("uname -a").
 - Se for do seu sistema você pode pegar uma informação do seu arquivo .env; pode pegar o commit do seu git junto com a tag ou algo do gênero.

Versão do framework pode pegar a versão do composer (?!); ou da pasta vendor (?!); Ou colocar essa informação no seu .env.

**Comment by maykonmendel** [comment]
@zabaala 

Valeu pelas informações. Vou tentar aqui e dou retorno.

**Comment by maykonmendel** [comment]
@zabaala 

O comando $_SERVER só roda em Linux? Tentei dar um php echo e não rodou.

**Comment by IgorDePaula** [comment]
nao, o $_SERVER eh do php e pega informacoes do servidor web (apache/nginx) voce nao conseguiu porque ele eh um array, precisa ser var_dump ou print_r.

**Comment by maykonmendel** [comment]
@IgorDePaula 

Sim, me lembrei disso. Tô voltando a usar php agora, então algumas coisas eu havia esquecido. Valeu pelo lembrete.

**Comment by maykonmendel** [comment]
Resolvi com o seguinte comando: $dot = new Dotenv\Dotenv(base_path()); $dot->load(); echo getenv('DB_HOST');

**Comment by JoseCage** [comment]
@maykonmendel não está usando [Laravel](https://laravel.com)??

Caso sim, para usar o **dotenv** não precisa instanciar como acima. Basta usar por exemplo:

``
$dbhost = env('DH_HOST');
``

**Comment by maykonmendel** [comment]
@JoseCage 

Eu pesquisei mais a fundo e acabei encontrando o comando que você citou. Funcionou e já estou provendo as outras variáveis que preciso.

**Comment by JoseCage** [comment]
Opa.. Que bom que funcionou.. :+1: 

Bom trabalho meu caro colega..

**Comment by paulofreitas** [comment]
Complementando o que o @zabaala disse, para pegar a versão do framework use `app()->version()` ou `app()::VERSION`. 👍

**Comment by zabaala** [comment]
@paulofreitas de onde vem a informação contida em app()::VERSION / app()->version?

Procurei antes de dar a minha primeira resposta e não encontrei 😄

**Comment by paulofreitas** [comment]
> @paulofreitas de onde vem a informação contida em app()::VERSION / app()->version?
>
> Procurei antes de dar a minha primeira resposta e não encontrei 😄 

Da classe `Illuminate\Foundation\Application`: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php 😃 

O *helper* `app()` retorna uma instância dela. 👍
