### ISSUE TITLE
Undefined constant 'App'

### ISSUE THREAD

**Issue by pxpm** [laravelbrasil/forum#9]
ENV:
PHP Version => 7.0.13-0ubuntu0.16.04.1

Composer é uma fresh install, não tem nada a não ser o laravel
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\"`

apache.conf

<Directory /var/www/>
 Options Indexes FollowSymLinks MultiViews
AllowOverride None
Order allow,deny
allow from all
Require all granted
</Directory>

<VirtualHost *:443>
DocumentRoot /var/www/html/laravel/public
<Directory /var/www/html/laravel/public>
AllowOverride Options=All,MultiViews
Order allow,deny
            allow from all
SSLRequireSSL
</Directory>
SSLEngine on
SSLCertificateFile /etc/letsencrypt/live/cbsoft.life/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/cbsoft.life/privkey.pem
ServerName cbsoft.life
<VirtualHost>

## Problema Encontrado
Boas pessoal, estou com um problema, que não estou a ver como resolvo.

A parte da configuração do servidor e das vhosts correu bem, penso eu, uma vez que consigo iniciar a composição da app.
O meu problema está em que ele ao inicializar a APP, ele diz-me que a variável não está definida.

`PHP Fatal error:  Uncaught Error: Undefined constant 'App' in /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:714\nStack trace:\n#0 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): ReflectionClass->newInstanceArgs(Array)\n#1 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\\Container\\Container->build('App\\\\Http\\\\Kernel')\n#2 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\\Container\\Container->make('App\\\\Http\\\\Kernel')\n#3 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(239): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Kernel', Array)\n#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(678): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application))\n#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Con in /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 714`

 Eu nem sei que info adicional vos posso dar mais para me ajudarem a resolver, mas o que precisarem da minha parte digam-me pff, estou a ficar maluco com isto.

**Ambiente de desenvolvimento:** Ubuntu 16, apache2, php7, mysql.

## **EDIT: O meu ficheiro .htaccess na pasta public não tem o Options -MultiViews, porque se puser lá isso diz que os Options não podem estar nesse ficheiro, ao remover, dá este erro. **

[Thu Feb 09 12:40:47.400654 2017] [core:alert] [pid 15602] [client 82.155.79.172:63077] /var/www/html/laravel/public/.htaccess: Options not allowed here

Actualizado em resposta a @cagartner and @zabaala

**Comment by cagartner** [comment]
Bom dia @pxpm , tem como atualizar o issue com infos como: Versão do PHP utilizada, Versão do Laravel e que tipo de ambiente você está trabalhando ex: Linux, Windows ou Mac.

Essas infos podem ajudar a solucionar o problema

Abraços!

# Atualização: Vi que tem infos no título

Mas faltou a versão do Laravel :)

**Comment by zabaala** [comment]
@pxpm posta também o teu composer.json.

**Comment by zabaala** [comment]
Cara, eu particularmente não consigo visualizar nenhum motivo para o erro, mas verificaria o seguinte:
* Verificaria a estrutura de pastas pra ver se ela corresponde ao que está definido no composer.json;
* Verificaria meu composer.json pra saber se realmente não tem nada escrito errado (espasços, pontos, etc);
* Seguiria a stack trace pra tentar encontrar o erro;
* Dependendo do que encontrasse rastreando a stack, olharia se não há algo errado na escrita do código dessas namespaces, já que ela está sendo considerada como uma constante;
* Tentaria fazer esse autoload na mão;
* Tentaria monitorar os logs do servidor;
* E tentaria mexer em algo do PHP ou até mesmo rodar em outro ambiente.

Esse é seu ambiente de produção?

**Comment by cagartner** [comment]
As permissões de pastas estão corretas?

**Comment by pxpm** [comment]
@zabaala Eu penso que isto esteja relacionado com o facto de o apache não me estar a deixar utilizar os options no .htaccess, e os namespaces não estarem a ser resolvidos.
O composer está o por defeito do laravel, apenas fiz um composer require, e um composer install para instalar o laravel e as depedencies. já vi o env tem lá a app key etc. 
Não tenho mais nada na stack, apenas se activo o Options -Multiviews no .htaccess ele dá erro que não pode estar lá o options, se retiro, ele corre até dar aquele erro do 'App'

@cagartner podes ajudar-me a verificar isso ? eu já dei 777 para storage e 755 para a pasta laravel, podes ajudar-me a ver se está tudo correcto ?

**Comment by cagartner** [comment]
Opção 1,  isolar se  o problema está no apache:
Tenta executar `php artisan serve` na aplicação e verficar se o erro persiste.

Opação 2, isolar se o problema está nas permissões:
Na dúvida dá um `chmod -R 777` na pasta do projeto, se rodar depois corrige para a permissão correta.

**Comment by pxpm** [comment]
@cagartner o que eu fiz:

chmod -R 777 na pasta laravel(nome do meu projecto)

sudo php artisan serve --host 0.0.0.0 --port 80 (parei o apache)

Não me dá o erro do Options no ficheiro .htaccess pelo que penso que isso esteja resolvido, mas o problema não residia ai então, porque continua a dar-me o mesmo erro do constant 'App'

**Comment by zabaala** [comment]
Tenta:
```
<Directory /var/www/>
Options Indexes FollowSymLinks
AllowOverride All
Order allow,deny
allow from all
Require all granted
...
```
Mas não acho que seja isso. Parece algum problema com o código, já que quem resolve as namespaces é o autoload do PHP e não o Apache.

**Comment by zabaala** [comment]
>Não me dá o erro do Options no ficheiro .htaccess pelo que penso que isso esteja resolvido, mas o problema não residia ai então, porque continua a dar-me o mesmo erro do constant 'App'

Realmente não vai ser exibido o erro, já que `php artisan serve` utiliza o built-in server do PHP e ele não utiliza .htaccess.

**Comment by pxpm** [comment]
@zabaala reactivei o apache, resolvi o problema do multiview not allowed com as directivas allowoverride, mas o erro 'App' continua lá, desta vez o ficheiro .htaccess está exactamente igual como vêm no laravel.

Como posso fazer debug ao autoload? crio outro ficheiro index.php e chamo lá só o autoload? mas não é isso que  ele está a fazer ao chamar no index.php?
`require __DIR__.'/../bootstrap/autoload.php';`
?

**Comment by pxpm** [comment]
@zabaala e @cagartner 
Não me perguntem como, nem porque ... eliminei a pasta do laravel, voltei a criar o project de novo com o composer e já funcionou .
Não faço ideia como nem porque porque a unica coisa que eu tinha feito na instalação do laravel foi mesmo criar o projecto com o composer, nem tinha posto bases de dados nem nada ... 
e agora, apaguei a pasta e criei de novo, dei as mesmas permissões e o projecto e funcionou ... sem alterar nada na conf do apache nem nada (porque isso já estava bem configurado)
Obrigado a todos, e gostava de deixar aqui a solução, mas realmente não sei o que é que mudou uma vez que isto era um teste e não tinha alterado nada á instalação inicial do laravel ..

**Comment by zabaala** [comment]
Que bom que deu certo. =)
