### ISSUE TITLE
Routes::auth em subdomínio

### ISSUE THREAD

**Issue by rogerio-pereira** [laravelbrasil/forum#91]
Olá pessoal como eu faço para usar o Routes::auth(); somente dentro de um subdomínio?

o site principal nao vai usar, então para evitar qualquer problema queria deixar somente dentro do subdomino

assim está o meu arquivo de rotas

Route::group([
                'domain' => 'painel.'.str_replace('http://','',env('APP_URL')),
                'namespace' => 'Painel'
            ], function() 
{
     Auth::routes();
     //Rotas do painel
});

Erro que está dando
Class App\Http\Controllers\Painel\Auth\LoginController does not exist

**Comment by IgorDePaula** [comment]
Ai sao duas coisas diferentes? So esta usando o auth em um subdominio, tente usar um middlware para fazer o que quer, agora, sobre o erro que recebeu, vc colocou um namespace na rota, mas nao existe este namespace no seu app, e nao esta encontrando o controller la.

**Comment by rogerio-pereira** [comment]
valeu consegui resolver

**Comment by IgorDePaula** [comment]
Poste a solução para que outros com o mesmo problema nao passe o mesmo perengue.

**Comment by rogerio-pereira** [comment]
Desculpe, usei apenas o middleware no routes.php
