### ISSUE TITLE
Problema ao configurar Apache Virtual Host no Debian para trabalhar com Laravel

### ISSUE THREAD

**Issue by MestreRico** [laravelbrasil/forum#95]
Estou tentando configurar um virtual host no apache para trabalhar com Laravel, no entanto só consigo acesso quando insiro o /index.php no final da URL.

No windows usando wamp consegui realizar a parametrização normalmente.

acesso:
appcliente.dev

já no linux só funciona utilizando:
appcliente.dev/index.php

## Problema Encontrado
Ao tentar acessar um virtual host do apache o mesmo só funciona se colocar o index.php no final da URL.

---

## Abordagem
Configurações que estou utilizando:

arquivo hosts do debian:
`127.0.0.1       appcliente.dev`

Arquivo appcliente.conf:

```
<VirtualHost *:80>
     
        ServerName appcliente.dev
        ServerAlias appcliente.dev
        DocumentRoot /var/www/html/appCliente/public
        DirectoryIndex index.php
        <Directory  "/var/www/html/appCliente/public/">
                Options +Indexes +Includes +FollowSymLinks +MultiViews
                AllowOverride All
                Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

       
</VirtualHost>
```

Comandos utilizados:

`sudo a2ensite appcliente.conf`

`sudo service apache2 restart`

Erro apresentado:

```
Not Found

The requested URL /login was not found on this server.

Apache/2.4.10 (Debian) Server at appcliente.dev Port 80

```
---

Será que alguém pode me ajudar?

Desde já obrigado.

#### Resolvido

Utilizei os comandos indicados pelo @joaosalless e habilitando o rewrite.

`sudo a2enmod rewrite`

`sudo service apache2 restart`

**Comment by joaosalless** [comment]
Você precisa habilitar o módulo rewrite do apache para que todas as requisições sejam direcionadas para o arquivo index.php da pasta public e assim acessem as rotas da sua aplicação. Estas regras de redirecionamento ou reescrita de urls como muitos preferem chamar, são configuradas no arquivo .htaccess que encontra-se na pasta public.

Comando para habilitar o módulo rewrite:
```shell
sudo a2enmod rewrite
```

Em seguida reinicie o serviço

```shell
sudo service apache2 restart
```

**Comment by MestreRico** [comment]
Obrigado @joaosalless era este detalhe mesmo, no windows já havia habilitado o rewrite quando instalei.

No linux não havia habilitado, muito obrigado.
