### ISSUE TITLE
Diminuir extensão do Array

### ISSUE THREAD

**Issue by ronicec** [laravelbrasil/forum#96]
Pessoal estou precisando de uma ajuda simples. 
Atualmente possuo este retorno:

```
{
  "error": null,
  "result": [
    [
      [
        {
          "cliente_id": 1,
          "nome": 1,
          "telefone": 2
        }
      ]
    ]
  ]
}
``` 
Eu preciso diminuir a extensão do meu array em -1, antes:
```
[
    [
      [
```
Para
```
[
      [
```

Estou usando desta maneira para retornar os meus dados...

```
$result = Clientes::query();
$result->with(['clientes' => function($query) {
            $query->select('cliente_id', 'nome', 'telefone');
        }]);
$result = $result->get()->pluck('clientes');
```

Estou usando o recurso Pluck para manter apenas os dados que é do clientes, ou seja, os dados da tabela principal estou ignorando.
Porém como que faço para diminuir essa dimensão do array? No caso ali está contando o Array da tabela principal também e quero tirar isso.

Obrigado!

**Comment by omarkdev** [comment]
Você pode fazer:
```php
$value['result']->map(function($result){ return $result[0]; });
```

**Comment by ronicec** [comment]
Opá! 
Deu certo...

Obrigado omarkdev
