### ISSUE TITLE
Como salvar dados relacionados

### ISSUE THREAD

**Issue by victorhugorch** [laravelbrasil/forum#97]
Descrição Geral do Problema

## Problema Encontrado
Quando eu tenho uma relação entre dos modelos HasMany/HasMany, eu uso o método sync() para salvar os dados no Banco. 

O laravel procura a tabela modelo_modelo e salva. Quando eu tenho uma relação HasOne/BelongsTo como eu salvo os dados na tabela?

---

## Abordagem
Já tentei ->update() mas não funcionou.

## Atualização 1
Se precisar atualizar a sua pergunta, adicione seções como essa.

---

## Solução
Se o problema foi resolvido, adicione uma seção de solução como essa

**Comment by joaosalless** [comment]
A classe de relacionamento HasOne extende a classe HasOneOrMany e conforme podemos ver no código fonte desta classe, existem os métodos `save()` e `saveMany()`:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L251

Então para um relacionamento HasOne, o método a ser usado é o `save()`.


A classe de relacionamento BelongsTo possui os métodos `associate()`:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L210

**Comment by victorhugorch** [comment]
Muito obrigado, @joaosalless!
